import type { Metadata } from "next";
import { Cormorant_Garamond, Lato, Questrial,Pattaya } from "next/font/google";
import "./globals.css";

const questrial = Questrial({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-questrial",
});

const lato = Lato({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-lato",
});

const lato_light = Lato({
  subsets: ["latin"],
  display: "swap",
  weight: "300",
  variable: "--font-lato_light",
});

const cormorant_garamond = Cormorant_Garamond({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-cormorant_garamond",
});

const pattaya = Pattaya({
  subsets: ['latin'],
  display: 'swap',
  weight: '400',
  variable: '--font-pattaya',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${questrial.variable} ${lato.variable} ${lato_light.variable} ${cormorant_garamond.variable} ${pattaya.variable}`}>
      <body
        className="text-neutral bg-white font-questrial"
      >
        {children}
      </body>
    </html>
  );
}
