const fertilityReview = [
    {
      "id": 1,
      "center_name": "hyderabad",
      "clinic_location": "banjara hills",
      "city": "Hyderabad",
      "rating": 4.9,
      "name": "Renuka",
      "reviews": "Struggling with female infertility treatment in Hyderabad was overwhelming, and I felt lost searching for the right fertility center in Hyderabad. After visiting Dr. Durga G. Rao, I finally found hope. Her expertise and care made all the difference. With a personalized treatment plan, I now have a positive outcome. Truly grateful!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXKUFBmfsV0gy5GjWQIRbizGSvVqX9KLPoI-Sp8cgi1M-hMSqZK=w56-h56-p-rp-mo-br100",
      "review_link": "maps.app.goo.gl/FiYnims6MH4tzcTY8"
    },
    {
      "id": 2,
      "center_name": "hyderabad",
      "clinic_location": "gachibowli",
      "city": "Hyderabad",
      "rating": 4.9,
      "name": "Navaneeth Rao",
      "reviews": "After months of unsuccessful attempts, I was unsure about the right fertility treatment in Hyderabad. Visiting Dr. Avanthi Vellala’s care and advanced approach made my journey smooth. Grateful for the support!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKTpj2xInuEhuIBMrsrTvhQl5zOMoPsdj4vFgl-ECbUlzqHBw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/KkY24v8QbYyt4VnZA"
    },
    {
      "id": 3,
      "center_name": "hyderabad",
      "clinic_location": "dilshuknagar",
      "city": "Hyderabad",
      "rating": 4.9,
      "name": "Bhagya Sri",
      "reviews": "Finding a reliable fertility hospital near me was challenging. I needed the best care, and Dr. Parinaaz Parhar, my dream of starting a family became a reality. Highly recommend her for anyone seeking the best infertility specialist in Hyderabad!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXxcZmAmCFy_irK8Z1G0-QesngWzOJ33cVvJT6EVsVQ6-nVSXMfwA=w45-h45-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/n8KpemCkvFN7Y9k3A"
    },
    {
      "id": 4,
      "center_name": "hyderabad",
      "clinic_location": "miyapur",
      "city": "Hyderabad",
      "rating": 4.9,
      "name": "Medak Rakhi",
      "reviews": "Choosing the best fertility hospital in Hyderabad felt overwhelming until I met Dr. Srinivasa Varalakshmi Yakasiri, and the results were amazing. Anyone looking for the best fertility doctor in Hyderabad should definitely visit her.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVV6V5enWzRgdT42hx5f3KnIzzi148ovO1Z-HYC4ceTmcPIO2m5=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/FSjVCbewBBfNc3zf8"
    },
    {
      "id": 5,
      "center_name": "banjara hills",
      "clinic_location": "banjara hills",
      "city": "Banjara Hills",
      "rating": 4.9,
      "name": "Nandini Gubba",
      "reviews": "I was looking for a trusted Hyderabad fertility center, and my journey led me to Dr. Durga G. Rao, I felt confident in her expertise. The clinic’s modern treatments and warm support made the process smooth. I’m now blessed with positive results and highly recommend them!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJMuILKHklgB4gAnuofZ3OFrlF5r6F62uoxVfw2kQ6gOhbHBQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/tv5K6FriEap2rhTm9"
    },
    {
      "id": 6,
      "center_name": "banjara hills",
      "clinic_location": "banjara hills",
      "city": "Banjara Hills",
      "rating": 4.9,
      "name": "Someswara Rao Teppala",
      "reviews": "Facing issues with ifemale infertility treatment in hyderabad was emotionally challenging. After visiting Dr. Durga G. Rao, I felt reassured. She patiently explained the process, and her expertise made all the difference. Now, I am hopeful and grateful for this journey. Highly recommend her!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUJmn2AuP2RSwVcihiMoFp_9WWguCP8ohhesBFo8Lz6Z9_bOubg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/YPhvr9tDQt1r3QHY6"
    },
    {
      "id": 7,
      "center_name": "banjara hills",
      "clinic_location": "banjara hills",
      "city": "Banjara Hills",
      "rating": 4.9,
      "name": "Upender Gali",
      "reviews": "I searched for the best ffertility treatment in hyderabad and found Dr. Durga G. Rao, and the treatment was tailored to my needs. The doctor’s support and knowledge made my experience stress-free. Truly grateful for this journey!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWO_ovn6diLSrr6x5dBxi2C0fQOPIb_YbUt_5346gm7mlcnGqZl=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/db2WbMTNoZPqfFwr6"
    },
    {
      "id": 8,
      "center_name": "banjara hills",
      "clinic_location": "banjara hills",
      "city": "Banjara Hills",
      "rating": 4.9,
      "name": "Umeera Khan",
      "reviews": "Finding the best infertility specialist in hyderabad was not easy. But after meeting Dr. Durga G. Rao it feels relief!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJw9BIkRtWFE1BgAZ3cpMMABe2DE3xKeuyiPaURgKPjAxJNSg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/qTw1hgdX28eoXHUV8"
    },
    {
      "id": 9,
      "center_name": "gachibowli",
      "clinic_location": "gachibowli",
      "city": "Gachibowli",
      "rating": 4.9,
      "name": "Aaliya Sheikh",
      "reviews": "I was looking for a best fertility hospital in hyderabad, and I found Dr. Avanthi Vellala, and now I feel confident about my treatment. Highly recommended!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVaryLP-qAbGfBXYjLtdaQi58njQC1hz2T-zOdhn2tyV9pptEe2Tw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/Fqz3rDx5KXfc9JwQ9"
    },
    {
      "id": 10,
      "center_name": "gachibowli",
      "clinic_location": "gachibowli",
      "city": "Gachibowli",
      "rating": 4.9,
      "name": "Lekhan Naga",
      "reviews": "The struggle of infertility led me to search for the best hyderabad fertility center. I found Dr. Avanthi Vellala, and it was the best decision. The entire experience was smooth, and the personalized treatment gave me hope. So grateful for the support!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocI5mA_d95nPa0fHlv9ncDPrqwECj6JM2LGpP8wrGZ7B46HdXA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/G6QhNE1UQXxgcB3U6"
    },
    {
      "id": 11,
      "center_name": "gachibowli",
      "clinic_location": "gachibowli",
      "city": "Gachibowli",
      "rating": 4.9,
      "name": "Kaniki Shekar",
      "reviews": "Finding a trusted female infertility treatment in hyderabad was overwhelming. After meeting Dr. Avanthi Vellala, I finally felt hopeful. She listened to my concerns, explained everything clearly, and guided me through the process. Grateful for her support and expertise!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLipXYIcAPExyu_HZLcNechNkVeyScHkmBmOeiAm_22ckyP=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/bvEnx187Q2SrYtKQ6"
    },
    {
      "id": 12,
      "center_name": "gachibowli",
      "clinic_location": "gachibowli",
      "city": "Gachibowli",
      "rating": 4.9,
      "name": "Lakshmi Sarada",
      "reviews": "Struggling with infertility, I searched for the fertility treatment in hyderabad. Dr. Avanthi Vellala, I feel positive about my future. Highly recommend her!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJdA5mFa1KosgA1bVPQqhMPUKmCwtPMxHRivQiwfUSABq-FTA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/kSfUiEEEjcFmBFUV6"
    },
    {
      "id": 13,
      "center_name": "dilshuknagar",
      "clinic_location": "dilshuknagar",
      "city": "Dilshuknagar",
      "rating": 4.9,
      "name": "Rajitha",
      "reviews": "I was looking for best infertility specialist in hyderabad and i was bit nervous about starting my journey at a fertility hospital in Hyderabad, but Dr. A Tejashree, and the treatment process was smooth. I truly appreciate her care and expertise!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocI-ED_3STq78dZjSdAzoq1vnownZ1JgknPExw26IZZOOgDXKg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/FNwAv61a6Km2EcMq5"
    },
    {
      "id": 14,
      "center_name": "dilshuknagar",
      "clinic_location": "dilshuknagar",
      "city": "Dilshuknagar",
      "rating": 4.9,
      "name": "Tulasi Vinnu",
      "reviews": "Looking for the best fertility hospital in hyderabad was difficult, but meeting Dr. Bogi Reddy Mounika, kind, and incredibly knowledgeable. Her treatment plan was well-structured, and I now have hope for a positive outcome!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKMgoqB8uNKk6gRD6JQQRM7zTcjdcSkoRyWOcr7OLaj99sCWA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/2yKfm4asq1GMpuQ48"
    },
    {
      "id": 15,
      "center_name": "dilshuknagar",
      "clinic_location": "dilshuknagar",
      "city": "Dilshuknagar",
      "rating": 4.9,
      "name": "Gavvala Srinivas",
      "reviews": "Choosing the right hyderabad fertility center was crucial for me. Dr. Sai Manasa Darla, making my experience smooth and stress-free. Highly recommend her expertise!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKMMs_ocH0w9LsaqPdWN8jhI8p_cL8N7XyTbuApk4gmDKAX3w=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/eM7rKDYKWNjtqt7QA"
    },
    {
      "id": 16,
      "center_name": "dilshuknagar",
      "clinic_location": "dilshuknagar",
      "city": "Dilshuknagar",
      "rating": 4.9,
      "name": "Raj Bag",
      "reviews": "Struggling with infertility was emotionally draining, and I needed the bestfemale infertility treatment in hyderabad. Meeting Dr. Sai Manasa Darla, and I feel confident about the future!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKkOoaWijfwPb_UnLGYnnxWOys14Zk64Gb8HUMIbMOc1ZRtAg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/SwN1D3yx7r4rXJff9"
    },
    {
      "id": 17,
      "center_name": "secunderabad",
      "clinic_location": "secunderabad",
      "city": "Secunderabad",
      "rating": 4.9,
      "name": "Harikrishna Boini",
      "reviews": "I was looking for a trusted fertility treatment in hyderabad, and I’m glad I found Dr. Parinaaz Parhar, and I now feel hopeful. Highly recommended!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKGrowOzdEQfyrpQbX110iIpuIj3ZedlLv3scrurCilai75rg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/sCsGYqhc3PbV1mMFA"
    },
    {
      "id": 18,
      "center_name": "secunderabad",
      "clinic_location": "secunderabad",
      "city": "Secunderabad",
      "rating": 5,
      "name": "Hardik Mehta",
      "reviews": "Finding the best infertility specialist in hyderabad wasn’t easy. But after consulting Dr. Parinaaz Parhar, I knew I was in safe hands. She listened to my concerns, offered the best treatment, and made the entire journey stress-free. Grateful for her expertise!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIwXRLZFbaSm3J8S-48YPzvt53xlgzY5A92PAcC2aCsLTUREg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/tF6XYUPFmQMhqkNm7"
    },
    {
      "id": 19,
      "center_name": "secunderabad",
      "clinic_location": "secunderabad",
      "city": "Secunderabad",
      "rating": 4.9,
      "name": "Syamala Ramu",
      "reviews": "The journey to parenthood seemed difficult until I found the best fertility hospital in hyderabad. Dr. Parinaaz Parhar, explained the entire process, and guided me with the best treatment. I’m now filled with hope. Thankful for such great care!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWqVoW6QXFyc0tGSejh39vXYp61SqVH_6WDt4eyRZtgSKQsgzaI=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/E84o9Kqd3QkEf9t48"
    },
    {
      "id": 20,
      "center_name": "secunderabad",
      "clinic_location": "secunderabad",
      "city": "Secunderabad",
      "rating": 4.9,
      "name": "Gangula",
      "reviews": "Searching for the top hyderabad fertility center was exhausting. Meeting Dr. Parinaaz Parhar-free. I highly recommend her for anyone seeking the best fertility care!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIxFQjkN6BhNFYe0QUZJ3zTa7ZmPMsRAINfGQTu7xcwSxrpDQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/UiPcXYQ3BJDdakGY8"
    },
    {
      "id": 21,
      "center_name": "miyapur",
      "clinic_location": "miyapur",
      "city": "Miyapur",
      "rating": 4.9,
      "name": "Hari Brahmeswara Reddy Kovvuri",
      "reviews": "The uncertainty of infertility made me anxious. I searched for the best fertility center in hyderabad and found Dr. Srinivasa Varalakshmi Yakasiri, and I now feel hopeful about the future!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXcTSSs5eIUWMrOMgpjPQgSAkx5Y58IRPVDhVGSsm-ivm3er8q-=w56-h56-p-rp-mo-ba4-br100",
      "review_link": "https://maps.app.goo.gl/cdpjmbj96MQyrvcz8"
    },
    {
      "id": 22,
      "center_name": "miyapur",
      "clinic_location": "miyapur",
      "city": "Miyapur",
      "rating": 4.9,
      "name": "Anusha Bontha",
      "reviews": "I was looking for a reliable fertility treatment in hyderabad, and meeting Dr. Srinivasa Varalakshmi Yakasiri-structured treatment plan. I’m so grateful for her guidance and expertise!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocK2Rg4DEzwEbqSfXri9_umr7sx-BVW6l21kua4STaSYwKZ_0w=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/SHcvrFj7MTpBhA377"
    },
    {
      "id": 23,
      "center_name": "miyapur",
      "clinic_location": "miyapur",
      "city": "Miyapur",
      "rating": 4.9,
      "name": "Navaneeth Rao",
      "reviews": "Finding the best infertility specialist in hyderabad was my priority, and Dr. Srinivasa Varalakshmi Yakasiri-free. I highly recommend her to anyone facing fertility challenges!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKTpj2xInuEhuIBMrsrTvhQl5zOMoPsdj4vFgl-ECbUlzqHBw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/KkY24v8QbYyt4VnZA"
    },
    {
      "id": 24,
      "center_name": "miyapur",
      "clinic_location": "miyapur",
      "city": "Miyapur",
      "rating": 4.9,
      "name": "Shirley George",
      "reviews": "Choosing the best fertility hospital in hyderabad was overwhelming, but meeting Dr. Srinivasa Varalakshmi Yakasiri!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUmLGJZ9Lzd-qILCt4gdLl6M7xL743q4BoiVJhHy09GdE2BH5bhWQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/ryH671hiknmvZdNS9"
    },
    {
      "id": 25,
      "center_name": "kompally",
      "clinic_location": "kompally",
      "city": "Kompally",
      "rating": 5,
      "name": "Jarupula Vanditha",
      "reviews": "The search for the best hyderabad fertility center ended when I met Dr. Meera Jindal, and I now feel hopeful about my journey ahead!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjViJX9oQ9qwkdEpIgLUMQ4ij65aQ6lwQSMRhJynRW6r85umOgYR=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/5XGSjn2JekPiXf1S9"
    },
    {
      "id": 26,
      "center_name": "kompally",
      "clinic_location": "kompally",
      "city": "Kompally",
      "rating": 5,
      "name": "Pavan Thati",
      "reviews": "Facing infertility was tough, and I wanted the female infertility treatment in hyderabad. Meeting Dr. Meera Jindal, and the treatment was smooth. I feel hopeful and thankful for her expert care!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVus2iJKmiCvpXBr9o8gWNDBDgCd26yTQUy2bpoq7HlY2-V_fSyew=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/MHprTCVZ5sEhLkm76"
    },
    {
      "id": 27,
      "center_name": "kompally",
      "clinic_location": "kompally",
      "city": "Kompally",
      "rating": 5,
      "name": "Hrishabh",
      "reviews": "I needed the fertility treatment in hyderabad and found Dr. Meera Jindal, knowledgeable, and guided me every step of the way. The treatment process was comfortable, and I finally see hope. Highly recommended!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVNVV8YharMC-nxNhyzS1reAODVxyPKdkaQmUMe1BJmIkESXL5y=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/v2ARN6EZeyvDzeaS6"
    },
    {
      "id": 28,
      "center_name": "kompally",
      "clinic_location": "kompally",
      "city": "Kompally",
      "rating": null,
      "name": "kalyan kumar",
      "reviews": "Choosing the right best infertility specialist in hyderabad was overwhelming, but Dr. Meera Jindal!",
      "profile_picture": null,
      "review_link": null
    },
    {
      "id": 29,
      "center_name": "uppal",
      "clinic_location": "uppal",
      "city": "Uppal",
      "rating": 4.9,
      "name": "Vinod Kumar Aitipamula",
      "reviews": "The search for the best hyderabad fertility center was exhausting until I met Dr. M V D Aruna, yet compassionate. The treatment plan was personalized, and I now feel confident about the future. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjV2-uEOl8kSmfKYgIcKfQDjXQ9uSsoTPUNyd2SCVD6MCHDzPvE=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/g9iymmWGKKB9HD978"
    },
    {
      "id": 30,
      "center_name": "uppal",
      "clinic_location": "uppal",
      "city": "Uppal",
      "rating": 4.9,
      "name": "Krishnamohan Kunthipuram",
      "reviews": "Finding a trustworthy IVF specialist in Hyderabad was important for me. Dr. M V D Aruna, patiently explained everything, and ensured I felt comfortable. Her expertise made the process much easier. Grateful for such great care!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLiolgNvVj1OjALIn9i0ZQ6G8RTjIKW9ALllx05hkq7Vt81Iw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/61GKBJD7ZUZt28vj6"
    },
    {
      "id": 31,
      "center_name": "uppal",
      "clinic_location": "uppal",
      "city": "Uppal",
      "rating": 4.9,
      "name": "Poolapalli Chinnari",
      "reviews": "The journey of infertility was overwhelming, but finding the bestfemale infertility treatment in hyderabad changed everything. Dr. M V D Aruna, explained all options, and provided an effective treatment plan. I now have hope for the future. Truly grateful!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJkDO8eKvwFMo64UNbC13KvZJ7FtnhcUqe8-Ec1dGOFL1u9kg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/Md42qHzCqEk5QJYr6"
    },
    {
      "id": 32,
      "center_name": "uppal",
      "clinic_location": "uppal",
      "city": "Uppal",
      "rating": 4.9,
      "name": "Navya Jonnadhula",
      "reviews": "I was searching for a reliable fertility treatment in hyderabad, and meeting Dr. M V D Aruna, and I feel hopeful again!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJVH0o6Q7Cer9XUrE4tcn5Qub7iiuuSZTZB4ThDlG79K7Cm9w=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/gzc5AwhSNhy4EH6bA"
    },
    {
      "id": 33,
      "center_name": "Hanamkonda",
      "clinic_location": "Hanamkonda",
      "city": "Hanamkonda",
      "rating": 4.7,
      "name": "Bala Krishna",
      "reviews": "Choosing the best infertility center was tough, but Dr. Jalagam Kavya Rao. She listened to my concerns and designed a personalized treatment plan. The experience was positive, and I highly recommend her!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjW-lE6tP5h5DoUMNrfC71mwbGnpJgyi4zMAPW8bhO_5UXs7WJI7=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/3SfsZZWQmH8rbitX9"
    },
    {
      "id": 34,
      "center_name": "Hanamkonda",
      "clinic_location": "Hanamkonda",
      "city": "Hanamkonda",
      "rating": 4.7,
      "name": "Bhukya Suresh Nayak",
      "reviews": "I was looking for fertility consultation and found Dr. Jalagam Kavya Rao, I now have hope for a successful outcome.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjX8V10HJUFGi3sKhRr8GZJFL7yQ5b_I-_T5zCh5pVmRbTlQheaK7A=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/qM9qGkrjsHXfZr6w6"
    },
    {
      "id": 35,
      "center_name": "Hanamkonda",
      "clinic_location": "Hanamkonda",
      "city": "Hanamkonda",
      "rating": 4.7,
      "name": "Sangeetha Rani Yanamanagandla",
      "reviews": "I was searching for the top fertility consultation, then i met Dr. Jalagam Kavya Rao, kind, and extremely knowledgeable. I feel lucky to have found her for my fertility journey.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocK4QoOqj4nR9OoqWFQ2JGaYCS8sBVgUaAzdlSkBnElXfdj_VQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/YokoGx2CFdgkh6oJ9"
    },
    {
      "id": 36,
      "center_name": "Hanamkonda",
      "clinic_location": "Hanamkonda",
      "city": "Hanamkonda",
      "rating": 4.9,
      "name": "Sathish Yadav Sathish",
      "reviews": "Dealing with infertility was stressful, but finding the best IVF fertility consultation gave me hope. Dr. Jalagam Kavya Rao",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJrkoJZO2hgnJOnGH3W6H4qVNdyaJRd0FI_tMnEtSYvPS06Sw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/PwxwSTwERz6Y38CT9"
    },
    {
      "id": 37,
      "center_name": "karimnagar",
      "clinic_location": "karimnagar",
      "city": "Karimnagar",
      "rating": 5,
      "name": "Bandi Mamatha",
      "reviews": "I needed a trusted best fertility hospital near me, and I’m so glad I found Dr. Jigna Tamagond, and I now feel positive about my future. Highly recommended!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJ0aM72z0UR7aQxic9hXu43CGrS2P17Yevbx9t8jyCNOKXK0g=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/zJBSZApFpMpoEvEZ8"
    },
    {
      "id": 38,
      "center_name": "karimnagar",
      "clinic_location": "karimnagar",
      "city": "Karimnagar",
      "rating": 5,
      "name": "Prashanth Chinni",
      "reviews": "Struggling with infertility was tough, but after visiting the best fertility hospital near me, I finally found oasis fertility karmnagar and then i met Dr. Jigna Tamagond her analysis and suggestion amazed me!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUnL9m4u_IdKx-SjsRaD9t9aLs4I4V7xEux7VQEudM6a-oKJ88=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/z5usb7bNuseNho5c7"
    },
    {
      "id": 39,
      "center_name": "karimnagar",
      "clinic_location": "karimnagar",
      "city": "Karimnagar",
      "rating": 5,
      "name": "Akula Sandhyarani",
      "reviews": "Searching for the best fertility hospital near me led me to Dr. Jigna Tamagond, and it was the best decision. She was kind, professional, and extremely knowledgeable. The treatment was smooth, and I now feel confident about my journey.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLHPl6BT1EvaonPBmfn_oq04Sy8iH2l_s2mw3m1Lb7KpjfEzg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/dx41QVeLs4JJVWz39"
    },
    {
      "id": 40,
      "center_name": "karimnagar",
      "clinic_location": "karimnagar",
      "city": "Karimnagar",
      "rating": 5,
      "name": "Harish",
      "reviews": "I found Oasis fertility in karimnagar. then i met Dr. Jigna Tamagond—she explained everything clearly and ensured I was comfortable throughout. The experience was reassuring, and I highly recommend her!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVxY-cxqfttf7WPYFG_uJ8lu3TQbQB_-JSKsUndoyS1XJuT0c7QzA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/tMmQgvUidoeS592EA"
    },
    {
      "id": 41,
      "center_name": "vijayawada",
      "clinic_location": "vijayawada",
      "city": "Vijayawada",
      "rating": 4.9,
      "name": "Kotha Mrudula",
      "reviews": "Infertility was a difficult journey, and I wanted the best fertility centres in vijayawada. Meeting Dr. Venkata Sujatha Vellanki-changing. She patiently explained my options and provided the best treatment. I now feel hopeful and thankful for her support!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLS4kVGN-UiZSIqZuilE5y1fDAGhft6zZE3ljp97H-pCjHoIw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/RPhq128i2Q6VkjQM7"
    },
    {
      "id": 42,
      "center_name": "vijayawada",
      "clinic_location": "vijayawada",
      "city": "Vijayawada",
      "rating": 4.9,
      "name": "Dubba Sunil",
      "reviews": "I was searching for a trustworthy best fertility centres in vijayawada, and Dr. Venkata Sujatha Vellanki, kind approach, and well-structured treatment plan made my journey smooth. Highly recommend her to anyone facing fertility issues!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXK7SlU5nnePsEC1y0A3OVEOXdDU8tmkZgWZaTIckV_kuicKLW-aw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/MPVe5xJu78HGZy8k9"
    },
    {
      "id": 43,
      "center_name": "vijayawada",
      "clinic_location": "vijayawada",
      "city": "Vijayawada",
      "rating": 4.9,
      "name": "Siva Sai Kumar",
      "reviews": "Choosing the rightbest fertility centres in vijayawada was overwhelming. But Dr. Venkata Sujatha Vellanki’m truly grateful for her care!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWtp1oTxQQ8CEo7iHXuLWYftp7gaVcnadSE6ZJGm0_-lnd3oq8=w56-h56-p-rp-mo-br100",
      "review_link": "https://www.google.com/maps/contrib/118068252448421908233/reviews"
    },
    {
      "id": 44,
      "center_name": "vijayawada",
      "clinic_location": "vijayawada",
      "city": "Vijayawada",
      "rating": 4.9,
      "name": "Sandhya Dodla",
      "reviews": "Finding a best fertility centres in vijayawada was my biggest concern. Dr. Venkata Sujatha Vellanki, I now feel confident about my future!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIY9Q890869J-EYPfc6nECGVJYyM_vv3-5MbwVBQmhr3U-wSg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/GCs6j4WoX1aocB4B9"
    },
    {
      "id": 45,
      "center_name": "visakhapatnam",
      "clinic_location": "visakhapatnam",
      "city": "Visakhapatnam",
      "rating": 4.9,
      "name": "Gummala Darababu",
      "reviews": "The search for the best fertility hospital near me was exhausting, but meeting Dr. Radhika Potluri, explained all possibilities, and designed a treatment that worked for me. So grateful for her expertise!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIw-OEqRYyxaLo_9pYPfh8swi9WPIFIyhOZEEMHV8or7mQ5dw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/p6Bpv6NSXUbPn2NLA"
    },
    {
      "id": 46,
      "center_name": "visakhapatnam",
      "clinic_location": "visakhapatnam",
      "city": "Visakhapatnam",
      "rating": 4.9,
      "name": "Yarra Vandana",
      "reviews": "Struggling with infertility was emotionally draining, but finding the male fertility test in bangalore gave me hope. Dr. Radhika Potluri",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjW0JKaRLeyFha_xEjU0t_iMrAIbM7hjcsyTjGm05rIbuyAe8WEi=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/oH6ejG5h24DvrQjn7"
    },
    {
      "id": 47,
      "center_name": "visakhapatnam",
      "clinic_location": "visakhapatnam",
      "city": "Visakhapatnam",
      "rating": 4.9,
      "name": "Kamesh Royistan",
      "reviews": "Choosing the right fertility hospital near me was important to me. Dr. Radhika Potluri, knowledgeable, and supportive. Her guidance helped me stay confident throughout the treatment. I highly recommend her!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXVxWnMxcUPeERYbdEhnyB80CdoL5VWAPl6l4mUEWU2lNNpu5YlRw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/USfR1dzt28yvS8Ui6"
    },
    {
      "id": 48,
      "center_name": "visakhapatnam",
      "clinic_location": "visakhapatnam",
      "city": "Visakhapatnam",
      "rating": 4.9,
      "name": "Kasina Suguna",
      "reviews": "The search for a trusted fertility hospital near me then google led me to Dr. Radhika Potluri, compassionate, and offered the best treatment options. Thanks to her, I now feel optimistic about the future.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKVU_MH5HafV6WV_d8NSN3pq-84_n6rfEFvc1E8jOzn94F7GA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/yewzRut981Sx4pM29"
    },
    {
      "id": 49,
      "center_name": "guntur",
      "clinic_location": "guntur",
      "city": "Guntur",
      "rating": 5,
      "name": "Istikhar",
      "reviews": "Finding the best fertility hospital in gunturwas not easy, but meeting Dr. Ramya Vicharapu-planned, and I now feel hopeful. Highly recommended!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKCWeHIGgh6u9isiJ-NQnop8nEDZ-uATxwK2auiAavA-xAFeA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/dbt3NggMRuAmeU3E8"
    },
    {
      "id": 50,
      "center_name": "guntur",
      "clinic_location": "guntur",
      "city": "Guntur",
      "rating": 5,
      "name": "Nisha Shaikh",
      "reviews": "I was looking for a reliable best fertility hospital in guntur and came across Dr. Ramya Vicharapu, and I feel much more positive now.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJ2kEqiIdh8rbDHtQFVw1sXlFMS_OeQ3Z6_wGxrTK_ocqsjRw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/NPugY1sfeCPDAMyDA"
    },
    {
      "id": 51,
      "center_name": "guntur",
      "clinic_location": "guntur",
      "city": "Guntur",
      "rating": 5,
      "name": "Lovaraju Madda",
      "reviews": "Infertility was a difficult journey, but finding the best fertility hospital in guntur made all the difference. Dr. Ramya Vicharapu!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUZI3FpS9kIPN5mnf-cyTgE9GOLHptYPDOY5j1PTvMVg4eSlWA2=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/b7CoCo2DVwQmb7zg9"
    },
    {
      "id": 52,
      "center_name": "guntur",
      "clinic_location": "guntur",
      "city": "Guntur",
      "rating": 5,
      "name": "Gudimella Vasavi Sujatha",
      "reviews": "I was searching for an best fertility hospital in guntur, and I’m grateful I found Dr. Ramya Vicharapu!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIlB6BtSJ16RCzhV6MGbbrm1TrMBHTllesABNkkrIxxpQ_lKw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/JFfTsyGXy197u8Ha8"
    },
    {
      "id": 53,
      "center_name": "ongole",
      "clinic_location": "ongole",
      "city": "Ongole",
      "rating": 5,
      "name": "Sulthan Sk",
      "reviews": "Choosing the right best fertility hospital in ongole was overwhelming, but meeting Dr Deepika Boppana, and the treatment process was smooth. I highly recommend her to anyone facing fertility challenges!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLjZJura-jRNkBjDYtXp1YUE0vU01Hqjn9t7gDxhSxLfwJVig=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/5gxg9jhvZUVndE9u7"
    },
    {
      "id": 54,
      "center_name": "ongole",
      "clinic_location": "ongole",
      "city": "Ongole",
      "rating": 5,
      "name": "Vijaya Lakshmi",
      "reviews": "The search for the best fertility hospital in ongole was stressful, but Dr Deepika Boppana, knowledgeable, and ensured I was comfortable throughout. So grateful for her support!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKdz6BWe7V3GkKVStPW-d_McqgFYt4Fe2jtYYCgfM1Nc8yyoA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/ELBL5kCx343uagUi6"
    },
    {
      "id": 55,
      "center_name": "ongole",
      "clinic_location": "ongole",
      "city": "Ongole",
      "rating": 5,
      "name": "Urvashi",
      "reviews": "Finding a reliable best fertility hospital in ongole was my priority, and Dr Deepika Boppana!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLqy1Ifrbz-sMhVQ8jOV4kLzs1tNvsuny5lgHISMeAbIUXX-Q=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/9J6xMgepSdi2XnhLA"
    },
    {
      "id": 56,
      "center_name": "ongole",
      "clinic_location": "ongole",
      "city": "Ongole",
      "rating": 5,
      "name": "Dhana Lakshmi",
      "reviews": "Infertility was a challenging phase, but finding the best fertility hospital in ongole changed everything. Dr Deepika Boppana, professional, and made the entire process smooth. I now feel positive about my journey ahead!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJIMyV12fRC8r4XgsCh3cALjnSJhfHob20kfJyKcpUvkeKPWg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/j5YAuPGUroDXw1Mo6"
    },
    {
      "id": 57,
      "center_name": "tirupati",
      "clinic_location": "tirupati",
      "city": "Tirupati",
      "rating": 4.9,
      "name": "Usha Nallapareddy",
      "reviews": "I was searching for an expert fertility doctor near me, and i found Dr. Nadikattu Saranya Lakshmi, making me feel confident and hopeful. Grateful for her exceptional care!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJ-2YAQLOakjWHiTvytLyANuo1b41YunzzHTMrutSR1y3VpsA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/DSiWfWy5L3tmGMqq8"
    },
    {
      "id": 58,
      "center_name": "tirupati",
      "clinic_location": "tirupati",
      "city": "Tirupati",
      "rating": 4.9,
      "name": "Divya K",
      "reviews": "Choosing the right fertility treatments was crucial, and Dr. Pallavi Tapala!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIh0moEZM9Jfu-Z4pO03_ThQlFggGbXHvOcPLakeZC9tYHPXRKX=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/gRSzm4A9Rj2cezxN8"
    },
    {
      "id": 59,
      "center_name": "tirupati",
      "clinic_location": "tirupati",
      "city": "Tirupati",
      "rating": 4.9,
      "name": "Kiran Teja",
      "reviews": "The journey to find the best fertility treatment led me to Dr. Ramya Vicharapu’m grateful for her exceptional care and support!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVPlg-FteaQdQLj_woNS4OS9UmcwW0BH6Ig5oUkRKVf0mxRFrk=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/bzKkEFuiFREWCTdT7"
    },
    {
      "id": 60,
      "center_name": "tirupati",
      "clinic_location": "tirupati",
      "city": "Tirupati",
      "rating": 4.9,
      "name": "Sarah",
      "reviews": "Finding a trustworthy fertility treatments was difficult, but Dr. Vijayalakshmi D, and now I feel hopeful about the future. Highly recommended!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJAdbdA0Uy_bqDtq5ML-IhsWBaRNNWPXGaeh-_P5cOOprdX6w=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/caJh5ncRsAuu8iuZA"
    },
    {
      "id": 61,
      "center_name": "kurnool",
      "clinic_location": "kurnool",
      "city": "Kurnool",
      "rating": 5,
      "name": "Srikanth Sri",
      "reviews": "Facing infertility was overwhelming, but finding the best fertility centre in kurnool gave me hope. Dr. Vijayalakshmi D, and I now feel positive about my journey ahead!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJV0CbscHMoi8u1hCrFTgJe-jBE18h7cyY7tZAba3nO6IjjY96z=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/TUi1nzMLia3mfQhE7"
    },
    {
      "id": 62,
      "center_name": "kurnool",
      "clinic_location": "kurnool",
      "city": "Kurnool",
      "rating": 5,
      "name": "Madhusudan Naidu Pathipati",
      "reviews": "I was searching for an experienced fertility centre in kurnool, and Dr. Vijayalakshmi D, knowledgeable, and provided a well-planned treatment. The support I received was truly reassuring!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJJqeZyvFm1fC9s5Wy35_EqRjG5jAHujaRg7SDrqIg-u9dblw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/YSQ4a76euJ2Gsofz9"
    },
    {
      "id": 63,
      "center_name": "kurnool",
      "clinic_location": "kurnool",
      "city": "Kurnool",
      "rating": 5,
      "name": "Vasanth Appapogu",
      "reviews": "Choosing the right fertility centre in kurnool was stressful, but meeting Dr. Vijayalakshmi D, making the process easy to understand. I’m thankful for her expertise and support!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKqcRkT75CGLsu44io3o73xFfGLta_9biNXnBfuaOYo0LszSw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/dUE997hEDGkD257g8"
    },
    {
      "id": 64,
      "center_name": "kurnool",
      "clinic_location": "kurnool",
      "city": "Kurnool",
      "rating": 4.9,
      "name": "Gowthami Gowni",
      "reviews": "The journey to find the best fertility centre in kurnool was tough, but I’m glad I consulted Dr. Vijayalakshmi D, guided me well, and ensured I felt comfortable throughout the treatment.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWIfG_ONIOQqjrx7OExlhmR__iP_5KVoJ6Jw9tZC2dbJzJqMbCu=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/TbUNdQyBTN7nhkaJ8"
    },
    {
      "id": 65,
      "center_name": "Bengaluru",
      "clinic_location": "HSR",
      "city": "Bengaluru",
      "rating": 4.9,
      "name": "Haribabu Tata",
      "reviews": "Finding a reliable best fertility hospital in bangalore was my priority, and I’m grateful to have found Dr. Prinka Bajaj, making my treatment stress-free. Now, I feel hopeful and confident about the future!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJGNAbwp_l1bJcENwg1tG9Y5Nr4ZlHjFneKljumt5OLUJc2zwQ=w56-h56-p-rp-mo-ba3-br100",
      "review_link": "https://maps.app.goo.gl/kVN2F8wwg7fYwNfT9"
    },
    {
      "id": 66,
      "center_name": "Bengaluru",
      "clinic_location": "HSR",
      "city": "Bengaluru",
      "rating": 4.9,
      "name": "Sumon Laskar",
      "reviews": "Struggling with infertility was emotionally draining, but visiting the best IVF center in Hyderabad changed everything. Dr. Prinka Bajaj!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKbxVIncIvGGMCydXmsvR9VqGexuzyNOF1Y93CWTT8Fd2B3RA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/DPJ64qNRhFqKev47A"
    },
    {
      "id": 67,
      "center_name": "Bengaluru",
      "clinic_location": "banashankari",
      "city": "Bengaluru",
      "rating": 4.9,
      "name": "Navitham",
      "reviews": "I was searching for a trustwort best fertility hospital in bangalore, and I’m so glad I found Dr. Shalini M A!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUlN4o3xhycMK7e6eFmN5xobNFkvbzkMTttXJ8JZhIXa5DUcgw5lA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/iqaeLBBEv51Rkx7n8"
    },
    {
      "id": 68,
      "center_name": "Bengaluru",
      "clinic_location": "hebbal",
      "city": "Bengaluru",
      "rating": 4.9,
      "name": "Shireen Shariff",
      "reviews": "Choosing the right best fertility hospital in bangalore was overwhelming, but Dr. Shalini M A!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLllXJDL20xxHz7E6T4CDm2Qpt1HFt9_b8e87_z55bbvr1a0A=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/rtq7m8fHqJfLSKif7"
    },
    {
      "id": 69,
      "center_name": "HSR",
      "clinic_location": "HSR",
      "city": "Hsr",
      "rating": 4.9,
      "name": "Haribabu Tata",
      "reviews": "The search for the best fertility hospital in bangalore was exhausting, but meeting Dr. Rekha Viswanath, professional, and extremely knowledgeable. I now feel positive about my future!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJGNAbwp_l1bJcENwg1tG9Y5Nr4ZlHjFneKljumt5OLUJc2zwQ=w56-h56-p-rp-mo-ba3-br100",
      "review_link": "https://maps.app.goo.gl/kVN2F8wwg7fYwNfT9"
    },
    {
      "id": 70,
      "center_name": "HSR",
      "clinic_location": "HSR",
      "city": "Hsr",
      "rating": 4.9,
      "name": "Neha Vernekar",
      "reviews": "Finding a reliable best fertility hospital in bangalore was my priority. Dr. Shalini M A!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKvLgY_zs3qj6XLcl9D39IsKTCux5Cr7wEPyw8_1OTBs1fDrw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/7XysC3Z1eyLz4qvk7"
    },
    {
      "id": 71,
      "center_name": "HSR",
      "clinic_location": "HSR",
      "city": "Hsr",
      "rating": 4.9,
      "name": "Manikeshwari K",
      "reviews": "Infertility was a tough journey, but finding the best best fertility hospital in bangalore gave me new hope. Dr. Shweta .G. Sonwalkar, and I now feel optimistic about my future!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKLdL9IMtSrXEVOoE-h0Vwf9ghAlLbVbkdoF1nn8GV6koWaS5Jv=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/5fX9pg83f7pnbLV66"
    },
    {
      "id": 72,
      "center_name": "HSR",
      "clinic_location": "HSR",
      "city": "Hsr",
      "rating": 4.9,
      "name": "Sumon Laskar",
      "reviews": "I was looking for an experienced best fertility hospital in bangalore, and Dr. Shalini M A!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKbxVIncIvGGMCydXmsvR9VqGexuzyNOF1Y93CWTT8Fd2B3RA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/DPJ64qNRhFqKev47A"
    },
    {
      "id": 73,
      "center_name": "banashankari",
      "clinic_location": "banashankari",
      "city": "Banashankari",
      "rating": 5,
      "name": "Rs Gowda",
      "reviews": "Finding a trusted best fertility hospital in bangalore was stressful, but Dr. Prinka Bajaj!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWeCA_Yq1YVje93tm3C0gPCkQLNBzI7XSOh-0PwClZGNCDKvCv6=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/tb1WxbCLsZ7Ry1qH7"
    },
    {
      "id": 74,
      "center_name": "banashankari",
      "clinic_location": "banashankari",
      "city": "Banashankari",
      "rating": 5,
      "name": "Sadhana Naik",
      "reviews": "The journey to find the best fertility hospital in bangalore led me to Dr. Prinka Bajaj!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXLGXX-iwMC3GAmK59zMIMask5-no_AzPbK4l4lh7lfslBJWs61=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/iRX5vx4RQy2xc4Qr9"
    },
    {
      "id": 75,
      "center_name": "banashankari",
      "clinic_location": "banashankari",
      "city": "Banashankari",
      "rating": 5,
      "name": "Mohana Priya",
      "reviews": "Choosing the right best fertility hospital in bangalore was crucial, and I’m glad I found Dr. Prinka Bajaj, clear communication, and caring approach made the process stress-free. I highly recommend her!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJMWp-PjgnCuIPjbMcPPH-AT_S_dW_kXb3SKW3SVtvWkBR6eg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/3QhsmwetyKdRna8a6"
    },
    {
      "id": 76,
      "center_name": "banashankari",
      "clinic_location": "banashankari",
      "city": "Banashankari",
      "rating": 4.9,
      "name": "Sumon Laskar",
      "reviews": "Infertility can be a heartbreaking journey, but finding the best fertility hospital in bangalore changed everything for me. Dr. Prinka Bajaj, making sure I received the best treatment. I now have hope for the future!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKbxVIncIvGGMCydXmsvR9VqGexuzyNOF1Y93CWTT8Fd2B3RA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/DPJ64qNRhFqKev47A"
    },
    {
      "id": 77,
      "center_name": "hebbal",
      "clinic_location": "hebbal",
      "city": "Hebbal",
      "rating": 4.9,
      "name": "Sanjeeva Rayudu",
      "reviews": "I was searching for an experienced best fertility hospital in bangalore, and Dr. Shalini M A, making me feel comfortable throughout the process. So grateful for her support!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJuObpZTQRri922E7s74N32Y5rj4p-lhuLeKYgIV4c35jJLpg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/TJvLpiAsJuXGVmgD6"
    },
    {
      "id": 78,
      "center_name": "hebbal",
      "clinic_location": "hebbal",
      "city": "Hebbal",
      "rating": 4.9,
      "name": "Navitham",
      "reviews": "Finding a best fertility hospital in bangalore was challenging, but Dr. Shalini M A. Her knowledge and patient-centered approach reassured me, and I feel much more confident about my journey!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUlN4o3xhycMK7e6eFmN5xobNFkvbzkMTttXJ8JZhIXa5DUcgw5lA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/iqaeLBBEv51Rkx7n8"
    },
    {
      "id": 79,
      "center_name": "hebbal",
      "clinic_location": "hebbal",
      "city": "Hebbal",
      "rating": 4.9,
      "name": "Maheshwari Eswari Eswari",
      "reviews": "The search for the best fertility hospital in bangalore led me to Dr. Shalini M A!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLlmJMaEy9zvaY_KbuNuSfZ8DMJ3JutTDLf-OoGC2TWuG-YIg=w56-h56-p-rp-mo-ba3-br100",
      "review_link": "https://maps.app.goo.gl/EvypeEDc6piPsXvm7"
    },
    {
      "id": 80,
      "center_name": "hebbal",
      "clinic_location": "hebbal",
      "city": "Hebbal",
      "rating": 4.9,
      "name": "Shireen Shariff",
      "reviews": "Choosing the right best fertility hospital in bangalore was my priority, and I’m thankful I found Dr. Shalini M A, caring, and made sure I was comfortable at every step. Highly recommended!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLllXJDL20xxHz7E6T4CDm2Qpt1HFt9_b8e87_z55bbvr1a0A=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/rtq7m8fHqJfLSKif7"
    },
    {
      "id": 81,
      "center_name": "hebbal",
      "clinic_location": "hebbal",
      "city": "Hebbal",
      "rating": 4.9,
      "name": "Navitham",
      "reviews": "Facing infertility was overwhelming, but visiting the best best fertility hospital in bangalore gave me hope. Dr. Shalini M A!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUlN4o3xhycMK7e6eFmN5xobNFkvbzkMTttXJ8JZhIXa5DUcgw5lA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/wp3tDC7gv8cTLFT78"
    },
    {
      "id": 82,
      "center_name": "belagavi",
      "clinic_location": "belagavi",
      "city": "Belagavi",
      "rating": 5,
      "name": "Sudha Patil",
      "reviews": "I was looking for a reliable infertility doctor near me, and then i met Dr. Shweta .G. Sonwalkar, provided a structured treatment plan, and ensured I felt comfortable throughout the process. Truly grateful for her care!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocI1TuDkNb8oFapWusEkLel-5hC9n2XGu9__loaZ3keH8eme9w=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/2P4vyoUXe36x13Th9"
    },
    {
      "id": 83,
      "center_name": "belagavi",
      "clinic_location": "belagavi",
      "city": "Belagavi",
      "rating": 5,
      "name": "Adam",
      "reviews": "Choosing the right fertility centre near me wa so stressful, but then i found Dr. Shweta .G. Sonwalkar, and I highly recommend her!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXoGIPncmjzMXAU2hregFSYNbdMQlcXOlOrAf4ETyfeWmAc3m-L=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/LwBDgVkyo5UWqRWu8"
    },
    {
      "id": 84,
      "center_name": "belagavi",
      "clinic_location": "belagavi",
      "city": "Belagavi",
      "rating": 5,
      "name": "Irfan Khan",
      "reviews": "Searching for the best infertility doctor near me was exhausting until I met Dr. Shweta .G. Sonwalkar!",
      "profile_picture": null,
      "review_link": "https://maps.app.goo.gl/LwBDgVkyo5UWqRWu8"
    },
    {
      "id": 85,
      "center_name": "belagavi",
      "clinic_location": "belagavi",
      "city": "Belagavi",
      "rating": 4.9,
      "name": "Sharada Shiledar",
      "reviews": "Finding a trusted infertility doctor near me was my priority, and then i found Dr. Shweta .G. Sonwalkar!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJVFU-oPlfCdh0sIYzesdWv7hoydWH6FNOp9tURs3AUByoC=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/j2QFgGtV4pyakmXa9"
    },
    {
      "id": 86,
      "center_name": "belagavi",
      "clinic_location": "belagavi",
      "city": "Belagavi",
      "rating": 5,
      "name": "Sharada Shiledar",
      "reviews": "Struggling with infertility was emotionally draining, but finding the best fertility centre near me changed everything. Dr. Shweta .G. Sonwalkar, kind, and highly knowledgeable. Her guidance made the process smooth and reassuring!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJVFU-oPlfCdh0sIYzesdWv7hoydWH6FNOp9tURs3AUByoC=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/JpQ7TYu5xBrm2apC9"
    },
    {
      "id": 87,
      "center_name": "chennai",
      "clinic_location": "chennai",
      "city": "Chennai",
      "rating": 4.9,
      "name": "Karthikaarjun A",
      "reviews": "I was searching for a skilled fertility centre, and i found right one specially Dr. Hema!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLvS2E-jTV6hPrw3yGd4ZqvNbbs2M-up7crvEW0kqhswBbE5w=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/NDCLK7VYLcgZVBnA8"
    },
    {
      "id": 88,
      "center_name": "chennai",
      "clinic_location": "chennai",
      "city": "Chennai",
      "rating": 4.9,
      "name": "Sathiya Sathiya",
      "reviews": "Finding a trustworthy fertility centre was overwhelming, but Dr. Hema, answered all my concerns, and gave me confidence in the process. Highly recommend her!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJo2e2MAmX1H1FJQABYQZ1i-b6FRw_EKJaAvoACCmyWWcV4zw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/b1CGoUBEr8zYh8n48"
    },
    {
      "id": 89,
      "center_name": "chennai",
      "clinic_location": "chennai",
      "city": "Chennai",
      "rating": 4.9,
      "name": "Prabakaran Subu",
      "reviews": "The search for the best fertility centre was tough, but meeting Dr. Maheswari D, caring, and provided the best possible solution. Now, I feel hopeful about my journey!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXEPSsP0Q0XC6oMGLvN8hCvE0nDycn7zUjtHEkf4pdeaDVhmNCAww=w56-h56-p-rp-mo-ba3-br100",
      "review_link": "https://maps.app.goo.gl/h1ZmAxvok1WrEVkVA"
    },
    {
      "id": 90,
      "center_name": "chennai",
      "clinic_location": "chennai",
      "city": "Chennai",
      "rating": 4.9,
      "name": "Anagha C H",
      "reviews": "Choosing a reliable fertility centre was important to me, and I’m glad I found Dr. Maheswari D!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVqDxvnlhhmAPnmg-9RQxhL81lvpv7Kpc7PLz94ieMK-XHOtVU=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/irFpmGjYgJMW2shk9"
    },
    {
      "id": 91,
      "center_name": "chennai",
      "clinic_location": "chennai",
      "city": "Chennai",
      "rating": 4.9,
      "name": "Ramya Hema",
      "reviews": "Dealing with infertility was emotionally exhausting, but finding the best fertility center gave me hope. Dr. Maheswari D!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLc9tciEnzPQYNW8S6PE0cZknC0VOkdU8fni7ObnZUhaFNfPQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/kdbseUNiA6L4CWd19"
    },
    {
      "id": 92,
      "center_name": "Pune",
      "clinic_location": "Pune",
      "city": "Pune",
      "rating": 4.9,
      "name": "Chaya Wakode",
      "reviews": "I was searching for an experienced infertility doctors in pune, and Dr. Nilesh Unmesh Balkawade!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKVJtamRUa1agKMUWeb6wdczv9mZb5AbaU39OWhvXcwwHgv-A=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/CmUcWzptkmPnuud18"
    },
    {
      "id": 93,
      "center_name": "Pune",
      "clinic_location": "Pune",
      "city": "Pune",
      "rating": 4.9,
      "name": "Madhushri Marathe",
      "reviews": "Finding a trusted IVF infertility doctors in pune was difficult, but Dr. Sneha Govind Balki, kind, and explained everything in detail. I truly appreciate her guidance!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIhSb6z3B0AGx7aX4bm_mOOxCehqBAZr8kjM69RLu89oo1tcw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/zDwf7DRiyxoeSTJEA"
    },
    {
      "id": 94,
      "center_name": "Pune",
      "clinic_location": "Pune",
      "city": "Pune",
      "rating": 4.7,
      "name": "Nandini Idohole",
      "reviews": "The journey to find the best infertility doctors in pune led me to Dr. Nilesh Unmesh Balkawade’m extremely grateful for her support!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKHPCqfIBD5pMFJ323h5h9zeeQKyHDb554QGVW1v4HD32MJSA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/8eoVDFctXWJFTsif9"
    },
    {
      "id": 95,
      "center_name": "Pune",
      "clinic_location": "Pune",
      "city": "Pune",
      "rating": 4.7,
      "name": "Pratik Kedari",
      "reviews": "Choosing the right infertility doctors in pune was important, and I’m so glad I found Dr. Sneha Govind Balki, kind, and made the process stress-free. Highly recommended!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUwHJlwOH2qkb29xIs9c2ZrB2wljts1-rQvu9M0kqktprMgy65sbQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/8W8vgFELigaRDXB36"
    },
    {
      "id": 96,
      "center_name": "Pune",
      "clinic_location": "Pune",
      "city": "Pune",
      "rating": 4.9,
      "name": "Rajendra Mothe",
      "reviews": "Infertility was a tough phase, but finding the best infertility doctors in pune gave me hope. Dr. Nilesh Unmesh Balkawade, professional, and made sure I received the best treatment. I now feel optimistic about my journey!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWMEgexjQ1nlN0b41jXtSpkfz-QhplE6yNT7VJpMO4sYBuyNPHddQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/voRZhsvRfhm6wi75A"
    },
    {
      "id": 97,
      "center_name": "wakad",
      "clinic_location": "wakad",
      "city": "Wakad",
      "rating": 4.9,
      "name": "Hakam Joping",
      "reviews": "I needed an experienced infertility doctors in pune, and Dr. Nilesh Unmesh Balkawade, making me feel confident and comfortable throughout the process. So grateful for her care!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXRjLT-R6qCFuGyPMOZcCQ7kxQvhxvnGkJGmrFuyhSJ1i_r0j17=w56-h56-p-rp-mo-ba3-br100",
      "review_link": "https://maps.app.goo.gl/aFrJaB6xbMGcAXGP7"
    },
    {
      "id": 98,
      "center_name": "wakad",
      "clinic_location": "wakad",
      "city": "Wakad",
      "rating": 4.9,
      "name": "Chaya Wakode",
      "reviews": "Choosing a reliable infertility doctors in pune was overwhelming, but Dr. Nilesh Unmesh Balkawade-informed and at ease throughout my treatment. Highly recommended!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKVJtamRUa1agKMUWeb6wdczv9mZb5AbaU39OWhvXcwwHgv-A=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/CmUcWzptkmPnuud18"
    },
    {
      "id": 99,
      "center_name": "wakad",
      "clinic_location": "wakad",
      "city": "Wakad",
      "rating": 4.9,
      "name": "Prashant Ranpise",
      "reviews": "The search for the best infertility doctors in pune was exhausting until I met Dr. Nilesh Unmesh Balkawade, understood my concerns, and provided the best treatment plan. I truly appreciate her expertise!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLN65_iIhU58mC4IiavMhi1yjAP9JawZWNYW7BX5Xw6cqzIbQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/ABvEL4Vx7Mdv8AQz8"
    },
    {
      "id": 100,
      "center_name": "wakad",
      "clinic_location": "wakad",
      "city": "Wakad",
      "rating": 4.9,
      "name": "Bandu Jadhav",
      "reviews": "Finding a skilled infertility doctors in pune was important, and I’m glad I found Dr. Nilesh Unmesh Balkawade with her expertise and caring approach. Truly grateful!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLs8xDDb12GsezxYTTeR_6zMb1R6GhZ_HfwVOhlGRgrsmEWdis=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/28Go4X42nUWZFsHN7"
    },
    {
      "id": 101,
      "center_name": "wakad",
      "clinic_location": "wakad",
      "city": "Wakad",
      "rating": 4.9,
      "name": "Vikas Lande",
      "reviews": "Infertility was a stressful journey, but finding the best infertility doctors in pune gave me confidence. Dr. Nilesh Unmesh Balkawade, ensuring I understood every step. Her expertise and care made all the difference!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKS2ViCy5luxjh7hVQkFGgJ_XvhIATTImbRmN3eA6EglkBCIA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/6DNnRhxJ5Xy8uDmd6"
    },
    {
      "id": 102,
      "center_name": "kharadi",
      "clinic_location": "kharadi",
      "city": "Kharadi",
      "rating": 4.7,
      "name": "Nandini Idohole",
      "reviews": "I was searching for a compassionate infertility doctors in pune, and i found Dr. Sneha Govind Balki is specialized in this field !",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKHPCqfIBD5pMFJ323h5h9zeeQKyHDb554QGVW1v4HD32MJSA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/8eoVDFctXWJFTsif9"
    },
    {
      "id": 103,
      "center_name": "kharadi",
      "clinic_location": "kharadi",
      "city": "Kharadi",
      "rating": 5,
      "name": "Govind Bhambre",
      "reviews": "Finding a trusted infertility doctors in pune felt overwhelming, but Dr. Sneha Govind Balki, provided a clear treatment plan, and gave me hope. Highly recommended!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVmC9X6B1_EZOcn3N3TQcYc58_T-ewRGf5wQRyswFkZWXGV4ngW=w56-h56-p-rp-mo-ba3-br100",
      "review_link": "https://maps.app.goo.gl/8SPGYmRzEMwRoQuX6"
    },
    {
      "id": 104,
      "center_name": "kharadi",
      "clinic_location": "kharadi",
      "city": "Kharadi",
      "rating": 4.7,
      "name": "Pitta Kishore",
      "reviews": "The search for the infertility doctors in pune was exhausting, but Dr. Sneha Govind Balki, patience, and care made my journey much smoother!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIXC9Px-Oj7wwJavLnULLhvpeT9CWXwjDgS6epPKsO0Z_FS8w=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/X6LhCAJ6je5tMdY59"
    },
    {
      "id": 105,
      "center_name": "kharadi",
      "clinic_location": "kharadi",
      "city": "Kharadi",
      "rating": 4.7,
      "name": "Nadia Shaikh",
      "reviews": "Choosing the right infertility doctors in pune was crucial, and I’m so glad I found Dr. Sneha Govind Balki, kind, and made the process stress-free. Her support meant the world to me!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLkUaxmLiYqeDs8gbqRL8Oei2eTGXv5gJ4EgJe7FHnumUH6OYQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/VmJGRjP3hsAggU16A"
    },
    {
      "id": 106,
      "center_name": "kharadi",
      "clinic_location": "kharadi",
      "city": "Kharadi",
      "rating": 4.7,
      "name": "Poornima Bagul",
      "reviews": "Dealing with infertility was emotionally challenging, but after visiting the best infertility doctors in pune changed everything. specially Dr. Sneha Govind Balki!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVsKQM0UExDdTG1PCW0WgcWBtawSQaeyNZX9jlkcIv0x6yKu3g=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/YHLn7n4omWaFoBMU9"
    },
    {
      "id": 107,
      "center_name": "nashik",
      "clinic_location": "nashik",
      "city": "Nashik",
      "rating": 5,
      "name": "Vaishali Dumbare",
      "reviews": "I was looking for best fertility clinic near me, and then i found Dr. Pallavi Yuvraj Untwal just go for it with out thinking twice!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocId70JrDMx2FBCnvRSbVZIR2xkp72hMRQIx9B_MiOa6CiZBfA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/4kpTffhGZdcuvfzGA"
    },
    {
      "id": 108,
      "center_name": "nashik",
      "clinic_location": "nashik",
      "city": "Nashik",
      "rating": 5,
      "name": "Usha Patil",
      "reviews": "Finding a best fertility clinic near me was difficult, but Dr. Pallavi Yuvraj Untwal’m truly grateful for her support!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKd6EMo8mfe_nwnc21KCZEyjyUTAEJkj7uzQmqzHdBUJ3kqGw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/BQpA7ZhxLHFivaTw8"
    },
    {
      "id": 109,
      "center_name": "nashik",
      "clinic_location": "nashik",
      "city": "Nashik",
      "rating": 5,
      "name": "Kavitaa Tailor",
      "reviews": "The search for the best fertility clinic near me led me to Dr. Pallavi Yuvraj Untwal, created a personalized treatment plan, and gave me confidence. I highly recommend her!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLB4g4D5uVY1V0iEdLRtKyM-3LhfjB8MRHCN463oSxT6z8LLQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/8R4BQPLgqgPAP1736"
    },
    {
      "id": 110,
      "center_name": "nashik",
      "clinic_location": "nashik",
      "city": "Nashik",
      "rating": 5,
      "name": "Ganesh Karwal",
      "reviews": "I was searching best fertility clinic near me then i got to know I’m so glad I found Dr. Pallavi Yuvraj Untwal, patient, and made the process stress-free. Her care and expertise truly made a difference!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJ68lcyDouptfG9QliSEPkNQcnaqSgtl22AKCSxqOGTV_fWpQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/qCRMabjGYj8BCPt59"
    },
    {
      "id": 111,
      "center_name": "nashik",
      "clinic_location": "nashik",
      "city": "Nashik",
      "rating": 5,
      "name": "Mahesh Belekar",
      "reviews": "Infertility was a difficult phase, but finding the best fertility clinic near me gave me new hope. Dr. Pallavi Yuvraj Untwal!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJGybbY0m6SV_1ztoFm6JrwRtxrI518iZGVVxqQmeE8X0xz=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/nRSAEvdAn47dfL828"
    },
    {
      "id": 112,
      "center_name": "raipur",
      "clinic_location": "raipur",
      "city": "Raipur",
      "rating": 5,
      "name": "Bharat Pahuja",
      "reviews": "I was searching for a best infertility doctor in raipur , and then i got to know about Dr. Pratibha Tiwary satisfied!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJcQsAWo41KeW8Uq7SI18ytKZNgvGF6bua3uiqzVq2d-nrprg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/Ap4DHNNqNFF3de9p8"
    },
    {
      "id": 113,
      "center_name": "raipur",
      "clinic_location": "raipur",
      "city": "Raipur",
      "rating": 5,
      "name": "Tanushree Barua",
      "reviews": "Choosing a best infertility doctor in raipur was overwhelming, but Dr. Pratibha Tiwary what a incredible and knowlegable person she is !",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUtTTGVmqP73WWZ5MI01q8SV7jYGyGBlnn-ANITA5kFj7olbFbe=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/3APNiiqWCYJCQi579"
    },
    {
      "id": 114,
      "center_name": "raipur",
      "clinic_location": "raipur",
      "city": "Raipur",
      "rating": 5,
      "name": "Komal Dewangan",
      "reviews": "The journey to find the best infertility doctor in raipur was exhausting, but meeting Dr. Pratibha Tiwary, kind, and ensured I was on the right path. I feel much more hopeful now!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXh2W7mJ0GXx9C6OcuCCZM5rVVOowYiZbJ5bH4BHkMQm0odSxtrDA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/5g7weWndF8spoivY9"
    },
    {
      "id": 115,
      "center_name": "raipur",
      "clinic_location": "raipur",
      "city": "Raipur",
      "rating": 5,
      "name": "Kumar Gaurav",
      "reviews": "Finding a best skilled infertility doctor in raipur was crucial, and I’m so glad I chose Dr. Pratibha Tiwary, support, and clear communication made the entire process smooth and stress-free!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWnkuovrXnz1mjY51aCuYlk9bY9m-ikCtwQVDkQIm5hbwmeRya7=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/d9ZW1eKKzSV9BxaY6"
    },
    {
      "id": 116,
      "center_name": "raipur",
      "clinic_location": "raipur",
      "city": "Raipur",
      "rating": 5,
      "name": "Deepali",
      "reviews": "Struggling with infertility was tough, but finding the best infertility doctor in raipur changed my outlook. Dr. Pratibha Tiwary, patient, and provided the right treatment plan. Her support gave me the confidence to move forward!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJNdu8TzMyiCufxfy050DJ4Ahbj5ZFbwQnKiLELXgCFMg2Xlw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/WjhFNwQUAyF96tFs5"
    },
    {
      "id": 117,
      "center_name": "vadodara",
      "clinic_location": "vadodara",
      "city": "Vadodara",
      "rating": 4.9,
      "name": "Suresh Rathod",
      "reviews": "I was looking for a trusted fertility clinic, and Dr. Baxi Sushma, making the entire process less stressful. I truly appreciate her guidance!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIIAsTF_7X4PRqAp7QGO2k--v3InJzvgxvFaSfjJxHya7VImA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/WFzNBZkSXGWHvo4T9"
    },
    {
      "id": 118,
      "center_name": "vadodara",
      "clinic_location": "vadodara",
      "city": "Vadodara",
      "rating": 4.9,
      "name": "Neetu Vardhan",
      "reviews": "Finding a good fertility clinic was challenging, but Dr. Baxi Sushma!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXlrPuozneVBtTmL_K0Ahehxn196w8KCLREkH6mAWiXWqztIKo=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/2t7c8fhss29oT7BNA"
    },
    {
      "id": 119,
      "center_name": "vadodara",
      "clinic_location": "vadodara",
      "city": "Vadodara",
      "rating": 4.9,
      "name": "Aneeta Patel",
      "reviews": "The search for the best infertility clinic led me to Dr. Baxi Sushma, listened to all my concerns, and made me feel comfortable throughout. I highly recommend her!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWyTc0wnx3xYEQJf0sO9XHuZeV_aU0DmSnJqnX0lyq1XXW_7GY=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/93js5Buyji79GZ3J6"
    },
    {
      "id": 120,
      "center_name": "vadodara",
      "clinic_location": "vadodara",
      "city": "Vadodara",
      "rating": 4.9,
      "name": "Santosh Luste",
      "reviews": "Choosing a skilled fertility clinic was important, and I’m glad I found Dr. Baxi Sushma, knowledgeable, and made sure I felt confident in the process. Her support meant a lot!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJBhEoHMcqaSzUpYCnWjSMsGy3G6HnQIvL3JSdyiRQ6FkNxwQ=w56-h56-p-rp-mo-ba3-br100",
      "review_link": "https://maps.app.goo.gl/jekG5b9XYda1eKJ16"
    },
    {
      "id": 121,
      "center_name": "vadodara",
      "clinic_location": "vadodara",
      "city": "Vadodara",
      "rating": 4.9,
      "name": "Suresh Rathod",
      "reviews": "Infertility was emotionally draining, but visiting the best IVF fertility clinic gave me hope. specially Dr. Baxi Sushma!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIIAsTF_7X4PRqAp7QGO2k--v3InJzvgxvFaSfjJxHya7VImA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/aycBs9hiZbk76zjp9"
    },
    {
      "id": 122,
      "center_name": "ranchi",
      "clinic_location": "ranchi",
      "city": "Ranchi",
      "rating": 4.9,
      "name": "Rahul Singh",
      "reviews": "I needed a best reliable fertility doctor in ranchi , and Dr. Musunuru Rajani, provided a great treatment plan, and made me feel comfortable throughout the process. Grateful for her support!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLHQ4AeF9R3sXJ6knv6QVhYF8IXVCm40yodoycGfpWVT_4ZEw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/11PRU8AFdhdqiVMa9"
    },
    {
      "id": 123,
      "center_name": "ranchi",
      "clinic_location": "ranchi",
      "city": "Ranchi",
      "rating": 4.9,
      "name": "Ashish Sharma",
      "reviews": "Finding a trusted fertility hospital in ranchi was challenging, but Dr. Musunuru Rajani, professional, and helped me every step of the way. I now feel more confident about my journey!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjV392MCna1evNE97BAL2Arm19DZyBqWv-YcBrWHwY-ruNGt5hjGww=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/pPdVbPXQHjQikzAc7"
    },
    {
      "id": 124,
      "center_name": "ranchi",
      "clinic_location": "ranchi",
      "city": "Ranchi",
      "rating": 4.9,
      "name": "Shiva Yadav",
      "reviews": "The search for the best infertility treatment doctor in ranchi was overwhelming, but meeting Dr. Musunuru Rajani, understanding, and provided the best solutions. I truly appreciate her guidance!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLTL_laLgwHEnsxuK2ogZeW3rSRivwey2_GcSc1nA8xipJAHQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/YvhAPRFnXAnmZTxG7"
    },
    {
      "id": 125,
      "center_name": "ranchi",
      "clinic_location": "ranchi",
      "city": "Ranchi",
      "rating": 4.9,
      "name": "Rohini",
      "reviews": "Choosing a compassionate best fertility doctor in ranchi was important to me, and I’m so thankful I found Dr. Musunuru Rajani-free. Highly recommend her!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVSIR3Vk2EgPPIPtzUdJUT9zuJuPW8YOGc1K2myh9un8p6CR49I=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/25YW4TKyZYhdEv8b9"
    },
    {
      "id": 126,
      "center_name": "ranchi",
      "clinic_location": "ranchi",
      "city": "Ranchi",
      "rating": 4.9,
      "name": "Rahul Singh",
      "reviews": "Struggling with infertility was difficult, but finding the best IVF center in ranchi gave me hope. Dr. Musunuru Rajani, knowledgeable, and ensured I received the best treatment. So grateful for her care!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLHQ4AeF9R3sXJ6knv6QVhYF8IXVCm40yodoycGfpWVT_4ZEw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/whdkLHy86bK6XrHV9"
    },
    {
      "id": 127,
      "null": null,
      "review_link": "https://maps.app.goo.gl/Z2iVz6dH84txkRag7",
      "center_name": "india",
      "clinic_location": "Hyderabad",
      "rating": 5,
      "reviews": "\"I recently visited Oasis for my prenatal care, and I must say, I was thoroughly impressed. Dr. MeeraJindal and Tejashree was extremely knowledgeable, kind, and took the time to answer all my questions.",
      "name": "Sai Singh",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWjG9wHNIcDGy4OTnfpUpwQWolqPfV3q2B4LCY8NsAJGa91ZUjXcQ=w60-h60-p-rp-mo-br100"
    },
    {
      "id": 128,
      "null": null,
      "review_link": "https://maps.app.goo.gl/5fX9pg83f7pnbLV66",
      "center_name": "india",
      "clinic_location": "Bengaluru",
      "rating": 4.9,
      "reviews": "Thanks to oasis for all the support. We have gone through a lot before coming here. Since when we started taking treatment from oasis hospital really given me a positive vibe.We are really happy to share this review.",
      "name": "Manikeshwari K",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKLdL9IMtSrXEVOoE-h0Vwf9ghAlLbVbkdoF1nn8GV6koWaS5Jv=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 129,
      "null": null,
      "review_link": "https://maps.app.goo.gl/VmJGRjP3hsAggU16A",
      "center_name": "india",
      "clinic_location": "Pune",
      "rating": 4.9,
      "reviews": "Excellent facilities and compassionate care at OASIS Hospital, making a significant difference in our journey to parenthood. THANKS TO COMPLETE OASIS TEAM.",
      "name": "Rajendra Mothe",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWMEgexjQ1nlN0b41jXtSpkfz-QhplE6yNT7VJpMO4sYBuyNPHddQ=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 130,
      "null": null,
      "review_link": "https://maps.app.goo.gl/NDCLK7VYLcgZVBnA8",
      "center_name": "india",
      "clinic_location": "chennai",
      "rating": 4.9,
      "reviews": "Thanks for Nova IVF and thank you so much for dr.ajantha mam .she is very friendly and ans all enquiries.she give good confident for pts .all staff are pt guidance well.",
      "name": "Sathiya Sathiya",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJo2e2MAmX1H1FJQABYQZ1i-b6FRw_EKJaAvoACCmyWWcV4zw=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 131,
      "null": null,
      "review_link": "https://maps.app.goo.gl/WFzNBZkSXGWHvo4T9",
      "center_name": "india",
      "clinic_location": "Vadodara",
      "rating": 5,
      "reviews": "We want to Jalgaon manmad but we didn't find what we came for but in nashik oasis fertility dr pallavi dr Meenakshi centre manager pre full staff support guide a lot are hopes and dreams came true all credit to dr pallavi highly recommend",
      "name": "Usha Patil",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKd6EMo8mfe_nwnc21KCZEyjyUTAEJkj7uzQmqzHdBUJ3kqGw=w56-h56-p-rp-mo-br100"
    },
  ]

  export default fertilityReview;