const iuiReview = [
    {
      "id": 1,
      "center_name": "hyderabad",
      "clinic_location": "banjara hills",
      "city": "Hyderabad",
      "rating": 4.9,
      "name": "Renuka",
      "reviews": "We had lost confidence after multiple failed attempts. Dr. Durga G. Rao's methodical approach to IUI treatment gave us newfound optimism. The care and attention were outstanding, making this journey much smoother.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXKUFBmfsV0gy5GjWQIRbizGSvVqX9KLPoI-Sp8cgi1M-hMSqZK=w56-h56-p-rp-mo-br100",
      "review_link": "maps.app.goo.gl/FiYnims6MH4tzcTY8"
    },
    {
      "id": 2,
      "center_name": "hyderabad",
      "clinic_location": "gachibowli",
      "city": "Hyderabad",
      "rating": 4.9,
      "name": "Navaneeth Rao",
      "reviews": "We felt hopeless after trying for years. A friend recommended IUI treatment, and we found an expert who truly understood our pain. The approach was scientific yet compassionate, giving us a fresh start.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKTpj2xInuEhuIBMrsrTvhQl5zOMoPsdj4vFgl-ECbUlzqHBw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/KkY24v8QbYyt4VnZA"
    },
    {
      "id": 3,
      "center_name": "hyderabad",
      "clinic_location": "dilshuknagar",
      "city": "Hyderabad",
      "rating": 4.9,
      "name": "Bhagya Sri",
      "reviews": "The fear of another failure held us back. But with the right IUI specialist, we felt supported throughout the process. Everything was well-explained, making the journey easier to handle.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXxcZmAmCFy_irK8Z1G0-QesngWzOJ33cVvJT6EVsVQ6-nVSXMfwA=w45-h45-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/n8KpemCkvFN7Y9k3A"
    },
    {
      "id": 4,
      "center_name": "hyderabad",
      "clinic_location": "miyapur",
      "city": "Hyderabad",
      "rating": 4.9,
      "name": "Medak Rakhi",
      "reviews": "Infertility challenges were heartbreaking, but the right IUI treatment changed everything. The doctor's patience, skill, and kindness made this a much more comfortable process.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVV6V5enWzRgdT42hx5f3KnIzzi148ovO1Z-HYC4ceTmcPIO2m5=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/FSjVCbewBBfNc3zf8"
    },
    {
      "id": 5,
      "center_name": "banjara hills",
      "clinic_location": "banjara hills",
      "city": "Banjara Hills",
      "rating": 4.9,
      "name": "Nandini Gubba",
      "reviews": "The emotional ups and downs of infertility were hard to bear. Finding an experienced IUI specialist made all the difference. The care, guidance, and clear explanations reassured us completely.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJMuILKHklgB4gAnuofZ3OFrlF5r6F62uoxVfw2kQ6gOhbHBQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/tv5K6FriEap2rhTm9"
    },
    {
      "id": 6,
      "center_name": "banjara hills",
      "clinic_location": "banjara hills",
      "city": "Banjara Hills",
      "rating": 4.9,
      "name": "Someswara Rao Teppala",
      "reviews": "Feeling uncertain about IUI, we sought expert advice. The specialist explained every step with clarity, making us feel hopeful again. The care we received was beyond expectations.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUJmn2AuP2RSwVcihiMoFp_9WWguCP8ohhesBFo8Lz6Z9_bOubg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/YPhvr9tDQt1r3QHY6"
    },
    {
      "id": 7,
      "center_name": "banjara hills",
      "clinic_location": "banjara hills",
      "city": "Banjara Hills",
      "rating": 4.9,
      "name": "Upender Gali",
      "reviews": "Trying to conceive for years was emotionally exhausting. With the right guidance from an experienced IUI specialist, we finally saw hope. The procedure was seamless, and the doctor was extremely supportive.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWO_ovn6diLSrr6x5dBxi2C0fQOPIb_YbUt_5346gm7mlcnGqZl=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/db2WbMTNoZPqfFwr6"
    },
    {
      "id": 8,
      "center_name": "banjara hills",
      "clinic_location": "banjara hills",
      "city": "Banjara Hills",
      "rating": 4.9,
      "name": "Umeera Khan",
      "reviews": "IUI treatment felt like a last resort, but after the consultation, we realized it was the right choice. The process was handled professionally, with great attention to detail.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJw9BIkRtWFE1BgAZ3cpMMABe2DE3xKeuyiPaURgKPjAxJNSg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/qTw1hgdX28eoXHUV8"
    },
    {
      "id": 9,
      "center_name": "gachibowli",
      "clinic_location": "gachibowli",
      "city": "Gachibowli",
      "rating": 4.9,
      "name": "Aaliya Sheikh",
      "reviews": "The emotional toll of infertility was heavy. Dr. Avanthi Vellala made us feel seen and understood. Her approach to IUI treatment was both scientific and compassionate, creating a truly positive experience.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVaryLP-qAbGfBXYjLtdaQi58njQC1hz2T-zOdhn2tyV9pptEe2Tw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/Fqz3rDx5KXfc9JwQ9"
    },
    {
      "id": 10,
      "center_name": "gachibowli",
      "clinic_location": "gachibowli",
      "city": "Gachibowli",
      "rating": 4.9,
      "name": "Lekhan Naga",
      "reviews": "The road to parenthood was difficult. The specialist’s warm approach and deep knowledge of IUI treatment made a huge difference. We felt genuinely cared for.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocI5mA_d95nPa0fHlv9ncDPrqwECj6JM2LGpP8wrGZ7B46HdXA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/G6QhNE1UQXxgcB3U6"
    },
    {
      "id": 11,
      "center_name": "gachibowli",
      "clinic_location": "gachibowli",
      "city": "Gachibowli",
      "rating": 4.9,
      "name": "Kaniki Shekar",
      "reviews": "When natural conception didn’t work, IUI seemed like the next step. The doctor’s approach was detailed, reassuring, and well-planned. We couldn’t have asked for better guidance.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLipXYIcAPExyu_HZLcNechNkVeyScHkmBmOeiAm_22ckyP=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/bvEnx187Q2SrYtKQ6"
    },
    {
      "id": 12,
      "center_name": "gachibowli",
      "clinic_location": "gachibowli",
      "city": "Gachibowli",
      "rating": 4.9,
      "name": "Lakshmi Sarada",
      "reviews": "We struggled with fertility treatments before, but this IUI experience was different. The specialist’s dedication and step-by-step guidance gave us confidence and peace of mind.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJdA5mFa1KosgA1bVPQqhMPUKmCwtPMxHRivQiwfUSABq-FTA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/kSfUiEEEjcFmBFUV6"
    },
    {
      "id": 13,
      "center_name": "dilshuknagar",
      "clinic_location": "dilshuknagar",
      "city": "Dilshuknagar",
      "rating": 4.9,
      "name": "Rajitha",
      "reviews": "After years of disappointment, we met Dr. A Tejashree. She offered hope through IUI treatment with a tailored approach. The professionalism and support made the entire process feel manageable. Highly recommend her expertise!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocI-ED_3STq78dZjSdAzoq1vnownZ1JgknPExw26IZZOOgDXKg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/FNwAv61a6Km2EcMq5"
    },
    {
      "id": 14,
      "center_name": "dilshuknagar",
      "clinic_location": "dilshuknagar",
      "city": "Dilshuknagar",
      "rating": 4.9,
      "name": "Tulasi Vinnu",
      "reviews": "Our journey felt endless until we met the right specialist. The IUI treatment was carefully planned, and the doctor’s expertise was evident in every step.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKMgoqB8uNKk6gRD6JQQRM7zTcjdcSkoRyWOcr7OLaj99sCWA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/2yKfm4asq1GMpuQ48"
    },
    {
      "id": 15,
      "center_name": "dilshuknagar",
      "clinic_location": "dilshuknagar",
      "city": "Dilshuknagar",
      "rating": 4.9,
      "name": "Gavvala Srinivas",
      "reviews": "Infertility made us anxious. Dr. Sai Manasa Darla was a true guide, explaining the IUI procedure in detail. Her reassuring nature eased our stress, and the treatment was seamless. A great experience with a skilled specialist!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKMMs_ocH0w9LsaqPdWN8jhI8p_cL8N7XyTbuApk4gmDKAX3w=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/eM7rKDYKWNjtqt7QA"
    },
    {
      "id": 16,
      "center_name": "dilshuknagar",
      "clinic_location": "dilshuknagar",
      "city": "Dilshuknagar",
      "rating": 4.9,
      "name": "Raj Bag",
      "reviews": "I was hesitant about IUI treatment, but the doctor’s patience in explaining everything reassured me. The whole experience was smooth and stress-free.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKkOoaWijfwPb_UnLGYnnxWOys14Zk64Gb8HUMIbMOc1ZRtAg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/SwN1D3yx7r4rXJff9"
    },
    {
      "id": 17,
      "center_name": "secunderabad",
      "clinic_location": "secunderabad",
      "city": "Secunderabad",
      "rating": 4.9,
      "name": "Harikrishna Boini",
      "reviews": "Feeling lost with failed attempts, we turned to Dr. Parinaaz Parhar. Her expertise in IUI treatment was evident from day one. The care we received was exceptional, making the process easier and giving us renewed confidence.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKGrowOzdEQfyrpQbX110iIpuIj3ZedlLv3scrurCilai75rg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/sCsGYqhc3PbV1mMFA"
    },
    {
      "id": 18,
      "center_name": "secunderabad",
      "clinic_location": "secunderabad",
      "city": "Secunderabad",
      "rating": 5,
      "name": "Hardik Mehta",
      "reviews": "Finding the right IUI specialist near me felt daunting, but Dr. Parinaaz Parhar was the perfect choice. The treatment was well-planned, and the emotional support we received was invaluable.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIwXRLZFbaSm3J8S-48YPzvt53xlgzY5A92PAcC2aCsLTUREg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/tF6XYUPFmQMhqkNm7"
    },
    {
      "id": 19,
      "center_name": "secunderabad",
      "clinic_location": "secunderabad",
      "city": "Secunderabad",
      "rating": 4.9,
      "name": "Syamala Ramu",
      "reviews": "Doubts and anxiety surrounded our decision, but the doctor’s calm and professional approach to IUI treatment changed everything. We felt supported throughout.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWqVoW6QXFyc0tGSejh39vXYp61SqVH_6WDt4eyRZtgSKQsgzaI=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/E84o9Kqd3QkEf9t48"
    },
    {
      "id": 20,
      "center_name": "secunderabad",
      "clinic_location": "secunderabad",
      "city": "Secunderabad",
      "rating": 4.9,
      "name": "Gangula",
      "reviews": "Finding the best IUI specialist near me was crucial. The doctor was not just skilled but also compassionate, making the entire process comfortable.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIxFQjkN6BhNFYe0QUZJ3zTa7ZmPMsRAINfGQTu7xcwSxrpDQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/UiPcXYQ3BJDdakGY8"
    },
    {
      "id": 21,
      "center_name": "miyapur",
      "clinic_location": "miyapur",
      "city": "Miyapur",
      "rating": 4.9,
      "name": "Hari Brahmeswara Reddy Kovvuri",
      "reviews": "The uncertainty of infertility was overwhelming. Dr. Srinivasa Varalakshmi Yakasiri provided clarity and hope. Her personalized IUI treatment plan was exactly what we needed. We felt heard, supported, and optimistic about the future.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXcTSSs5eIUWMrOMgpjPQgSAkx5Y58IRPVDhVGSsm-ivm3er8q-=w56-h56-p-rp-mo-ba4-br100",
      "review_link": "https://maps.app.goo.gl/cdpjmbj96MQyrvcz8"
    },
    {
      "id": 22,
      "center_name": "miyapur",
      "clinic_location": "miyapur",
      "city": "Miyapur",
      "rating": 4.9,
      "name": "Anusha Bontha",
      "reviews": "We had tried various treatments before considering IUI. The specialist’s professionalism and warmth made all the difference in our journey.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocK2Rg4DEzwEbqSfXri9_umr7sx-BVW6l21kua4STaSYwKZ_0w=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/SHcvrFj7MTpBhA377"
    },
    {
      "id": 23,
      "center_name": "miyapur",
      "clinic_location": "miyapur",
      "city": "Miyapur",
      "rating": 4.9,
      "name": "Navaneeth Rao",
      "reviews": "Struggling with conception was tough. A friend recommended IUI, and we’re grateful for the specialist’s expertise and genuine support.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKTpj2xInuEhuIBMrsrTvhQl5zOMoPsdj4vFgl-ECbUlzqHBw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/KkY24v8QbYyt4VnZA"
    },
    {
      "id": 24,
      "center_name": "miyapur",
      "clinic_location": "miyapur",
      "city": "Miyapur",
      "rating": 4.9,
      "name": "Shirley George",
      "reviews": "The journey was emotionally draining until we found a specialist who truly cared. The IUI treatment was conducted with precision, and the care we received was unmatched.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUmLGJZ9Lzd-qILCt4gdLl6M7xL743q4BoiVJhHy09GdE2BH5bhWQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/ryH671hiknmvZdNS9"
    },
    {
      "id": 25,
      "center_name": "kompally",
      "clinic_location": "kompally",
      "city": "Kompally",
      "rating": 5,
      "name": "Jarupula Vanditha",
      "reviews": "Trying for a baby felt like an endless journey. Dr. Meera Jindal's compassionate approach and deep expertise in IUI treatment made all the difference. The process was stress-free, and I felt truly cared for. Grateful for the kindness and support!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjViJX9oQ9qwkdEpIgLUMQ4ij65aQ6lwQSMRhJynRW6r85umOgYR=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/5XGSjn2JekPiXf1S9"
    },
    {
      "id": 26,
      "center_name": "kompally",
      "clinic_location": "kompally",
      "city": "Kompally",
      "rating": 5,
      "name": "Pavan Thati",
      "reviews": "After months of uncertainty, we finally took a step towards IUI treatment. The entire experience was handled professionally, giving us much-needed confidence.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVus2iJKmiCvpXBr9o8gWNDBDgCd26yTQUy2bpoq7HlY2-V_fSyew=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/MHprTCVZ5sEhLkm76"
    },
    {
      "id": 27,
      "center_name": "kompally",
      "clinic_location": "kompally",
      "city": "Kompally",
      "rating": 5,
      "name": "Hrishabh",
      "reviews": "Each failed attempt hurt, but our IUI doctor gave us renewed hope. Their expertise and support made the process smoother than we expected.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVNVV8YharMC-nxNhyzS1reAODVxyPKdkaQmUMe1BJmIkESXL5y=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/v2ARN6EZeyvDzeaS6"
    },
    {
      "id": 28,
      "center_name": "kompally",
      "clinic_location": "kompally",
      "city": "Kompally",
      "rating": null,
      "name": "kalyan kumar",
      "reviews": "Fertility struggles are never easy, but with the right IUI specialist, the journey became manageable. The doctor’s approach was both scientific and heartfelt.",
      "profile_picture": null,
      "review_link": null
    },
    {
      "id": 29,
      "center_name": "uppal",
      "clinic_location": "uppal",
      "city": "Uppal",
      "rating": 4.9,
      "name": "Vinod Kumar Aitipamula",
      "reviews": "Struggling with infertility was exhausting. I had almost lost hope until I found Dr. M V D Aruna. Her guidance through my IUI treatment was reassuring. The procedure was smooth, and today, I am filled with hope again. Highly recommend for anyone seeking expert care.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjV2-uEOl8kSmfKYgIcKfQDjXQ9uSsoTPUNyd2SCVD6MCHDzPvE=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/g9iymmWGKKB9HD978"
    },
    {
      "id": 30,
      "center_name": "uppal",
      "clinic_location": "uppal",
      "city": "Uppal",
      "rating": 4.9,
      "name": "Krishnamohan Kunthipuram",
      "reviews": "Infertility felt like an endless battle. After consulting an IUI specialist, we finally had a clear plan. The treatment was smooth, and the doctor’s care gave us renewed confidence in our journey.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLiolgNvVj1OjALIn9i0ZQ6G8RTjIKW9ALllx05hkq7Vt81Iw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/61GKBJD7ZUZt28vj6"
    },
    {
      "id": 31,
      "center_name": "uppal",
      "clinic_location": "uppal",
      "city": "Uppal",
      "rating": 4.9,
      "name": "Poolapalli Chinnari",
      "reviews": "We had almost given up, but IUI treatment turned things around. The doctor’s expertise, patience, and encouragement helped us stay positive throughout the process. Truly grateful for such great care.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJkDO8eKvwFMo64UNbC13KvZJ7FtnhcUqe8-Ec1dGOFL1u9kg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/Md42qHzCqEk5QJYr6"
    },
    {
      "id": 32,
      "center_name": "uppal",
      "clinic_location": "uppal",
      "city": "Uppal",
      "rating": 4.9,
      "name": "Navya Jonnadhula",
      "reviews": "The emotional rollercoaster of trying to conceive was exhausting. The IUI specialist not only guided us medically but also provided emotional support. The treatment was seamless, and we felt reassured every step of the way.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJVH0o6Q7Cer9XUrE4tcn5Qub7iiuuSZTZB4ThDlG79K7Cm9w=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/gzc5AwhSNhy4EH6bA"
    },
    {
      "id": 33,
      "center_name": "Hanamkonda",
      "clinic_location": "Hanamkonda",
      "city": "Hanamkonda",
      "rating": 4.7,
      "name": "Bala Krishna",
      "reviews": "Infertility was taking a toll on us. Finding the best IUI center near me felt overwhelming, but Dr. Jalagam Kavya Rao’s expertise changed everything. The clinic was well-equipped, and the treatment was handled with care and professionalism.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjW-lE6tP5h5DoUMNrfC71mwbGnpJgyi4zMAPW8bhO_5UXs7WJI7=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/3SfsZZWQmH8rbitX9"
    },
    {
      "id": 34,
      "center_name": "Hanamkonda",
      "clinic_location": "Hanamkonda",
      "city": "Hanamkonda",
      "rating": 4.7,
      "name": "Bhukya Suresh Nayak",
      "reviews": "Infertility was taking a toll on us. Finding the best IUI center near me felt overwhelming, but Dr. Jalagam Kavya Rao’s expertise changed everything. The clinic was well-equipped, and the treatment was handled with care and professionalism.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjX8V10HJUFGi3sKhRr8GZJFL7yQ5b_I-_T5zCh5pVmRbTlQheaK7A=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/qM9qGkrjsHXfZr6w6"
    },
    {
      "id": 35,
      "center_name": "Hanamkonda",
      "clinic_location": "Hanamkonda",
      "city": "Hanamkonda",
      "rating": 4.7,
      "name": "Sangeetha Rani Yanamanagandla",
      "reviews": "After years of unsuccessful attempts, we were searching for the best IUI center near me. The staff was kind, the process was smooth, and the doctor’s guidance gave us much-needed confidence. Grateful for the support we received.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocK4QoOqj4nR9OoqWFQ2JGaYCS8sBVgUaAzdlSkBnElXfdj_VQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/YokoGx2CFdgkh6oJ9"
    },
    {
      "id": 36,
      "center_name": "Hanamkonda",
      "clinic_location": "Hanamkonda",
      "city": "Hanamkonda",
      "rating": 4.9,
      "name": "Sathish Yadav Sathish",
      "reviews": "We were unsure about where to start, but this IUI center provided a clear and comforting path. The doctor took time to explain everything, and the team ensured a stress-free experience. Highly recommended for those on this journey.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJrkoJZO2hgnJOnGH3W6H4qVNdyaJRd0FI_tMnEtSYvPS06Sw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/PwxwSTwERz6Y38CT9"
    },
    {
      "id": 37,
      "center_name": "karimnagar",
      "clinic_location": "karimnagar",
      "city": "Karimnagar",
      "rating": 5,
      "name": "Bandi Mamatha",
      "reviews": "The uncertainty of fertility treatments made us anxious. We chose an IUI center based on its reputation, and the experience exceeded expectations. Every step was handled with care, and we felt truly supported throughout.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJ0aM72z0UR7aQxic9hXu43CGrS2P17Yevbx9t8jyCNOKXK0g=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/zJBSZApFpMpoEvEZ8"
    },
    {
      "id": 38,
      "center_name": "karimnagar",
      "clinic_location": "karimnagar",
      "city": "Karimnagar",
      "rating": 5,
      "name": "Prashanth Chinni",
      "reviews": "Struggling with infertility left us feeling hopeless. Finding the best IUI center near me was life-changing. Dr. Jigna Tamagond provided compassionate care, making sure we were comfortable and informed at every stage.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUnL9m4u_IdKx-SjsRaD9t9aLs4I4V7xEux7VQEudM6a-oKJ88=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/z5usb7bNuseNho5c7"
    },
    {
      "id": 39,
      "center_name": "karimnagar",
      "clinic_location": "karimnagar",
      "city": "Karimnagar",
      "rating": 5,
      "name": "Akula Sandhyarani",
      "reviews": "We had so many questions about IUI treatment, but the doctor and staff at this center made everything clear. The process was seamless, and we felt reassured by the expertise and personal attention we received.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLHPl6BT1EvaonPBmfn_oq04Sy8iH2l_s2mw3m1Lb7KpjfEzg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/dx41QVeLs4JJVWz39"
    },
    {
      "id": 40,
      "center_name": "karimnagar",
      "clinic_location": "karimnagar",
      "city": "Karimnagar",
      "rating": 5,
      "name": "Harish",
      "reviews": "Choosing the right IUI center was crucial for us. From the first consultation to the procedure, we were treated with kindness and professionalism. The team truly understands the emotional side of this journey.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVxY-cxqfttf7WPYFG_uJ8lu3TQbQB_-JSKsUndoyS1XJuT0c7QzA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/tMmQgvUidoeS592EA"
    },
    {
      "id": 41,
      "center_name": "vijayawada",
      "clinic_location": "vijayawada",
      "city": "Vijayawada",
      "rating": 4.9,
      "name": "Kotha Mrudula",
      "reviews": "We were worried about the IUI cost in Vijayawada and unsure where to go. After researching, we found a clinic that offered both affordability and expert care. The staff was supportive, and the treatment process was smooth, making us feel confident in our choice.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLS4kVGN-UiZSIqZuilE5y1fDAGhft6zZE3ljp97H-pCjHoIw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/RPhq128i2Q6VkjQM7"
    },
    {
      "id": 42,
      "center_name": "vijayawada",
      "clinic_location": "vijayawada",
      "city": "Vijayawada",
      "rating": 4.9,
      "name": "Dubba Sunil",
      "reviews": "Finding quality IUI treatment near me felt overwhelming. The clinic we chose provided clear guidance and a stress-free experience. The doctor explained each step in detail, ensuring we were comfortable and well-informed throughout the journey.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXK7SlU5nnePsEC1y0A3OVEOXdDU8tmkZgWZaTIckV_kuicKLW-aw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/MPVe5xJu78HGZy8k9"
    },
    {
      "id": 43,
      "center_name": "vijayawada",
      "clinic_location": "vijayawada",
      "city": "Vijayawada",
      "rating": 4.9,
      "name": "Siva Sai Kumar",
      "reviews": "We wanted an experienced IUI specialist near me and were fortunate to find a compassionate and skilled doctor. The process was straightforward, and the support we received made a huge difference in our journey.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWtp1oTxQQ8CEo7iHXuLWYftp7gaVcnadSE6ZJGm0_-lnd3oq8=w56-h56-p-rp-mo-br100",
      "review_link": "https://www.google.com/maps/contrib/118068252448421908233/reviews"
    },
    {
      "id": 44,
      "center_name": "vijayawada",
      "clinic_location": "vijayawada",
      "city": "Vijayawada",
      "rating": 4.9,
      "name": "Sandhya Dodla",
      "reviews": "Infertility was stressful, but Dr. Venkata Sujatha Vellanki’s expertise made all the difference. She explained everything clearly, and the entire team provided excellent care. The experience was reassuring, and we finally felt hopeful again.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIY9Q890869J-EYPfc6nECGVJYyM_vv3-5MbwVBQmhr3U-wSg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/GCs6j4WoX1aocB4B9"
    },
    {
      "id": 45,
      "center_name": "visakhapatnam",
      "clinic_location": "visakhapatnam",
      "city": "Visakhapatnam",
      "rating": 4.9,
      "name": "Gummala Darababu",
      "reviews": "We were unsure about the IUI treatment cost and whether it was the right option for us. After consulting with a specialist, we got a clear understanding of the process and pricing. The care and transparency we received made us feel confident in moving forward.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIw-OEqRYyxaLo_9pYPfh8swi9WPIFIyhOZEEMHV8or7mQ5dw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/p6Bpv6NSXUbPn2NLA"
    },
    {
      "id": 46,
      "center_name": "visakhapatnam",
      "clinic_location": "visakhapatnam",
      "city": "Visakhapatnam",
      "rating": 4.9,
      "name": "Yarra Vandana",
      "reviews": "Affording fertility treatments was a big concern. We researched the IUI treatment cost and found a clinic that balanced quality care with reasonable pricing. The experience was smooth, and the doctor ensured we were comfortable every step of the way.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjW0JKaRLeyFha_xEjU0t_iMrAIbM7hjcsyTjGm05rIbuyAe8WEi=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/oH6ejG5h24DvrQjn7"
    },
    {
      "id": 47,
      "center_name": "visakhapatnam",
      "clinic_location": "visakhapatnam",
      "city": "Visakhapatnam",
      "rating": 4.9,
      "name": "Kamesh Royistan",
      "reviews": "Finding affordable fertility solutions was stressful. We looked into the IUI treatment cost and were relieved to find a clinic that offered both expertise and transparency. The doctor explained everything clearly, making the process easier to navigate.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXVxWnMxcUPeERYbdEhnyB80CdoL5VWAPl6l4mUEWU2lNNpu5YlRw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/USfR1dzt28yvS8Ui6"
    },
    {
      "id": 48,
      "center_name": "visakhapatnam",
      "clinic_location": "visakhapatnam",
      "city": "Visakhapatnam",
      "rating": 4.9,
      "name": "Kasina Suguna",
      "reviews": "We had so many doubts about IUI, but Dr. Radhika Potluri patiently answered all our questions. She provided a detailed breakdown of the IUI treatment cost, ensuring we understood everything. The care and attention we received were truly exceptional.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKVU_MH5HafV6WV_d8NSN3pq-84_n6rfEFvc1E8jOzn94F7GA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/yewzRut981Sx4pM29"
    },
    {
      "id": 49,
      "center_name": "guntur",
      "clinic_location": "guntur",
      "city": "Guntur",
      "rating": 5,
      "name": "Istikhar",
      "reviews": "We were worried about the IUI cost in Guntur and whether it was within our budget. After visiting a well-reputed clinic, we were relieved to find affordable options without compromising on quality. The doctor guided us through the process, making it stress-free.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKCWeHIGgh6u9isiJ-NQnop8nEDZ-uATxwK2auiAavA-xAFeA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/dbt3NggMRuAmeU3E8"
    },
    {
      "id": 50,
      "center_name": "guntur",
      "clinic_location": "guntur",
      "city": "Guntur",
      "rating": 5,
      "name": "Nisha Shaikh",
      "reviews": "Understanding the IUI cost in Guntur was confusing at first, but after consulting a specialist, we received a clear breakdown. The clinic offered expert care at reasonable rates, and the staff was incredibly supportive throughout our journey.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJ2kEqiIdh8rbDHtQFVw1sXlFMS_OeQ3Z6_wGxrTK_ocqsjRw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/NPugY1sfeCPDAMyDA"
    },
    {
      "id": 51,
      "center_name": "guntur",
      "clinic_location": "guntur",
      "city": "Guntur",
      "rating": 5,
      "name": "Lovaraju Madda",
      "reviews": "Fertility treatments can be expensive, so we researched the IUI cost in Guntur before making a decision. The clinic we chose provided detailed information, excellent care, and a comfortable experience that made the entire process much easier.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUZI3FpS9kIPN5mnf-cyTgE9GOLHptYPDOY5j1PTvMVg4eSlWA2=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/b7CoCo2DVwQmb7zg9"
    },
    {
      "id": 52,
      "center_name": "guntur",
      "clinic_location": "guntur",
      "city": "Guntur",
      "rating": 5,
      "name": "Gudimella Vasavi Sujatha",
      "reviews": "We had so many concerns, but Dr. Ramya Vicharapu addressed all our doubts with patience. She explained the IUI cost in Guntur clearly and made sure we understood each step of the treatment. The experience was reassuring and well-managed.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIlB6BtSJ16RCzhV6MGbbrm1TrMBHTllesABNkkrIxxpQ_lKw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/JFfTsyGXy197u8Ha8"
    },
    {
      "id": 53,
      "center_name": "ongole",
      "clinic_location": "ongole",
      "city": "Ongole",
      "rating": 5,
      "name": "Sulthan Sk",
      "reviews": "We were anxious about the IUI treatment success rate and whether it would work for us. After choosing the best IUI center near me, we felt hopeful. The doctor explained everything clearly, and the care we received made all the difference in our journey.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLjZJura-jRNkBjDYtXp1YUE0vU01Hqjn9t7gDxhSxLfwJVig=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/5gxg9jhvZUVndE9u7"
    },
    {
      "id": 54,
      "center_name": "ongole",
      "clinic_location": "ongole",
      "city": "Ongole",
      "rating": 5,
      "name": "Vijaya Lakshmi",
      "reviews": "The uncertainty of fertility treatments was overwhelming. We researched the IUI treatment success rate and found a clinic known for excellent results. The staff was supportive, and the entire process was handled with professionalism and care.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKdz6BWe7V3GkKVStPW-d_McqgFYt4Fe2jtYYCgfM1Nc8yyoA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/ELBL5kCx343uagUi6"
    },
    {
      "id": 55,
      "center_name": "ongole",
      "clinic_location": "ongole",
      "city": "Ongole",
      "rating": 5,
      "name": "Urvashi",
      "reviews": "Choosing the best IUI center near me was crucial. From the first consultation to the procedure, the experience was smooth and reassuring. The doctor’s expertise and the clinic’s advanced approach gave us confidence throughout the process.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLqy1Ifrbz-sMhVQ8jOV4kLzs1tNvsuny5lgHISMeAbIUXX-Q=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/9J6xMgepSdi2XnhLA"
    },
    {
      "id": 56,
      "center_name": "ongole",
      "clinic_location": "ongole",
      "city": "Ongole",
      "rating": 5,
      "name": "Dhana Lakshmi",
      "reviews": "We were hesitant about IUI, but Dr. Deepika Boppana provided clear guidance and reassurance. She explained the IUI treatment success rate and tailored the approach to our needs. The journey was emotional, but the support we received made all the difference.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJIMyV12fRC8r4XgsCh3cALjnSJhfHob20kfJyKcpUvkeKPWg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/j5YAuPGUroDXw1Mo6"
    },
    {
      "id": 57,
      "center_name": "tirupati",
      "clinic_location": "tirupati",
      "city": "Tirupati",
      "rating": 4.9,
      "name": "Usha Nallapareddy",
      "reviews": "We had so many doubts, but Dr. Nadikattu Saranya Lakshmi was incredibly patient and supportive. She explained everything in detail, making IUI treatment much easier to understand. The compassionate approach made a tough journey feel manageable.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJ-2YAQLOakjWHiTvytLyANuo1b41YunzzHTMrutSR1y3VpsA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/DSiWfWy5L3tmGMqq8"
    },
    {
      "id": 58,
      "center_name": "tirupati",
      "clinic_location": "tirupati",
      "city": "Tirupati",
      "rating": 4.9,
      "name": "Divya K",
      "reviews": "Searching for IUI treatment near me felt overwhelming. After visiting a trusted clinic, we finally felt reassured. The doctor took the time to explain each step, ensuring we were comfortable and prepared throughout the entire process.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIh0moEZM9Jfu-Z4pO03_ThQlFggGbXHvOcPLakeZC9tYHPXRKX=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/gRSzm4A9Rj2cezxN8"
    },
    {
      "id": 59,
      "center_name": "tirupati",
      "clinic_location": "tirupati",
      "city": "Tirupati",
      "rating": 4.9,
      "name": "Kiran Teja",
      "reviews": "Fertility struggles can be exhausting, but finding the right IUI treatment made all the difference. The clinic was well-equipped, and the team’s expertise helped us stay positive. Every step was handled with care and professionalism.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVPlg-FteaQdQLj_woNS4OS9UmcwW0BH6Ig5oUkRKVf0mxRFrk=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/bzKkEFuiFREWCTdT7"
    },
    {
      "id": 60,
      "center_name": "tirupati",
      "clinic_location": "tirupati",
      "city": "Tirupati",
      "rating": 4.9,
      "name": "Sarah",
      "reviews": "We were nervous about starting IUI treatment, unsure of what to expect. After finding a reliable clinic, we received clear guidance and excellent care. The team made the process smooth, giving us hope and confidence in our journey.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJAdbdA0Uy_bqDtq5ML-IhsWBaRNNWPXGaeh-_P5cOOprdX6w=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/caJh5ncRsAuu8iuZA"
    },
    {
      "id": 61,
      "center_name": "kurnool",
      "clinic_location": "kurnool",
      "city": "Kurnool",
      "rating": 5,
      "name": "Srikanth Sri",
      "reviews": "Finding the best IUI center near me was a challenge, but once we stepped into this clinic, we knew we made the right choice. The team was professional, the environment was comforting, and the entire process was well-managed from start to finish.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJV0CbscHMoi8u1hCrFTgJe-jBE18h7cyY7tZAba3nO6IjjY96z=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/TUi1nzMLia3mfQhE7"
    },
    {
      "id": 62,
      "center_name": "kurnool",
      "clinic_location": "kurnool",
      "city": "Kurnool",
      "rating": 5,
      "name": "Madhusudan Naidu Pathipati",
      "reviews": "We wanted to consult a top IUI specialist for expert guidance. The doctor explained everything clearly, making us feel confident. The treatment process was smooth, and the staff ensured we felt supported throughout our journey.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJJqeZyvFm1fC9s5Wy35_EqRjG5jAHujaRg7SDrqIg-u9dblw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/YSQ4a76euJ2Gsofz9"
    },
    {
      "id": 63,
      "center_name": "kurnool",
      "clinic_location": "kurnool",
      "city": "Kurnool",
      "rating": 5,
      "name": "Vasanth Appapogu",
      "reviews": "Choosing the best IUI center near me felt overwhelming at first, but this clinic stood out with its advanced facilities and compassionate care. From consultation to treatment, everything was handled with expertise and kindness.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKqcRkT75CGLsu44io3o73xFfGLta_9biNXnBfuaOYo0LszSw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/dUE997hEDGkD257g8"
    },
    {
      "id": 64,
      "center_name": "kurnool",
      "clinic_location": "kurnool",
      "city": "Kurnool",
      "rating": 4.9,
      "name": "Gowthami Gowni",
      "reviews": "Dr. Vijayalakshmi D was incredibly patient and understanding. As a top IUI specialist, she provided clear guidance and reassurance throughout our treatment. The care we received here gave us renewed hope in our journey.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWIfG_ONIOQqjrx7OExlhmR__iP_5KVoJ6Jw9tZC2dbJzJqMbCu=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/TbUNdQyBTN7nhkaJ8"
    },
    {
      "id": 65,
      "center_name": "Bengaluru",
      "clinic_location": "HSR",
      "city": "Bengaluru",
      "rating": 4.9,
      "name": "Haribabu Tata",
      "reviews": "Finding the best IUI center near me was overwhelming. After visiting this clinic, we felt reassured. The staff was kind, the process was well-explained, and the treatment went smoothly. We finally had hope again.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJGNAbwp_l1bJcENwg1tG9Y5Nr4ZlHjFneKljumt5OLUJc2zwQ=w56-h56-p-rp-mo-ba3-br100",
      "review_link": "https://maps.app.goo.gl/kVN2F8wwg7fYwNfT9"
    },
    {
      "id": 66,
      "center_name": "Bengaluru",
      "clinic_location": "HSR",
      "city": "Bengaluru",
      "rating": 4.9,
      "name": "Sumon Laskar",
      "reviews": "We struggled to conceive for years. Choosing the best IUI center near me made a huge difference. The team was supportive, ensuring we understood every step. The treatment was stress-free and handled with great care.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKbxVIncIvGGMCydXmsvR9VqGexuzyNOF1Y93CWTT8Fd2B3RA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/DPJ64qNRhFqKev47A"
    },
    {
      "id": 67,
      "center_name": "Bengaluru",
      "clinic_location": "banashankari",
      "city": "Bengaluru",
      "rating": 4.9,
      "name": "Navitham",
      "reviews": "The journey to parenthood wasn’t easy, but this IUI center provided excellent support. From the first consultation to the treatment, we felt comfortable and confident in their expertise.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUlN4o3xhycMK7e6eFmN5xobNFkvbzkMTttXJ8JZhIXa5DUcgw5lA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/iqaeLBBEv51Rkx7n8"
    },
    {
      "id": 68,
      "center_name": "Bengaluru",
      "clinic_location": "hebbal",
      "city": "Bengaluru",
      "rating": 4.9,
      "name": "Shireen Shariff",
      "reviews": "We were nervous about the process, but the care at this center made all the difference. The staff was patient, the environment was comforting, and the entire journey was handled with professionalism.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLllXJDL20xxHz7E6T4CDm2Qpt1HFt9_b8e87_z55bbvr1a0A=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/rtq7m8fHqJfLSKif7"
    },
    {
      "id": 69,
      "center_name": "HSR",
      "clinic_location": "HSR",
      "city": "Hsr",
      "rating": 4.9,
      "name": "Haribabu Tata",
      "reviews": "The best IUI center near me not only provided top-notch treatment but also emotional support. The doctor explained everything thoroughly, making sure we were comfortable and informed.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJGNAbwp_l1bJcENwg1tG9Y5Nr4ZlHjFneKljumt5OLUJc2zwQ=w56-h56-p-rp-mo-ba3-br100",
      "review_link": "https://maps.app.goo.gl/kVN2F8wwg7fYwNfT9"
    },
    {
      "id": 70,
      "center_name": "HSR",
      "clinic_location": "HSR",
      "city": "Hsr",
      "rating": 4.9,
      "name": "Neha Vernekar",
      "reviews": "Fertility treatments can be daunting, but this clinic’s expert team made the experience easier. The staff’s kindness and the doctor’s expertise reassured us throughout the journey.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKvLgY_zs3qj6XLcl9D39IsKTCux5Cr7wEPyw8_1OTBs1fDrw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/7XysC3Z1eyLz4qvk7"
    },
    {
      "id": 71,
      "center_name": "HSR",
      "clinic_location": "HSR",
      "city": "Hsr",
      "rating": 4.9,
      "name": "Manikeshwari K",
      "reviews": "We had heard about this IUI center from a friend. The experience was wonderful—the doctor’s approach was patient and understanding, and the staff was always available to help.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKLdL9IMtSrXEVOoE-h0Vwf9ghAlLbVbkdoF1nn8GV6koWaS5Jv=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/5fX9pg83f7pnbLV66"
    },
    {
      "id": 72,
      "center_name": "HSR",
      "clinic_location": "HSR",
      "city": "Hsr",
      "rating": 4.9,
      "name": "Sumon Laskar",
      "reviews": "The search for the best IUI center near me ended here. The clinic was well-equipped, the doctor was experienced, and the care we received was exceptional. Highly recommended!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKbxVIncIvGGMCydXmsvR9VqGexuzyNOF1Y93CWTT8Fd2B3RA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/DPJ64qNRhFqKev47A"
    },
    {
      "id": 73,
      "center_name": "banashankari",
      "clinic_location": "banashankari",
      "city": "Banashankari",
      "rating": 5,
      "name": "Rs Gowda",
      "reviews": "Dr. Prinka Bajaj was incredibly patient and thorough in explaining the process. She provided reassurance and expert care, making a difficult journey much more manageable.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWeCA_Yq1YVje93tm3C0gPCkQLNBzI7XSOh-0PwClZGNCDKvCv6=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/tb1WxbCLsZ7Ry1qH7"
    },
    {
      "id": 74,
      "center_name": "banashankari",
      "clinic_location": "banashankari",
      "city": "Banashankari",
      "rating": 5,
      "name": "Sadhana Naik",
      "reviews": "A compassionate and knowledgeable team made all the difference in our fertility journey. The doctor took time to address our concerns, and the procedure was carried out with precision.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXLGXX-iwMC3GAmK59zMIMask5-no_AzPbK4l4lh7lfslBJWs61=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/iRX5vx4RQy2xc4Qr9"
    },
    {
      "id": 75,
      "center_name": "banashankari",
      "clinic_location": "banashankari",
      "city": "Banashankari",
      "rating": 5,
      "name": "Mohana Priya",
      "reviews": "Choosing this IUI center was the best decision. The doctor guided us at every step, and the support from the staff made a tough journey much easier.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJMWp-PjgnCuIPjbMcPPH-AT_S_dW_kXb3SKW3SVtvWkBR6eg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/3QhsmwetyKdRna8a6"
    },
    {
      "id": 76,
      "center_name": "banashankari",
      "clinic_location": "banashankari",
      "city": "Banashankari",
      "rating": 4.9,
      "name": "Sumon Laskar",
      "reviews": "The clinic exceeded our expectations in terms of care, expertise, and results. The doctor’s dedication and the well-organized treatment plan gave us much-needed hope.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKbxVIncIvGGMCydXmsvR9VqGexuzyNOF1Y93CWTT8Fd2B3RA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/DPJ64qNRhFqKev47A"
    },
    {
      "id": 77,
      "center_name": "hebbal",
      "clinic_location": "hebbal",
      "city": "Hebbal",
      "rating": 4.9,
      "name": "Sanjeeva Rayudu",
      "reviews": "This IUI center stood out because of its experienced team and advanced technology. Every step was explained clearly, and we felt reassured throughout the process.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJuObpZTQRri922E7s74N32Y5rj4p-lhuLeKYgIV4c35jJLpg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/TJvLpiAsJuXGVmgD6"
    },
    {
      "id": 78,
      "center_name": "hebbal",
      "clinic_location": "hebbal",
      "city": "Hebbal",
      "rating": 4.9,
      "name": "Navitham",
      "reviews": "We were hesitant about IUI, but the doctor’s clear explanations and the clinic’s professional approach made everything smooth. It was the best choice for us.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUlN4o3xhycMK7e6eFmN5xobNFkvbzkMTttXJ8JZhIXa5DUcgw5lA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/iqaeLBBEv51Rkx7n8"
    },
    {
      "id": 79,
      "center_name": "hebbal",
      "clinic_location": "hebbal",
      "city": "Hebbal",
      "rating": 4.9,
      "name": "Maheshwari Eswari Eswari",
      "reviews": "Finding the right IUI center was stressful, but this clinic made us feel comfortable from the start. The treatment was handled with care, and the doctor was incredibly understanding.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLlmJMaEy9zvaY_KbuNuSfZ8DMJ3JutTDLf-OoGC2TWuG-YIg=w56-h56-p-rp-mo-ba3-br100",
      "review_link": "https://maps.app.goo.gl/EvypeEDc6piPsXvm7"
    },
    {
      "id": 80,
      "center_name": "hebbal",
      "clinic_location": "hebbal",
      "city": "Hebbal",
      "rating": 4.9,
      "name": "Shireen Shariff",
      "reviews": "The team at this IUI center was not only professional but also compassionate. They understood our concerns and provided the right guidance, making the process easier.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLllXJDL20xxHz7E6T4CDm2Qpt1HFt9_b8e87_z55bbvr1a0A=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/rtq7m8fHqJfLSKif7"
    },
    {
      "id": 81,
      "center_name": "hebbal",
      "clinic_location": "hebbal",
      "city": "Hebbal",
      "rating": 4.9,
      "name": "Navitham",
      "reviews": "The support we received from Dr. Shalini M A and the team was outstanding. Their expertise and attention to detail made our IUI treatment experience smooth and stress-free.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUlN4o3xhycMK7e6eFmN5xobNFkvbzkMTttXJ8JZhIXa5DUcgw5lA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/wp3tDC7gv8cTLFT78"
    },
    {
      "id": 82,
      "center_name": "belagavi",
      "clinic_location": "belagavi",
      "city": "Belagavi",
      "rating": 5,
      "name": "Sudha Patil",
      "reviews": "A warm and welcoming environment, combined with expert care, made our IUI journey stress-free. The doctor and team ensured we felt comfortable every step of the way.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocI1TuDkNb8oFapWusEkLel-5hC9n2XGu9__loaZ3keH8eme9w=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/2P4vyoUXe36x13Th9"
    },
    {
      "id": 83,
      "center_name": "belagavi",
      "clinic_location": "belagavi",
      "city": "Belagavi",
      "rating": 5,
      "name": "Adam",
      "reviews": "Choosing this clinic was the best decision. The doctor’s expertise and the staff’s dedication made our IUI treatment smooth and reassuring.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXoGIPncmjzMXAU2hregFSYNbdMQlcXOlOrAf4ETyfeWmAc3m-L=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/LwBDgVkyo5UWqRWu8"
    },
    {
      "id": 84,
      "center_name": "belagavi",
      "clinic_location": "belagavi",
      "city": "Belagavi",
      "rating": 5,
      "name": "Irfan Khan",
      "reviews": "The best IUI center near me not only provided excellent medical care but also emotional support. We felt valued and cared for throughout the process.",
      "profile_picture": null,
      "review_link": "https://maps.app.goo.gl/LwBDgVkyo5UWqRWu8"
    },
    {
      "id": 85,
      "center_name": "belagavi",
      "clinic_location": "belagavi",
      "city": "Belagavi",
      "rating": 4.9,
      "name": "Sharada Shiledar",
      "reviews": "A well-organized clinic with knowledgeable doctors and a caring staff. The process was seamless, and we felt confident in the treatment we received.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJVFU-oPlfCdh0sIYzesdWv7hoydWH6FNOp9tURs3AUByoC=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/j2QFgGtV4pyakmXa9"
    },
    {
      "id": 86,
      "center_name": "belagavi",
      "clinic_location": "belagavi",
      "city": "Belagavi",
      "rating": 5,
      "name": "Sharada Shiledar",
      "reviews": "From the first visit, we knew we were in the right place. The doctor explained the entire procedure in detail, and the staff was extremely supportive.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJVFU-oPlfCdh0sIYzesdWv7hoydWH6FNOp9tURs3AUByoC=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/JpQ7TYu5xBrm2apC9"
    },
    {
      "id": 87,
      "center_name": "chennai",
      "clinic_location": "chennai",
      "city": "Chennai",
      "rating": 4.9,
      "name": "Karthikaarjun A",
      "reviews": "Dr. Hema provided exceptional care during our IUI journey. She explained the procedure in detail and answered all our concerns. The clinic’s positive environment and dedicated staff made us feel confident in our decision.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLvS2E-jTV6hPrw3yGd4ZqvNbbs2M-up7crvEW0kqhswBbE5w=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/NDCLK7VYLcgZVBnA8"
    },
    {
      "id": 88,
      "center_name": "chennai",
      "clinic_location": "chennai",
      "city": "Chennai",
      "rating": 4.9,
      "name": "Sathiya Sathiya",
      "reviews": "We wanted the best IUI center near me with experienced doctors and advanced facilities. From consultation to treatment, everything was handled professionally. The team was kind, and the treatment plan was personalized to our needs.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJo2e2MAmX1H1FJQABYQZ1i-b6FRw_EKJaAvoACCmyWWcV4zw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/b1CGoUBEr8zYh8n48"
    },
    {
      "id": 89,
      "center_name": "chennai",
      "clinic_location": "chennai",
      "city": "Chennai",
      "rating": 4.9,
      "name": "Prabakaran Subu",
      "reviews": "Going for IUI treatment was a big step for us. We were anxious, but the doctor’s patience and expertise reassured us. The entire process was smooth, and we felt supported every step of the way.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXEPSsP0Q0XC6oMGLvN8hCvE0nDycn7zUjtHEkf4pdeaDVhmNCAww=w56-h56-p-rp-mo-ba3-br100",
      "review_link": "https://maps.app.goo.gl/h1ZmAxvok1WrEVkVA"
    },
    {
      "id": 90,
      "center_name": "chennai",
      "clinic_location": "chennai",
      "city": "Chennai",
      "rating": 4.9,
      "name": "Anagha C H",
      "reviews": "Finding the right IUI specialist near me was overwhelming, but this clinic made the process easy. The doctor took time to explain everything clearly. The care, expertise, and support we received made all the difference in our journey.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVqDxvnlhhmAPnmg-9RQxhL81lvpv7Kpc7PLz94ieMK-XHOtVU=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/irFpmGjYgJMW2shk9"
    },
    {
      "id": 91,
      "center_name": "chennai",
      "clinic_location": "chennai",
      "city": "Chennai",
      "rating": 4.9,
      "name": "Ramya Hema",
      "reviews": "We searched for an IUI specialist near me and found a clinic with compassionate doctors. Dr. Maheswari D was thorough in her approach, making the process stress-free. The personalized care and attention made all the difference.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLc9tciEnzPQYNW8S6PE0cZknC0VOkdU8fni7ObnZUhaFNfPQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/kdbseUNiA6L4CWd19"
    },
    {
      "id": 92,
      "center_name": "Pune",
      "clinic_location": "wakad",
      "city": "Pune",
      "rating": 4.9,
      "name": "Chaya Wakode",
      "reviews": "We were searching for an IUI specialist near me and found an amazing clinic. The doctor explained the entire process clearly, and the treatment was well-organized. We felt reassured throughout our journey.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKVJtamRUa1agKMUWeb6wdczv9mZb5AbaU39OWhvXcwwHgv-A=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/CmUcWzptkmPnuud18"
    },
    {
      "id": 93,
      "center_name": "Pune",
      "clinic_location": "wakad",
      "city": "Pune",
      "rating": 4.9,
      "name": "Madhushri Marathe",
      "reviews": "Starting IUI treatment was nerve-wracking, but the clinic’s team was incredibly supportive. They answered all our questions and made sure we were comfortable at every stage.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIhSb6z3B0AGx7aX4bm_mOOxCehqBAZr8kjM69RLu89oo1tcw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/zDwf7DRiyxoeSTJEA"
    },
    {
      "id": 94,
      "center_name": "Pune",
      "clinic_location": "kharadi",
      "city": "Pune",
      "rating": 4.7,
      "name": "Nandini Idohole",
      "reviews": "Finding an IUI specialist near me who truly cares was difficult, but this clinic stood out. The doctor took the time to understand our concerns and gave us a treatment plan that worked for us.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKHPCqfIBD5pMFJ323h5h9zeeQKyHDb554QGVW1v4HD32MJSA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/8eoVDFctXWJFTsif9"
    },
    {
      "id": 95,
      "center_name": "Pune",
      "clinic_location": "kharadi",
      "city": "Pune",
      "rating": 4.7,
      "name": "Pratik Kedari",
      "reviews": "We were unsure about IUI treatment, but after consulting with the doctor, we felt confident. The entire process was smooth, and the staff ensured we were comfortable at every step.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUwHJlwOH2qkb29xIs9c2ZrB2wljts1-rQvu9M0kqktprMgy65sbQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/8W8vgFELigaRDXB36"
    },
    {
      "id": 96,
      "center_name": "Pune",
      "clinic_location": "kharadi",
      "city": "Pune",
      "rating": 4.9,
      "name": "Rajendra Mothe",
      "reviews": "The doctor’s expertise and the clinic’s advanced approach made our IUI treatment experience stress-free. We felt hopeful and supported throughout.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWMEgexjQ1nlN0b41jXtSpkfz-QhplE6yNT7VJpMO4sYBuyNPHddQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/voRZhsvRfhm6wi75A"
    },
    {
      "id": 97,
      "center_name": "wakad",
      "clinic_location": "wakad",
      "city": "Wakad",
      "rating": 4.9,
      "name": "Hakam Joping",
      "reviews": "After struggling to conceive, we decided to try IUI treatment. The clinic provided excellent care, and the doctor’s detailed guidance made the process easier.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXRjLT-R6qCFuGyPMOZcCQ7kxQvhxvnGkJGmrFuyhSJ1i_r0j17=w56-h56-p-rp-mo-ba3-br100",
      "review_link": "https://maps.app.goo.gl/aFrJaB6xbMGcAXGP7"
    },
    {
      "id": 98,
      "center_name": "wakad",
      "clinic_location": "wakad",
      "city": "Wakad",
      "rating": 4.9,
      "name": "Chaya Wakode",
      "reviews": "A reliable IUI specialist near me was hard to find, but this clinic exceeded our expectations. The treatment was well-planned, and the doctor’s expertise was evident throughout.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKVJtamRUa1agKMUWeb6wdczv9mZb5AbaU39OWhvXcwwHgv-A=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/CmUcWzptkmPnuud18"
    },
    {
      "id": 99,
      "center_name": "wakad",
      "clinic_location": "wakad",
      "city": "Wakad",
      "rating": 4.9,
      "name": "Prashant Ranpise",
      "reviews": "IUI treatment can be overwhelming, but the doctor’s patience and knowledge helped us stay positive. The clinic was well-equipped, making the entire process smooth.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLN65_iIhU58mC4IiavMhi1yjAP9JawZWNYW7BX5Xw6cqzIbQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/ABvEL4Vx7Mdv8AQz8"
    },
    {
      "id": 100,
      "center_name": "wakad",
      "clinic_location": "wakad",
      "city": "Wakad",
      "rating": 4.9,
      "name": "Bandu Jadhav",
      "reviews": "We needed an experienced IUI specialist near me, and this clinic was the best choice. The doctor listened to our concerns and provided the best possible treatment.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLs8xDDb12GsezxYTTeR_6zMb1R6GhZ_HfwVOhlGRgrsmEWdis=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/28Go4X42nUWZFsHN7"
    },
    {
      "id": 101,
      "center_name": "wakad",
      "clinic_location": "wakad",
      "city": "Wakad",
      "rating": 4.9,
      "name": "Vikas Lande",
      "reviews": "Dr. Nilesh Unmesh Balkawade was incredibly thorough in explaining the process. His expertise and support made our IUI treatment experience positive and stress-free.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKS2ViCy5luxjh7hVQkFGgJ_XvhIATTImbRmN3eA6EglkBCIA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/6DNnRhxJ5Xy8uDmd6"
    },
    {
      "id": 102,
      "center_name": "kharadi",
      "clinic_location": "kharadi",
      "city": "Kharadi",
      "rating": 4.7,
      "name": "Nandini Idohole",
      "reviews": "We had many doubts about IUI treatment, but the doctor answered all our questions patiently. The process was smooth, and we felt well taken care of.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKHPCqfIBD5pMFJ323h5h9zeeQKyHDb554QGVW1v4HD32MJSA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/8eoVDFctXWJFTsif9"
    },
    {
      "id": 103,
      "center_name": "kharadi",
      "clinic_location": "kharadi",
      "city": "Kharadi",
      "rating": 5,
      "name": "Govind Bhambre",
      "reviews": "The search for a trustworthy IUI specialist near me ended here. The clinic had a professional and caring approach, making us feel valued and respected.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVmC9X6B1_EZOcn3N3TQcYc58_T-ewRGf5wQRyswFkZWXGV4ngW=w56-h56-p-rp-mo-ba3-br100",
      "review_link": "https://maps.app.goo.gl/8SPGYmRzEMwRoQuX6"
    },
    {
      "id": 104,
      "center_name": "kharadi",
      "clinic_location": "kharadi",
      "city": "Kharadi",
      "rating": 4.7,
      "name": "Pitta Kishore",
      "reviews": "The team at this clinic made our IUI treatment journey easier. Their constant support and detailed guidance helped us stay hopeful and confident.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIXC9Px-Oj7wwJavLnULLhvpeT9CWXwjDgS6epPKsO0Z_FS8w=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/X6LhCAJ6je5tMdY59"
    },
    {
      "id": 105,
      "center_name": "kharadi",
      "clinic_location": "kharadi",
      "city": "Kharadi",
      "rating": 4.7,
      "name": "Nadia Shaikh",
      "reviews": "Dr. Sneha Govind Balki provided exceptional care during our IUI treatment. She was patient, kind, and made sure we were comfortable at every stage.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLkUaxmLiYqeDs8gbqRL8Oei2eTGXv5gJ4EgJe7FHnumUH6OYQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/VmJGRjP3hsAggU16A"
    },
    {
      "id": 106,
      "center_name": "kharadi",
      "clinic_location": "kharadi",
      "city": "Kharadi",
      "rating": 4.7,
      "name": "Poornima Bagul",
      "reviews": "We were looking for an IUI specialist near me who understood our concerns, and we found exactly that. The doctor was supportive, and the entire process was well-managed.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVsKQM0UExDdTG1PCW0WgcWBtawSQaeyNZX9jlkcIv0x6yKu3g=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/YHLn7n4omWaFoBMU9"
    },
    {
      "id": 107,
      "center_name": "nashik",
      "clinic_location": "nashik",
      "city": "Nashik",
      "rating": 5,
      "name": "Vaishali Dumbare",
      "reviews": "Finding the best IUI centre near me was challenging, but this clinic exceeded our expectations. The staff was supportive, and the treatment process was well-structured. We felt comfortable and hopeful throughout.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocId70JrDMx2FBCnvRSbVZIR2xkp72hMRQIx9B_MiOa6CiZBfA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/4kpTffhGZdcuvfzGA"
    },
    {
      "id": 108,
      "center_name": "nashik",
      "clinic_location": "nashik",
      "city": "Nashik",
      "rating": 5,
      "name": "Usha Patil",
      "reviews": "We were anxious about starting our IUI journey, but this clinic made the process smooth. The doctor was experienced, the staff was kind, and we felt reassured at every step. Definitely the best IUI centre near me!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKd6EMo8mfe_nwnc21KCZEyjyUTAEJkj7uzQmqzHdBUJ3kqGw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/BQpA7ZhxLHFivaTw8"
    },
    {
      "id": 109,
      "center_name": "nashik",
      "clinic_location": "nashik",
      "city": "Nashik",
      "rating": 5,
      "name": "Kavitaa Tailor",
      "reviews": "Choosing the best IUI centre near me was crucial for us. The clinic had advanced technology, a caring team, and an expert doctor who made sure we understood the entire process. A truly positive experience!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLB4g4D5uVY1V0iEdLRtKyM-3LhfjB8MRHCN463oSxT6z8LLQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/8R4BQPLgqgPAP1736"
    },
    {
      "id": 110,
      "center_name": "nashik",
      "clinic_location": "nashik",
      "city": "Nashik",
      "rating": 5,
      "name": "Ganesh Karwal",
      "reviews": "Dr. Pallavi Yuvraj Untwal was compassionate and knowledgeable. She guided us with patience, answering all our questions. The clinic provided top-notch care, making our IUI treatment stress-free.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJ68lcyDouptfG9QliSEPkNQcnaqSgtl22AKCSxqOGTV_fWpQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/qCRMabjGYj8BCPt59"
    },
    {
      "id": 111,
      "center_name": "nashik",
      "clinic_location": "nashik",
      "city": "Nashik",
      "rating": 5,
      "name": "Mahesh Belekar",
      "reviews": "We searched for the best IUI centre near me and found a clinic that offered both expertise and emotional support. The doctor’s approach was reassuring, and the entire experience was handled with great professionalism.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJGybbY0m6SV_1ztoFm6JrwRtxrI518iZGVVxqQmeE8X0xz=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/nRSAEvdAn47dfL828"
    },
    {
      "id": 112,
      "center_name": "raipur",
      "clinic_location": "raipur",
      "city": "Raipur",
      "rating": 5,
      "name": "Bharat Pahuja",
      "reviews": "Finding an IUI specialist near me who is both experienced and compassionate was not easy. This clinic provided excellent care, and the doctor explained the entire process in detail. We felt supported throughout our journey.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJcQsAWo41KeW8Uq7SI18ytKZNgvGF6bua3uiqzVq2d-nrprg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/Ap4DHNNqNFF3de9p8"
    },
    {
      "id": 113,
      "center_name": "raipur",
      "clinic_location": "raipur",
      "city": "Raipur",
      "rating": 5,
      "name": "Tanushree Barua",
      "reviews": "We wanted the best IUI center near me with advanced facilities and expert doctors. The clinic exceeded our expectations with personalized care and a smooth treatment process. We felt hopeful again!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUtTTGVmqP73WWZ5MI01q8SV7jYGyGBlnn-ANITA5kFj7olbFbe=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/3APNiiqWCYJCQi579"
    },
    {
      "id": 114,
      "center_name": "raipur",
      "clinic_location": "raipur",
      "city": "Raipur",
      "rating": 5,
      "name": "Komal Dewangan",
      "reviews": "Starting IUI treatment was a big decision, but this clinic made everything easy. The staff was friendly, and the doctor provided the right guidance. We truly felt like we were in safe hands.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXh2W7mJ0GXx9C6OcuCCZM5rVVOowYiZbJ5bH4BHkMQm0odSxtrDA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/5g7weWndF8spoivY9"
    },
    {
      "id": 115,
      "center_name": "raipur",
      "clinic_location": "raipur",
      "city": "Raipur",
      "rating": 5,
      "name": "Kumar Gaurav",
      "reviews": "Dr. Pratibha Tiwary was kind and thorough in explaining our treatment plan. She answered all our concerns and gave us confidence in our IUI treatment journey. The care we received was exceptional.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWnkuovrXnz1mjY51aCuYlk9bY9m-ikCtwQVDkQIm5hbwmeRya7=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/d9ZW1eKKzSV9BxaY6"
    },
    {
      "id": 116,
      "center_name": "raipur",
      "clinic_location": "raipur",
      "city": "Raipur",
      "rating": 5,
      "name": "Deepali",
      "reviews": "Searching for the best IUI center near me led us to this clinic, and we are grateful. The process was stress-free, the staff was supportive, and the doctor’s expertise made all the difference. Highly recommended!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJNdu8TzMyiCufxfy050DJ4Ahbj5ZFbwQnKiLELXgCFMg2Xlw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/WjhFNwQUAyF96tFs5"
    },
    {
      "id": 117,
      "center_name": "vadodara",
      "clinic_location": "vadodara",
      "city": "Vadodara",
      "rating": 4.9,
      "name": "Suresh Rathod",
      "reviews": "Finding the best IUI center in Vadodara was overwhelming, but this clinic stood out. From consultation to treatment, everything was handled with care. The staff was supportive, and the experience was smooth and stress-free.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIIAsTF_7X4PRqAp7QGO2k--v3InJzvgxvFaSfjJxHya7VImA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/WFzNBZkSXGWHvo4T9"
    },
    {
      "id": 118,
      "center_name": "vadodara",
      "clinic_location": "vadodara",
      "city": "Vadodara",
      "rating": 4.9,
      "name": "Neetu Vardhan",
      "reviews": "We were worried about the IUI treatment cost, but this clinic provided transparent pricing and excellent care. The doctor explained every step, and we felt reassured throughout the process.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXlrPuozneVBtTmL_K0Ahehxn196w8KCLREkH6mAWiXWqztIKo=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/2t7c8fhss29oT7BNA"
    },
    {
      "id": 119,
      "center_name": "vadodara",
      "clinic_location": "vadodara",
      "city": "Vadodara",
      "rating": 4.9,
      "name": "Aneeta Patel",
      "reviews": "Choosing the best IUI center in Vadodara was crucial for us, and we’re so glad we found this place. The doctors and staff were professional, and the treatment was tailored to our needs. A truly positive experience!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWyTc0wnx3xYEQJf0sO9XHuZeV_aU0DmSnJqnX0lyq1XXW_7GY=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/93js5Buyji79GZ3J6"
    },
    {
      "id": 120,
      "center_name": "vadodara",
      "clinic_location": "vadodara",
      "city": "Vadodara",
      "rating": 4.9,
      "name": "Santosh Luste",
      "reviews": "Dr. Baxi Sushma was incredibly patient and knowledgeable. She guided us through the process, making sure we were comfortable. The clinic offered the right balance of expertise and compassion, making our journey easier.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJBhEoHMcqaSzUpYCnWjSMsGy3G6HnQIvL3JSdyiRQ6FkNxwQ=w56-h56-p-rp-mo-ba3-br100",
      "review_link": "https://maps.app.goo.gl/jekG5b9XYda1eKJ16"
    },
    {
      "id": 121,
      "center_name": "vadodara",
      "clinic_location": "vadodara",
      "city": "Vadodara",
      "rating": 4.9,
      "name": "Suresh Rathod",
      "reviews": "We were unsure about the IUI treatment cost, but the clinic provided clear details and options. The quality of care we received made every step worth it. The doctor’s expertise gave us hope and confidence.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIIAsTF_7X4PRqAp7QGO2k--v3InJzvgxvFaSfjJxHya7VImA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/aycBs9hiZbk76zjp9"
    },
    {
      "id": 122,
      "center_name": "ranchi",
      "clinic_location": "ranchi",
      "city": "Ranchi",
      "rating": 4.9,
      "name": "Rahul Singh",
      "reviews": "Finding the best IUI center near me was stressful, but this clinic made everything easy. From the first consultation to the treatment, the team was kind and professional. We felt reassured and well taken care of throughout the process.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLHQ4AeF9R3sXJ6knv6QVhYF8IXVCm40yodoycGfpWVT_4ZEw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/11PRU8AFdhdqiVMa9"
    },
    {
      "id": 123,
      "center_name": "ranchi",
      "clinic_location": "ranchi",
      "city": "Ranchi",
      "rating": 4.9,
      "name": "Ashish Sharma",
      "reviews": "We were nervous about starting IUI treatment, but the doctor explained everything with patience. The procedure was smooth, and the staff was always supportive. A great experience that gave us hope!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjV392MCna1evNE97BAL2Arm19DZyBqWv-YcBrWHwY-ruNGt5hjGww=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/pPdVbPXQHjQikzAc7"
    },
    {
      "id": 124,
      "center_name": "ranchi",
      "clinic_location": "ranchi",
      "city": "Ranchi",
      "rating": 4.9,
      "name": "Shiva Yadav",
      "reviews": "After searching for the best IUI center near me, we found this amazing clinic. The doctors were experienced, and the facilities were top-notch. The entire journey was handled with care and professionalism.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLTL_laLgwHEnsxuK2ogZeW3rSRivwey2_GcSc1nA8xipJAHQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/YvhAPRFnXAnmZTxG7"
    },
    {
      "id": 125,
      "center_name": "ranchi",
      "clinic_location": "ranchi",
      "city": "Ranchi",
      "rating": 4.9,
      "name": "Rohini",
      "reviews": "Dr. Musunuru Rajani was incredible! She answered all our concerns and guided us through our IUI treatment step by step. Her expertise and compassionate approach made us feel confident in our journey.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVSIR3Vk2EgPPIPtzUdJUT9zuJuPW8YOGc1K2myh9un8p6CR49I=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/25YW4TKyZYhdEv8b9"
    },
    {
      "id": 126,
      "center_name": "ranchi",
      "clinic_location": "ranchi",
      "city": "Ranchi",
      "rating": 4.9,
      "name": "Rahul Singh",
      "reviews": "We wanted an expert for IUI treatment, and this clinic exceeded our expectations. The process was well-organized, and the doctor’s support made all the difference. We truly felt like we were in good hands.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLHQ4AeF9R3sXJ6knv6QVhYF8IXVCm40yodoycGfpWVT_4ZEw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/whdkLHy86bK6XrHV9"
    },
    {
      "id": 127,
      "null": null,
      "review_link": "https://maps.app.goo.gl/Z2iVz6dH84txkRag7",
      "center_name": "india",
      "clinic_location": "Hyderabad",
      "rating": 5,
      "reviews": "\"I recently visited Oasis for my prenatal care, and I must say, I was thoroughly impressed. Dr. MeeraJindal and Tejashree was extremely knowledgeable, kind, and took the time to answer all my questions.",
      "name": "Sai Singh",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWjG9wHNIcDGy4OTnfpUpwQWolqPfV3q2B4LCY8NsAJGa91ZUjXcQ=w60-h60-p-rp-mo-br100"
    },
    {
      "id": 128,
      "null": null,
      "review_link": "https://maps.app.goo.gl/5fX9pg83f7pnbLV66",
      "center_name": "india",
      "clinic_location": "Bengaluru",
      "rating": 4.9,
      "reviews": "Thanks to oasis for all the support. We have gone through a lot before coming here. Since when we started taking treatment from oasis hospital really given me a positive vibe.We are really happy to share this review.",
      "name": "Manikeshwari K",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKLdL9IMtSrXEVOoE-h0Vwf9ghAlLbVbkdoF1nn8GV6koWaS5Jv=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 129,
      "null": null,
      "review_link": "https://maps.app.goo.gl/VmJGRjP3hsAggU16A",
      "center_name": "india",
      "clinic_location": "Pune",
      "rating": 4.9,
      "reviews": "Excellent facilities and compassionate care at OASIS Hospital, making a significant difference in our journey to parenthood. THANKS TO COMPLETE OASIS TEAM.",
      "name": "Rajendra Mothe",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWMEgexjQ1nlN0b41jXtSpkfz-QhplE6yNT7VJpMO4sYBuyNPHddQ=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 130,
      "null": null,
      "review_link": "https://maps.app.goo.gl/NDCLK7VYLcgZVBnA8",
      "center_name": "india",
      "clinic_location": "chennai",
      "rating": 4.9,
      "reviews": "Thanks for Nova IVF and thank you so much for dr.ajantha mam .she is very friendly and ans all enquiries.she give good confident for pts .all staff are pt guidance well.",
      "name": "Sathiya Sathiya",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJo2e2MAmX1H1FJQABYQZ1i-b6FRw_EKJaAvoACCmyWWcV4zw=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 131,
      "null": null,
      "review_link": "https://maps.app.goo.gl/WFzNBZkSXGWHvo4T9",
      "center_name": "india",
      "clinic_location": "Vadodara",
      "rating": 5,
      "reviews": "We want to Jalgaon manmad but we didn't find what we came for but in nashik oasis fertility dr pallavi dr Meenakshi centre manager pre full staff support guide a lot are hopes and dreams came true all credit to dr pallavi highly recommend",
      "name": "Usha Patil",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKd6EMo8mfe_nwnc21KCZEyjyUTAEJkj7uzQmqzHdBUJ3kqGw=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 132,
      "center_name": "kakinada",
      "clinic_location": "kakinada",
      "city": "kakinada",
      "rating": 5,
      "name": "Srikanth Sri",
      "reviews": "Finding the best IUI center near me was a challenge, but once we stepped into this clinic, we knew we made the right choice. The team was professional, the environment was comforting, and the entire process was well-managed from start to finish.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJV0CbscHMoi8u1hCrFTgJe-jBE18h7cyY7tZAba3nO6IjjY96z=w56-h56-p-rp-mo-br100",
      "review_link": null
    },
    {
      "id": 133,
      "center_name": "kakinada",
      "clinic_location": "kakinada",
      "city": "kakinada",
      "rating": 5,
      "name": "Madhusudan Naidu Pathipati",
      "reviews": "We wanted to consult a top IUI specialist for expert guidance. The doctor explained everything clearly, making us feel confident. The treatment process was smooth, and the staff ensured we felt supported throughout our journey.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJJqeZyvFm1fC9s5Wy35_EqRjG5jAHujaRg7SDrqIg-u9dblw=w56-h56-p-rp-mo-br100",
      "review_link": null
    },
    {
      "id": 134,
      "center_name": "kakinada",
      "clinic_location": "kakinada",
      "city": "kakinada",
      "rating": 5,
      "name": "Vasanth Appapogu",
      "reviews": "Choosing the best IUI center near me felt overwhelming at first, but this clinic stood out with its advanced facilities and compassionate care. From consultation to treatment, everything was handled with expertise and kindness.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKqcRkT75CGLsu44io3o73xFfGLta_9biNXnBfuaOYo0LszSw=w56-h56-p-rp-mo-br100",
      "review_link": null
    },
    {
      "id": 135,
      "center_name": "kakinada",
      "clinic_location": "kakinada",
      "city": "kakinada",
      "rating": 4.9,
      "name": "Gowthami Gowni",
      "reviews": "Dr. Ramineedi was incredibly patient and understanding. As a top IUI specialist, she provided clear guidance and reassurance throughout our treatment. The care we received here gave us renewed hope in our journey.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWIfG_ONIOQqjrx7OExlhmR__iP_5KVoJ6Jw9tZC2dbJzJqMbCu=w56-h56-p-rp-mo-br100",
      "review_link": null
    },
    {
      "id": 136,
      "center_name": "tolichowki",
      "clinic_location": "tolichowki",
      "city": "tolichowki",
      "rating": 4.9,
      "name": "Aaliya Sheikh",
      "reviews": "The emotional toll of infertility was heavy. Dr. Keerthana V made us feel seen and understood. Her approach to IUI treatment was both scientific and compassionate, creating a truly positive experience.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVaryLP-qAbGfBXYjLtdaQi58njQC1hz2T-zOdhn2tyV9pptEe2Tw=w56-h56-p-rp-mo-br100",
      "review_link": null
    },
    {
      "id": 137,
      "center_name": "tolichowki",
      "clinic_location": "tolichowki",
      "city": "tolichowki",
      "rating": 4.9,
      "name": "Lekhan Naga",
      "reviews": "The road to parenthood was difficult. The specialist’s warm approach and deep knowledge of IUI treatment made a huge difference. We felt genuinely cared for.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocI5mA_d95nPa0fHlv9ncDPrqwECj6JM2LGpP8wrGZ7B46HdXA=w56-h56-p-rp-mo-br100",
      "review_link": null
    },
    {
      "id": 138,
      "center_name": "tolichowki",
      "clinic_location": "tolichowki",
      "city": "tolichowki",
      "rating": 4.9,
      "name": "Kaniki Shekar",
      "reviews": "When natural conception didn’t work, IUI seemed like the next step. The doctor’s approach was detailed, reassuring, and well-planned. We couldn’t have asked for better guidance.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLipXYIcAPExyu_HZLcNechNkVeyScHkmBmOeiAm_22ckyP=w56-h56-p-rp-mo-br100",
      "review_link": null
    },
    {
      "id": 139,
      "center_name": "tolichowki",
      "clinic_location": "tolichowki",
      "city": "tolichowki",
      "rating": 4.9,
      "name": "Lakshmi Sarada",
      "reviews": "We struggled with fertility treatments before, but this IUI experience was different. The specialist’s dedication and step-by-step guidance gave us confidence and peace of mind.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJdA5mFa1KosgA1bVPQqhMPUKmCwtPMxHRivQiwfUSABq-FTA=w56-h56-p-rp-mo-br100",
      "review_link": null
    },
    {
      "id": 140,
      "center_name": "bhubaneswar",
      "clinic_location": "bhubaneswar",
      "city": "bhubaneswar",
      "rating": 5,
      "name": "Bharat Pahuja",
      "reviews": "Finding an IUI specialist near me who is both experienced and compassionate was not easy. This clinic provided excellent care, and the doctor explained the entire process in detail. We felt supported throughout our journey.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJcQsAWo41KeW8Uq7SI18ytKZNgvGF6bua3uiqzVq2d-nrprg=w56-h56-p-rp-mo-br100",
      "review_link": null
    },
    {
      "id": 141,
      "center_name": "bhubaneswar",
      "clinic_location": "bhubaneswar",
      "city": "bhubaneswar",
      "rating": 5,
      "name": "Tanushree Barua",
      "reviews": "We wanted the best IUI center near me with advanced facilities and expert doctors. The clinic exceeded our expectations with personalized care and a smooth treatment process. We felt hopeful again!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUtTTGVmqP73WWZ5MI01q8SV7jYGyGBlnn-ANITA5kFj7olbFbe=w56-h56-p-rp-mo-br100",
      "review_link": null
    },
    {
      "id": 142,
      "center_name": "bhubaneswar",
      "clinic_location": "bhubaneswar",
      "city": "bhubaneswar",
      "rating": 5,
      "name": "Komal Dewangan",
      "reviews": "Starting IUI treatment was a big decision, but this clinic made everything easy. The staff was friendly, and the doctor provided the right guidance. We truly felt like we were in safe hands.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXh2W7mJ0GXx9C6OcuCCZM5rVVOowYiZbJ5bH4BHkMQm0odSxtrDA=w56-h56-p-rp-mo-br100",
      "review_link": null
    },
    {
      "id": 143,
      "center_name": "bhubaneswar",
      "clinic_location": "bhubaneswar",
      "city": "bhubaneswar",
      "rating": 5,
      "name": "Kumar Gaurav",
      "reviews": "Dr. Prasanta Kumar Nayak was kind and thorough in explaining our treatment plan. She answered all our concerns and gave us confidence in our IUI treatment journey. The care we received was exceptional.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWnkuovrXnz1mjY51aCuYlk9bY9m-ikCtwQVDkQIm5hbwmeRya7=w56-h56-p-rp-mo-br100",
      "review_link": null
    },
    {
      "id": 144,
      "center_name": "bhubaneswar",
      "clinic_location": "bhubaneswar",
      "city": "bhubaneswar",
      "rating": 5,
      "name": "Deepali",
      "reviews": "Searching for the best IUI center near me led us to this clinic, and we are grateful. The process was stress-free, the staff was supportive, and the doctor’s expertise made all the difference. Highly recommended!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJNdu8TzMyiCufxfy050DJ4Ahbj5ZFbwQnKiLELXgCFMg2Xlw=w56-h56-p-rp-mo-br100",
      "review_link": null
    }
    
  ]

  export default iuiReview;