const ivfReview = [
    {
      "id": 1,
      "center_name": "hyderabad",
      "clinic_location": "banjara hills",
      "city": "Hyderabad",
      "rating": 4.9,
      "name": "Renuka",
      "reviews": "Dr. Durga G. Rao at this IVF center in Hyderabad made our journey smooth. The staff was caring, and the cost was transparent. Best IVF doctor in Hyderabad!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXKUFBmfsV0gy5GjWQIRbizGSvVqX9KLPoI-Sp8cgi1M-hMSqZK=w56-h56-p-rp-mo-br100",
      "review_link": "maps.app.goo.gl/FiYnims6MH4tzcTY8",
      "null": null
    },
    {
      "id": 2,
      "center_name": "hyderabad",
      "clinic_location": "gachibowli",
      "city": "Hyderabad",
      "rating": 4.9,
      "name": "Navaneeth Rao",
      "reviews": "Highly recommend this IVF center in Hyderabad. The team explained everything clearly, and the results were amazing. Best IVF centre in Hyderabad!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKTpj2xInuEhuIBMrsrTvhQl5zOMoPsdj4vFgl-ECbUlzqHBw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/KkY24v8QbYyt4VnZA",
      "null": null
    },
    {
      "id": 3,
      "center_name": "hyderabad",
      "clinic_location": "dilshuknagar",
      "city": "Hyderabad",
      "rating": 4.9,
      "name": "Bhagya Sri",
      "reviews": "We struggled for years, but Dr. Parinaaz Parhar gave us hope. The IVF cost in Hyderabad was reasonable, and the care was exceptional.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXxcZmAmCFy_irK8Z1G0-QesngWzOJ33cVvJT6EVsVQ6-nVSXMfwA=w45-h45-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/n8KpemCkvFN7Y9k3A",
      "null": null
    },
    {
      "id": 4,
      "center_name": "hyderabad",
      "clinic_location": "miyapur",
      "city": "Hyderabad",
      "rating": 4.9,
      "name": "Medak Rakhi",
      "reviews": "The best IVF doctor in Hyderabad! Dr. Srinivasa Varalakshmi Yakasiri and her team were supportive, and the process was stress-free.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVV6V5enWzRgdT42hx5f3KnIzzi148ovO1Z-HYC4ceTmcPIO2m5=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/FSjVCbewBBfNc3zf8",
      "null": null
    },
    {
      "id": 5,
      "center_name": "banjara hills",
      "clinic_location": "banjara hills",
      "city": "Banjara Hills",
      "rating": 4.9,
      "name": "Nandini Gubba",
      "reviews": "If you're looking for IVF in Hyderabad, this is the place. The staff is kind, and the treatment was successful. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJMuILKHklgB4gAnuofZ3OFrlF5r6F62uoxVfw2kQ6gOhbHBQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/tv5K6FriEap2rhTm9",
      "null": null
    },
    {
      "id": 6,
      "center_name": "banjara hills",
      "clinic_location": "banjara hills",
      "city": "Banjara Hills",
      "rating": 4.9,
      "name": "Someswara Rao Teppala",
      "reviews": "Our experience with IVF in Hyderabad was fantastic. The doctors were knowledgeable, and the center is well-equipped. Best IVF centre!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUJmn2AuP2RSwVcihiMoFp_9WWguCP8ohhesBFo8Lz6Z9_bOubg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/YPhvr9tDQt1r3QHY6",
      "null": null
    },
    {
      "id": 7,
      "center_name": "banjara hills",
      "clinic_location": "banjara hills",
      "city": "Banjara Hills",
      "rating": 4.9,
      "name": "Upender Gali",
      "reviews": "Dr. Durga G. Rao is the best IVF doctor in Hyderabad. The team was patient, and the results were beyond our expectations.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWO_ovn6diLSrr6x5dBxi2C0fQOPIb_YbUt_5346gm7mlcnGqZl=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/db2WbMTNoZPqfFwr6",
      "null": null
    },
    {
      "id": 8,
      "center_name": "banjara hills",
      "clinic_location": "banjara hills",
      "city": "Banjara Hills",
      "rating": 4.9,
      "name": "Umeera Khan",
      "reviews": "The IVF cost in Hyderabad at this center is worth every penny. The staff is friendly, and the doctors are highly skilled. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJw9BIkRtWFE1BgAZ3cpMMABe2DE3xKeuyiPaURgKPjAxJNSg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/qTw1hgdX28eoXHUV8",
      "null": null
    },
    {
      "id": 9,
      "center_name": "gachibowli",
      "clinic_location": "gachibowli",
      "city": "Gachibowli",
      "rating": 4.9,
      "name": "Aaliya Sheikh",
      "reviews": "We found the best IVF center in Hyderabad. The process was smooth, and the staff made us feel at ease. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVaryLP-qAbGfBXYjLtdaQi58njQC1hz2T-zOdhn2tyV9pptEe2Tw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/Fqz3rDx5KXfc9JwQ9",
      "null": null
    },
    {
      "id": 10,
      "center_name": "gachibowli",
      "clinic_location": "gachibowli",
      "city": "Gachibowli",
      "rating": 4.9,
      "name": "Lekhan Naga",
      "reviews": "Dr. Avanthi Vellala Rao is amazing! The IVF center in Hyderabad has a warm environment, and the treatment was successful. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocI5mA_d95nPa0fHlv9ncDPrqwECj6JM2LGpP8wrGZ7B46HdXA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/G6QhNE1UQXxgcB3U6",
      "null": null
    },
    {
      "id": 11,
      "center_name": "gachibowli",
      "clinic_location": "gachibowli",
      "city": "Gachibowli",
      "rating": 4.9,
      "name": "Kaniki Shekar",
      "reviews": "The best IVF doctor in Hyderabad! Dr. Avanthi Vellala explained everything clearly, and the staff was very supportive.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLipXYIcAPExyu_HZLcNechNkVeyScHkmBmOeiAm_22ckyP=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/bvEnx187Q2SrYtKQ6",
      "null": null
    },
    {
      "id": 12,
      "center_name": "gachibowli",
      "clinic_location": "gachibowli",
      "city": "Gachibowli",
      "rating": 4.9,
      "name": "Lakshmi Sarada",
      "reviews": "We are so grateful to this IVF center in Hyderabad. The cost was transparent, and the care was exceptional. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJdA5mFa1KosgA1bVPQqhMPUKmCwtPMxHRivQiwfUSABq-FTA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/kSfUiEEEjcFmBFUV6",
      "null": null
    },
    {
      "id": 13,
      "center_name": "dilshuknagar",
      "clinic_location": "dilshuknagar",
      "city": "Dilshuknagar",
      "rating": 4.9,
      "name": "Rajitha",
      "reviews": "Dr. A Tejashree is the best IVF doctor in Hyderabad. The team was caring, and the results were amazing.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocI-ED_3STq78dZjSdAzoq1vnownZ1JgknPExw26IZZOOgDXKg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/FNwAv61a6Km2EcMq5",
      "null": null
    },
    {
      "id": 14,
      "center_name": "dilshuknagar",
      "clinic_location": "dilshuknagar",
      "city": "Dilshuknagar",
      "rating": 4.9,
      "name": "Tulasi Vinnu",
      "reviews": "The IVF cost in Hyderabad at this center is reasonable, and the service is top-notch. We are so happy with the results!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKMgoqB8uNKk6gRD6JQQRM7zTcjdcSkoRyWOcr7OLaj99sCWA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/2yKfm4asq1GMpuQ48",
      "null": null
    },
    {
      "id": 15,
      "center_name": "dilshuknagar",
      "clinic_location": "dilshuknagar",
      "city": "Dilshuknagar",
      "rating": 4.9,
      "name": "Gavvala Srinivas",
      "reviews": "This is the best IVF centre in Hyderabad. The staff is friendly, and the doctors are highly experienced. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKMMs_ocH0w9LsaqPdWN8jhI8p_cL8N7XyTbuApk4gmDKAX3w=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/eM7rKDYKWNjtqt7QA",
      "null": null
    },
    {
      "id": 16,
      "center_name": "dilshuknagar",
      "clinic_location": "dilshuknagar",
      "city": "Dilshuknagar",
      "rating": 4.9,
      "name": "Raj Bag",
      "reviews": "Dr. Sai Manasa Darla made our IVF journey in Hyderabad stress-free. The team was supportive, and the results were perfect.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKkOoaWijfwPb_UnLGYnnxWOys14Zk64Gb8HUMIbMOc1ZRtAg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/SwN1D3yx7r4rXJff9",
      "null": null
    },
    {
      "id": 17,
      "center_name": "secunderabad",
      "clinic_location": "secunderabad",
      "city": "Secunderabad",
      "rating": 4.9,
      "name": "Harikrishna Boini",
      "reviews": "We had a great experience with IVF in Hyderabad. The doctors were knowledgeable, and the staff was very caring. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKGrowOzdEQfyrpQbX110iIpuIj3ZedlLv3scrurCilai75rg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/sCsGYqhc3PbV1mMFA",
      "null": null
    },
    {
      "id": 18,
      "center_name": "secunderabad",
      "clinic_location": "secunderabad",
      "city": "Secunderabad",
      "rating": 5,
      "name": "Hardik Mehta",
      "reviews": "The best IVF doctor in Hyderabad! Dr. Parninaaz and her team were amazing. The cost was transparent, and the care was excellent.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIwXRLZFbaSm3J8S-48YPzvt53xlgzY5A92PAcC2aCsLTUREg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/tF6XYUPFmQMhqkNm7",
      "null": null
    },
    {
      "id": 19,
      "center_name": "secunderabad",
      "clinic_location": "secunderabad",
      "city": "Secunderabad",
      "rating": 4.9,
      "name": "Syamala Ramu",
      "reviews": "This IVF center in Hyderabad is the best. The staff is kind, and the treatment was successful. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWqVoW6QXFyc0tGSejh39vXYp61SqVH_6WDt4eyRZtgSKQsgzaI=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/E84o9Kqd3QkEf9t48",
      "null": null
    },
    {
      "id": 20,
      "center_name": "secunderabad",
      "clinic_location": "secunderabad",
      "city": "Secunderabad",
      "rating": 4.9,
      "name": "Gangula",
      "reviews": "We are so happy with our experience at this IVF center in Hyderabad. The doctors were skilled, and the results were beyond our expectations.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIxFQjkN6BhNFYe0QUZJ3zTa7ZmPMsRAINfGQTu7xcwSxrpDQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/UiPcXYQ3BJDdakGY8",
      "null": null
    },
    {
      "id": 21,
      "center_name": "miyapur",
      "clinic_location": "miyapur",
      "city": "Miyapur",
      "rating": 4.9,
      "name": "Hari Brahmeswara Reddy Kovvuri",
      "reviews": "Dr. Srinivasa Varalakshmi Yakasiri is the best IVF doctor in Hyderabad. The center is well-maintained, and the staff made us feel comfortable throughout the process.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXcTSSs5eIUWMrOMgpjPQgSAkx5Y58IRPVDhVGSsm-ivm3er8q-=w56-h56-p-rp-mo-ba4-br100",
      "review_link": "https://maps.app.goo.gl/cdpjmbj96MQyrvcz8",
      "null": null
    },
    {
      "id": 22,
      "center_name": "miyapur",
      "clinic_location": "miyapur",
      "city": "Miyapur",
      "rating": 4.9,
      "name": "Anusha Bontha",
      "reviews": "We are so grateful to this IVF center in Hyderabad. The cost was transparent, and the care was exceptional. Highly recommend for IVF treatment!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocK2Rg4DEzwEbqSfXri9_umr7sx-BVW6l21kua4STaSYwKZ_0w=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/SHcvrFj7MTpBhA377",
      "null": null
    },
    {
      "id": 23,
      "center_name": "miyapur",
      "clinic_location": "miyapur",
      "city": "Miyapur",
      "rating": 4.9,
      "name": "Navaneeth Rao",
      "reviews": "The best IVF centre in Hyderabad! Dr. Srinivasa Varalakshmi Yakasiri and her team were supportive, and the results were amazing.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKTpj2xInuEhuIBMrsrTvhQl5zOMoPsdj4vFgl-ECbUlzqHBw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/KkY24v8QbYyt4VnZA",
      "null": null
    },
    {
      "id": 24,
      "center_name": "miyapur",
      "clinic_location": "miyapur",
      "city": "Miyapur",
      "rating": 4.9,
      "name": "Shirley George",
      "reviews": "If you're looking for IVF in Hyderabad, this is the place. The staff is kind, and the treatment was successful. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUmLGJZ9Lzd-qILCt4gdLl6M7xL743q4BoiVJhHy09GdE2BH5bhWQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/ryH671hiknmvZdNS9",
      "null": null
    },
    {
      "id": 25,
      "center_name": "kompally",
      "clinic_location": "kompally",
      "city": "Kompally",
      "rating": 5,
      "name": "Jarupula Vanditha",
      "reviews": "Our experience with IVF in Hyderabad was fantastic. The doctors were knowledgeable, and the center is well-equipped. Best IVF centre!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjViJX9oQ9qwkdEpIgLUMQ4ij65aQ6lwQSMRhJynRW6r85umOgYR=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/5XGSjn2JekPiXf1S9",
      "null": null
    },
    {
      "id": 26,
      "center_name": "kompally",
      "clinic_location": "kompally",
      "city": "Kompally",
      "rating": 5,
      "name": "Pavan Thati",
      "reviews": "Dr. Meera Jindal is the best IVF doctor in Hyderabad. The team was patient, and the results were beyond our expectations.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVus2iJKmiCvpXBr9o8gWNDBDgCd26yTQUy2bpoq7HlY2-V_fSyew=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/MHprTCVZ5sEhLkm76",
      "null": null
    },
    {
      "id": 27,
      "center_name": "kompally",
      "clinic_location": "kompally",
      "city": "Kompally",
      "rating": 5,
      "name": "Hrishabh",
      "reviews": "The IVF cost in Hyderabad at this center is worth every penny. The staff is friendly, and the doctors are highly skilled. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVNVV8YharMC-nxNhyzS1reAODVxyPKdkaQmUMe1BJmIkESXL5y=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/v2ARN6EZeyvDzeaS6",
      "null": null
    },
    {
      "id": 28,
      "center_name": "kompally",
      "clinic_location": "kompally",
      "city": "Kompally",
      "rating": null,
      "name": "kalyan kumar",
      "reviews": "We found the best IVF center in Hyderabad. The process was smooth, and the staff made us feel at ease. Highly recommend!",
      "profile_picture": null,
      "review_link": null,
      "null": null
    },
    {
      "id": 29,
      "center_name": "uppal",
      "clinic_location": "uppal",
      "city": "Uppal",
      "rating": 4.9,
      "name": "Vinod Kumar Aitipamula",
      "reviews": "Dr. M V D Aruna is amazing! The IVF center in Hyderabad has a warm environment, and the treatment was successful. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjV2-uEOl8kSmfKYgIcKfQDjXQ9uSsoTPUNyd2SCVD6MCHDzPvE=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/g9iymmWGKKB9HD978",
      "null": null
    },
    {
      "id": 30,
      "center_name": "uppal",
      "clinic_location": "uppal",
      "city": "Uppal",
      "rating": 4.9,
      "name": "Krishnamohan Kunthipuram",
      "reviews": "The best IVF doctor in Hyderabad! Dr. M V D Aruna explained everything clearly, and the staff was very supportive.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLiolgNvVj1OjALIn9i0ZQ6G8RTjIKW9ALllx05hkq7Vt81Iw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/61GKBJD7ZUZt28vj6",
      "null": null
    },
    {
      "id": 31,
      "center_name": "uppal",
      "clinic_location": "uppal",
      "city": "Uppal",
      "rating": 4.9,
      "name": "Poolapalli Chinnari",
      "reviews": "Dr. Dr. M V D Aruna is the best IVF doctor in Warangal. The fertility treatment was explained clearly, and the staff was very supportive. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJkDO8eKvwFMo64UNbC13KvZJ7FtnhcUqe8-Ec1dGOFL1u9kg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/Md42qHzCqEk5QJYr6",
      "null": null
    },
    {
      "id": 32,
      "center_name": "uppal",
      "clinic_location": "uppal",
      "city": "Uppal",
      "rating": 4.9,
      "name": "Navya Jonnadhula",
      "reviews": "We had a great experience with IVF in Warangal. The team was caring, and the results were amazing. Best fertility treatment center!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJVH0o6Q7Cer9XUrE4tcn5Qub7iiuuSZTZB4ThDlG79K7Cm9w=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/gzc5AwhSNhy4EH6bA",
      "null": null
    },
    {
      "id": 33,
      "center_name": "Hanamkonda",
      "clinic_location": "Hanamkonda",
      "city": "Hanamkonda",
      "rating": 4.7,
      "name": "Bala Krishna",
      "reviews": "If you're looking for fertility treatment or IVF in Warangal, this is the place. The doctors are skilled, and the staff is very kind.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjW-lE6tP5h5DoUMNrfC71mwbGnpJgyi4zMAPW8bhO_5UXs7WJI7=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/3SfsZZWQmH8rbitX9",
      "null": null
    },
    {
      "id": 34,
      "center_name": "Hanamkonda",
      "clinic_location": "Hanamkonda",
      "city": "Hanamkonda",
      "rating": 4.7,
      "name": "Bhukya Suresh Nayak",
      "reviews": "The best IVF doctor in Warangal! Dr. Jalagam Kavya Rao and her team made our journey smooth. The fertility treatment was successful, and we are so grateful.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjX8V10HJUFGi3sKhRr8GZJFL7yQ5b_I-_T5zCh5pVmRbTlQheaK7A=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/qM9qGkrjsHXfZr6w6",
      "null": null
    },
    {
      "id": 35,
      "center_name": "Hanamkonda",
      "clinic_location": "Hanamkonda",
      "city": "Hanamkonda",
      "rating": 4.7,
      "name": "Sangeetha Rani Yanamanagandla",
      "reviews": "Dr. Jalagam Kavya Rao is truly the best IVF doctor in Warangal. Her expertise in fertility treatment gave us hope, and the staff was incredibly supportive. Highly recommend for IVF in Warangal!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocK4QoOqj4nR9OoqWFQ2JGaYCS8sBVgUaAzdlSkBnElXfdj_VQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/YokoGx2CFdgkh6oJ9",
      "null": null
    },
    {
      "id": 36,
      "center_name": "Hanamkonda",
      "clinic_location": "Hanamkonda",
      "city": "Hanamkonda",
      "rating": 4.9,
      "name": "Sathish Yadav Sathish",
      "reviews": "Our journey with IVF in Warangal was smooth, thanks to Dr. Kavya Rao. She explained every step of the fertility treatment clearly, and the results were beyond our expectations.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJrkoJZO2hgnJOnGH3W6H4qVNdyaJRd0FI_tMnEtSYvPS06Sw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/PwxwSTwERz6Y38CT9",
      "null": null
    },
    {
      "id": 37,
      "center_name": "karimnagar",
      "clinic_location": "karimnagar",
      "city": "Karimnagar",
      "rating": 5,
      "name": "Bandi Mamatha",
      "reviews": "Dr. Jigna Tamagond is amazing! The IVF centre in Karimnagar provided transparent details about IVF cost, and the staff was very supportive. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJ0aM72z0UR7aQxic9hXu43CGrS2P17Yevbx9t8jyCNOKXK0g=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/zJBSZApFpMpoEvEZ8",
      "null": null
    },
    {
      "id": 38,
      "center_name": "karimnagar",
      "clinic_location": "karimnagar",
      "city": "Karimnagar",
      "rating": 5,
      "name": "Prashanth Chinni",
      "reviews": "We had a great experience at this IVF centre in Karimnagar. The cost was reasonable, and the team made us feel comfortable throughout the process. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUnL9m4u_IdKx-SjsRaD9t9aLs4I4V7xEux7VQEudM6a-oKJ88=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/z5usb7bNuseNho5c7",
      "null": null
    },
    {
      "id": 39,
      "center_name": "karimnagar",
      "clinic_location": "karimnagar",
      "city": "Karimnagar",
      "rating": 5,
      "name": "Akula Sandhyarani",
      "reviews": "If you're looking for IVF in Karimnagar, Dr. Jigna Tamagond is the best. She explained everything clearly, and the IVF cost was worth it. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLHPl6BT1EvaonPBmfn_oq04Sy8iH2l_s2mw3m1Lb7KpjfEzg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/dx41QVeLs4JJVWz39",
      "null": null
    },
    {
      "id": 40,
      "center_name": "karimnagar",
      "clinic_location": "karimnagar",
      "city": "Karimnagar",
      "rating": 5,
      "name": "Harish",
      "reviews": "The IVF centre in Karimnagar is excellent. The staff is caring, and the cost was transparent. We are so happy with the results. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVxY-cxqfttf7WPYFG_uJ8lu3TQbQB_-JSKsUndoyS1XJuT0c7QzA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/tMmQgvUidoeS592EA",
      "null": null
    },
    {
      "id": 41,
      "center_name": "vijayawada",
      "clinic_location": "vijayawada",
      "city": "Vijayawada",
      "rating": 4.9,
      "name": "Kotha Mrudula",
      "reviews": "Dr. Venkata Sujatha Vellanki is the best! The IVF clinic in Vijayawada provided excellent care, and the staff was very supportive. Highly recommend for IVF treatment!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLS4kVGN-UiZSIqZuilE5y1fDAGhft6zZE3ljp97H-pCjHoIw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/RPhq128i2Q6VkjQM7",
      "null": null
    },
    {
      "id": 42,
      "center_name": "vijayawada",
      "clinic_location": "vijayawada",
      "city": "Vijayawada",
      "rating": 4.9,
      "name": "Dubba Sunil",
      "reviews": "We had a wonderful experience at this IVF center in Vijayawada. The team was caring, and the process was smooth. Thank you for making it stress-free!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXK7SlU5nnePsEC1y0A3OVEOXdDU8tmkZgWZaTIckV_kuicKLW-aw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/MPVe5xJu78HGZy8k9",
      "null": null
    },
    {
      "id": 43,
      "center_name": "vijayawada",
      "clinic_location": "vijayawada",
      "city": "Vijayawada",
      "rating": 4.9,
      "name": "Siva Sai Kumar",
      "reviews": "If you're looking for the best IVF center in Vijayawada, Dr. Venkata Sujatha Vellanki is the one. She explained everything clearly, and the results were amazing.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWtp1oTxQQ8CEo7iHXuLWYftp7gaVcnadSE6ZJGm0_-lnd3oq8=w56-h56-p-rp-mo-br100",
      "review_link": "https://www.google.com/maps/contrib/118068252448421908233/reviews",
      "null": null
    },
    {
      "id": 44,
      "center_name": "vijayawada",
      "clinic_location": "vijayawada",
      "city": "Vijayawada",
      "rating": 4.9,
      "name": "Sandhya Dodla",
      "reviews": "The IVF clinic in Vijayawada is top-notch. The staff is friendly, and the treatment was successful. Highly recommend for anyone seeking IVF care!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIY9Q890869J-EYPfc6nECGVJYyM_vv3-5MbwVBQmhr3U-wSg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/GCs6j4WoX1aocB4B9",
      "null": null
    },
    {
      "id": 45,
      "center_name": "visakhapatnam",
      "clinic_location": "visakhapatnam",
      "city": "Visakhapatnam",
      "rating": 4.9,
      "name": "Gummala Darababu",
      "reviews": "Struggling with fertility issues? Dr. Radhika Potluri at the best IVF centre in Vizag changed our lives. The staff was caring, and the treatment was successful. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIw-OEqRYyxaLo_9pYPfh8swi9WPIFIyhOZEEMHV8or7mQ5dw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/p6Bpv6NSXUbPn2NLA",
      "null": null
    },
    {
      "id": 46,
      "center_name": "visakhapatnam",
      "clinic_location": "visakhapatnam",
      "city": "Visakhapatnam",
      "rating": 4.9,
      "name": "Yarra Vandana",
      "reviews": "We were lost until we found this IVF hospital in Vizag. The team was supportive, and the process was smooth. Dr. Radhika Potluri’s expertise made all the difference. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjW0JKaRLeyFha_xEjU0t_iMrAIbM7hjcsyTjGm05rIbuyAe8WEi=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/oH6ejG5h24DvrQjn7",
      "null": null
    },
    {
      "id": 47,
      "center_name": "visakhapatnam",
      "clinic_location": "visakhapatnam",
      "city": "Visakhapatnam",
      "rating": 4.9,
      "name": "Kamesh Royistan",
      "reviews": "Looking for IVF hospitals near me in Vizag? This is the place! The staff is kind, and the treatment was effective. We are so happy with the results. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXVxWnMxcUPeERYbdEhnyB80CdoL5VWAPl6l4mUEWU2lNNpu5YlRw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/USfR1dzt28yvS8Ui6",
      "null": null
    },
    {
      "id": 48,
      "center_name": "visakhapatnam",
      "clinic_location": "visakhapatnam",
      "city": "Visakhapatnam",
      "rating": 4.9,
      "name": "Kasina Suguna",
      "reviews": "Our journey with IVF in Vizag was amazing. The best IVF centre with skilled doctors and a caring team. The treatment was successful, and we are forever grateful.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKVU_MH5HafV6WV_d8NSN3pq-84_n6rfEFvc1E8jOzn94F7GA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/yewzRut981Sx4pM29",
      "null": null
    },
    {
      "id": 49,
      "center_name": "guntur",
      "clinic_location": "guntur",
      "city": "Guntur",
      "rating": 5,
      "name": "Istikhar",
      "reviews": "After years of struggling, Dr. Ramya Vicharapu gave us hope. Her expertise in fertility treatment and IVF was incredible. The staff was supportive, and we finally have our little one. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKCWeHIGgh6u9isiJ-NQnop8nEDZ-uATxwK2auiAavA-xAFeA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/dbt3NggMRuAmeU3E8",
      "null": null
    },
    {
      "id": 50,
      "center_name": "guntur",
      "clinic_location": "guntur",
      "city": "Guntur",
      "rating": 5,
      "name": "Nisha Shaikh",
      "reviews": "We were losing hope until we met Dr. Ramya Vicharapu. Her guidance during our IVF journey was exceptional. The fertility treatment was successful, and we are forever grateful.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJ2kEqiIdh8rbDHtQFVw1sXlFMS_OeQ3Z6_wGxrTK_ocqsjRw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/NPugY1sfeCPDAMyDA",
      "null": null
    },
    {
      "id": 51,
      "center_name": "guntur",
      "clinic_location": "guntur",
      "city": "Guntur",
      "rating": 5,
      "name": "Lovaraju Madda",
      "reviews": "Facing fertility issues? This IVF center changed our lives. The team was caring, and the treatment was tailored to our needs. We are now proud parents. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUZI3FpS9kIPN5mnf-cyTgE9GOLHptYPDOY5j1PTvMVg4eSlWA2=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/b7CoCo2DVwQmb7zg9",
      "null": null
    },
    {
      "id": 52,
      "center_name": "guntur",
      "clinic_location": "guntur",
      "city": "Guntur",
      "rating": 5,
      "name": "Gudimella Vasavi Sujatha",
      "reviews": "Our IVF journey was smooth and stress-free, thanks to the amazing team. The fertility treatment was effective, and the staff made us feel at ease. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIlB6BtSJ16RCzhV6MGbbrm1TrMBHTllesABNkkrIxxpQ_lKw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/JFfTsyGXy197u8Ha8",
      "null": null
    },
    {
      "id": 53,
      "center_name": "ongole",
      "clinic_location": "ongole",
      "city": "Ongole",
      "rating": 5,
      "name": "Sulthan Sk",
      "reviews": "After years of trying, Dr. Deepika Boppana at Ongole IVF Centre made our dream come true. Her expertise and the team’s support were incredible. Highly recommend for fertility treatment!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLjZJura-jRNkBjDYtXp1YUE0vU01Hqjn9t7gDxhSxLfwJVig=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/5gxg9jhvZUVndE9u7",
      "null": null
    },
    {
      "id": 54,
      "center_name": "ongole",
      "clinic_location": "ongole",
      "city": "Ongole",
      "rating": 5,
      "name": "Vijaya Lakshmi",
      "reviews": "We were struggling until we found Ongole IVF Centres. Dr. Deepika Boppana explained everything clearly, and the treatment was successful. Thank you for giving us hope!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKdz6BWe7V3GkKVStPW-d_McqgFYt4Fe2jtYYCgfM1Nc8yyoA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/ELBL5kCx343uagUi6",
      "null": null
    },
    {
      "id": 55,
      "center_name": "ongole",
      "clinic_location": "ongole",
      "city": "Ongole",
      "rating": 5,
      "name": "Urvashi",
      "reviews": "Facing fertility challenges? Ongole IVF Centres is the place to go. The staff was caring, and the process was smooth. We are now proud parents. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLqy1Ifrbz-sMhVQ8jOV4kLzs1tNvsuny5lgHISMeAbIUXX-Q=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/9J6xMgepSdi2XnhLA",
      "null": null
    },
    {
      "id": 56,
      "center_name": "ongole",
      "clinic_location": "ongole",
      "city": "Ongole",
      "rating": 5,
      "name": "Dhana Lakshmi",
      "reviews": "Our IVF journey at Ongole IVF Centres was amazing. The team was supportive, and the treatment was effective. We are so grateful for this life-changing experience.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJIMyV12fRC8r4XgsCh3cALjnSJhfHob20kfJyKcpUvkeKPWg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/j5YAuPGUroDXw1Mo6",
      "null": null
    },
    {
      "id": 57,
      "center_name": "tirupati",
      "clinic_location": "tirupati",
      "city": "Tirupati",
      "rating": 4.9,
      "name": "Usha Nallapareddy",
      "reviews": "Dr. Nadikattu Saranya Lakshmi at the best hospital in Tirupati for IVF made our journey stress-free. Her expertise and the team’s care gave us our little one. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJ-2YAQLOakjWHiTvytLyANuo1b41YunzzHTMrutSR1y3VpsA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/DSiWfWy5L3tmGMqq8",
      "null": null
    },
    {
      "id": 58,
      "center_name": "tirupati",
      "clinic_location": "tirupati",
      "city": "Tirupati",
      "rating": 4.9,
      "name": "Divya K",
      "reviews": "After years of struggle, Dr. Pallavi Tapala at this IVF clinic in Tirupati gave us hope. Her guidance and the staff’s support made all the difference. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIh0moEZM9Jfu-Z4pO03_ThQlFggGbXHvOcPLakeZC9tYHPXRKX=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/gRSzm4A9Rj2cezxN8",
      "null": null
    },
    {
      "id": 59,
      "center_name": "tirupati",
      "clinic_location": "tirupati",
      "city": "Tirupati",
      "rating": 4.9,
      "name": "Kiran Teja",
      "reviews": "Dr. Ramya Vicharapu is a blessing! The best hospital in Tirupati for IVF with a team that feels like family. The treatment was smooth, and the results were life-changing.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVPlg-FteaQdQLj_woNS4OS9UmcwW0BH6Ig5oUkRKVf0mxRFrk=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/bzKkEFuiFREWCTdT7",
      "null": null
    },
    {
      "id": 60,
      "center_name": "tirupati",
      "clinic_location": "tirupati",
      "city": "Tirupati",
      "rating": 4.9,
      "name": "Sarah",
      "reviews": "Dr. Vijayalakshmi D at this IVF clinic in Tirupati is amazing. The staff was supportive, and the treatment was effective. We are now proud parents. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJAdbdA0Uy_bqDtq5ML-IhsWBaRNNWPXGaeh-_P5cOOprdX6w=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/caJh5ncRsAuu8iuZA",
      "null": null
    },
    {
      "id": 61,
      "center_name": "kurnool",
      "clinic_location": "kurnool",
      "city": "Kurnool",
      "rating": 5,
      "name": "Srikanth Sri",
      "reviews": "Dr. Vijayalakshmi D at the best IVF hospital in Kurnool changed our lives. Her expertise and the team’s care made our IVF treatment successful. Forever grateful!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJV0CbscHMoi8u1hCrFTgJe-jBE18h7cyY7tZAba3nO6IjjY96z=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/TUi1nzMLia3mfQhE7",
      "null": null
    },
    {
      "id": 62,
      "center_name": "kurnool",
      "clinic_location": "kurnool",
      "city": "Kurnool",
      "rating": 5,
      "name": "Madhusudan Naidu Pathipati",
      "reviews": "After years of disappointment, we found hope at Kurnool IVF Centres. The staff was supportive, and the treatment was effective. We are now proud parents. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJJqeZyvFm1fC9s5Wy35_EqRjG5jAHujaRg7SDrqIg-u9dblw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/YSQ4a76euJ2Gsofz9",
      "null": null
    },
    {
      "id": 63,
      "center_name": "kurnool",
      "clinic_location": "kurnool",
      "city": "Kurnool",
      "rating": 5,
      "name": "Vasanth Appapogu",
      "reviews": "Dr. Vijayalakshmi D is amazing! The best IVF hospital in Kurnool with a team that feels like family. The process was smooth, and the results were life-changing.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKqcRkT75CGLsu44io3o73xFfGLta_9biNXnBfuaOYo0LszSw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/dUE997hEDGkD257g8",
      "null": null
    },
    {
      "id": 64,
      "center_name": "kurnool",
      "clinic_location": "kurnool",
      "city": "Kurnool",
      "rating": 4.9,
      "name": "Gowthami Gowni",
      "reviews": "Looking for IVF treatment in Kurnool? This is the place! The staff was kind, and the care was exceptional. Our dream of parenthood finally came true. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWIfG_ONIOQqjrx7OExlhmR__iP_5KVoJ6Jw9tZC2dbJzJqMbCu=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/TbUNdQyBTN7nhkaJ8",
      "null": null
    },
    {
      "id": 65,
      "center_name": "Bengaluru",
      "clinic_location": "HSR",
      "city": "Bengaluru",
      "rating": 4.9,
      "name": "Haribabu Tata",
      "reviews": "After years of struggle, Dr. Prinka Bajaj gave us hope. The best IVF clinic in Bangalore with a supportive team. We are now proud parents. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJGNAbwp_l1bJcENwg1tG9Y5Nr4ZlHjFneKljumt5OLUJc2zwQ=w56-h56-p-rp-mo-ba3-br100",
      "review_link": "https://maps.app.goo.gl/kVN2F8wwg7fYwNfT9",
      "null": "best ivf center near me"
    },
    {
      "id": 66,
      "center_name": "Bengaluru",
      "clinic_location": "HSR",
      "city": "Bengaluru",
      "rating": 4.9,
      "name": "Sumon Laskar",
      "reviews": "Struggling with fertility issues? Dr. Prinka Bajaj at the best IVF centre near me is the answer. Her expertise and the team’s care changed our lives.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKbxVIncIvGGMCydXmsvR9VqGexuzyNOF1Y93CWTT8Fd2B3RA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/DPJ64qNRhFqKev47A",
      "null": "best ivf center near me"
    },
    {
      "id": 67,
      "center_name": "Bengaluru",
      "clinic_location": "banashankari",
      "city": "Bengaluru",
      "rating": 4.9,
      "name": "Navitham",
      "reviews": "Dr. Shalini M A at the best IVF centre in Bangalore made our dream come true. Her expertise and the team’s care were exceptional. Highly recommend for IVF treatment!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUlN4o3xhycMK7e6eFmN5xobNFkvbzkMTttXJ8JZhIXa5DUcgw5lA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/iqaeLBBEv51Rkx7n8",
      "null": "best ivf center near me"
    },
    {
      "id": 68,
      "center_name": "Bengaluru",
      "clinic_location": "hebbal",
      "city": "Bengaluru",
      "rating": 4.9,
      "name": "Shireen Shariff",
      "reviews": "Looking for IVF treatment in Bangalore? Dr. Shalini M Ais the best. Her guidance and the staff’s support made all the difference. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLllXJDL20xxHz7E6T4CDm2Qpt1HFt9_b8e87_z55bbvr1a0A=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/rtq7m8fHqJfLSKif7",
      "null": "best ivf center near me"
    },
    {
      "id": 69,
      "center_name": "HSR",
      "clinic_location": "HSR",
      "city": "Hsr",
      "rating": 4.9,
      "name": "Haribabu Tata",
      "reviews": "Doctor Rekha is amazing! The best IVF center near me with a team that feels like family. The process was smooth, and the results were life-changing.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJGNAbwp_l1bJcENwg1tG9Y5Nr4ZlHjFneKljumt5OLUJc2zwQ=w56-h56-p-rp-mo-ba3-br100",
      "review_link": "https://maps.app.goo.gl/kVN2F8wwg7fYwNfT9",
      "null": "best ivf center near me"
    },
    {
      "id": 70,
      "center_name": "HSR",
      "clinic_location": "HSR",
      "city": "Hsr",
      "rating": 4.9,
      "name": "Neha Vernekar",
      "reviews": "Dr. Shalini M A is a blessing! The best IVF centre in Bangalore with a caring team. The treatment was effective, and we are forever grateful.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKvLgY_zs3qj6XLcl9D39IsKTCux5Cr7wEPyw8_1OTBs1fDrw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/7XysC3Z1eyLz4qvk7",
      "null": "best ivf center near me"
    },
    {
      "id": 71,
      "center_name": "HSR",
      "clinic_location": "HSR",
      "city": "Hsr",
      "rating": 4.9,
      "name": "Manikeshwari K",
      "reviews": "After multiple failed attempts, Dr. Shweta .G. Sonwalkar at the best IVF clinic near me turned things around. Her care and expertise gave us our little miracle.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKLdL9IMtSrXEVOoE-h0Vwf9ghAlLbVbkdoF1nn8GV6koWaS5Jv=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/5fX9pg83f7pnbLV66",
      "null": "best ivf center near me"
    },
    {
      "id": 72,
      "center_name": "HSR",
      "clinic_location": "HSR",
      "city": "Hsr",
      "rating": 4.9,
      "name": "Sumon Laskar",
      "reviews": "Dr. Shalini M A is amazing! The best IVF clinic near me with a team that truly cares. The process was smooth, and the results were life-changing.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKbxVIncIvGGMCydXmsvR9VqGexuzyNOF1Y93CWTT8Fd2B3RA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/DPJ64qNRhFqKev47A",
      "null": "best ivf center near me"
    },
    {
      "id": 73,
      "center_name": "banashankari",
      "clinic_location": "banashankari",
      "city": "Banashankari",
      "rating": 5,
      "name": "Rs Gowda",
      "reviews": "Dr. Prinka Bajaj is a miracle worker! The best IVF clinic in Bangalore with a team that feels like family. The results were beyond our expectations.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWeCA_Yq1YVje93tm3C0gPCkQLNBzI7XSOh-0PwClZGNCDKvCv6=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/tb1WxbCLsZ7Ry1qH7",
      "null": "best ivf center near me"
    },
    {
      "id": 74,
      "center_name": "banashankari",
      "clinic_location": "banashankari",
      "city": "Banashankari",
      "rating": 5,
      "name": "Sadhana Naik",
      "reviews": "Dr. Prinka Bajaj is incredible! The best IVF treatment in Bangalore with a supportive team. We are now a happy family. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXLGXX-iwMC3GAmK59zMIMask5-no_AzPbK4l4lh7lfslBJWs61=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/iRX5vx4RQy2xc4Qr9",
      "null": "best ivf center near me"
    },
    {
      "id": 75,
      "center_name": "banashankari",
      "clinic_location": "banashankari",
      "city": "Banashankari",
      "rating": 5,
      "name": "Mohana Priya",
      "reviews": "Doctor made our IVF journey stress-free. The best IVF center in Bangalore with a supportive team. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJMWp-PjgnCuIPjbMcPPH-AT_S_dW_kXb3SKW3SVtvWkBR6eg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/3QhsmwetyKdRna8a6",
      "null": "best ivf center near me"
    },
    {
      "id": 76,
      "center_name": "banashankari",
      "clinic_location": "banashankari",
      "city": "Banashankari",
      "rating": 4.9,
      "name": "Sumon Laskar",
      "reviews": "Dr. Bajaj is incredible! The best IVF treatment in Bangalore with a caring team. We are now proud parents. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKbxVIncIvGGMCydXmsvR9VqGexuzyNOF1Y93CWTT8Fd2B3RA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/DPJ64qNRhFqKev47A",
      "null": "best ivf center near me"
    },
    {
      "id": 77,
      "center_name": "hebbal",
      "clinic_location": "hebbal",
      "city": "Hebbal",
      "rating": 4.9,
      "name": "Sanjeeva Rayudu",
      "reviews": "They made our IVF journey stress-free. The best IVF center in Bangalore with a team that truly cares. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJuObpZTQRri922E7s74N32Y5rj4p-lhuLeKYgIV4c35jJLpg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/TJvLpiAsJuXGVmgD6",
      "null": "best ivf center near me"
    },
    {
      "id": 78,
      "center_name": "hebbal",
      "clinic_location": "hebbal",
      "city": "Hebbal",
      "rating": 4.9,
      "name": "Navitham",
      "reviews": "Dr. Shalini gave us hope when we had none. The best IVF center in Bangalore with a caring team. We are now proud parents. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUlN4o3xhycMK7e6eFmN5xobNFkvbzkMTttXJ8JZhIXa5DUcgw5lA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/iqaeLBBEv51Rkx7n8",
      "null": "best ivf center near me"
    },
    {
      "id": 79,
      "center_name": "hebbal",
      "clinic_location": "hebbal",
      "city": "Hebbal",
      "rating": 4.9,
      "name": "Maheshwari Eswari Eswari",
      "reviews": "One of the best Doctors ! The IVF treatment in Bangalore was smooth, and the staff was supportive. We are forever grateful for this experience.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLlmJMaEy9zvaY_KbuNuSfZ8DMJ3JutTDLf-OoGC2TWuG-YIg=w56-h56-p-rp-mo-ba3-br100",
      "review_link": "https://maps.app.goo.gl/EvypeEDc6piPsXvm7",
      "null": "best ivf center near me"
    },
    {
      "id": 80,
      "center_name": "hebbal",
      "clinic_location": "hebbal",
      "city": "Hebbal",
      "rating": 4.9,
      "name": "Shireen Shariff",
      "reviews": "After years of disappointment, Dr. Shalini M A at the best IVF centre in Bangalore gave us hope. The treatment was successful, and we are now a happy family.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLllXJDL20xxHz7E6T4CDm2Qpt1HFt9_b8e87_z55bbvr1a0A=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/rtq7m8fHqJfLSKif7",
      "null": "best ivf center near me"
    },
    {
      "id": 81,
      "center_name": "hebbal",
      "clinic_location": "hebbal",
      "city": "Hebbal",
      "rating": 4.9,
      "name": "Navitham",
      "reviews": "Looking for the best IVF centre near me? Dr. Shalini M A is the answer. Her expertise and the team’s care made our dream come true.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUlN4o3xhycMK7e6eFmN5xobNFkvbzkMTttXJ8JZhIXa5DUcgw5lA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/wp3tDC7gv8cTLFT78",
      "null": "best ivf center near me"
    },
    {
      "id": 82,
      "center_name": "belagavi",
      "clinic_location": "belagavi",
      "city": "Belagavi",
      "rating": 5,
      "name": "Sudha Patil",
      "reviews": "After years of struggling, Dr. Shweta G. Sonwalkar at the best IVF center near me gave us hope. Her expertise and the team’s care made our dream come true. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocI1TuDkNb8oFapWusEkLel-5hC9n2XGu9__loaZ3keH8eme9w=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/2P4vyoUXe36x13Th9",
      "null": null
    },
    {
      "id": 83,
      "center_name": "belagavi",
      "clinic_location": "belagavi",
      "city": "Belagavi",
      "rating": 5,
      "name": "Adam",
      "reviews": "We were losing hope until we found this IVF center. The staff was supportive, and the process was smooth. We are now proud parents. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXoGIPncmjzMXAU2hregFSYNbdMQlcXOlOrAf4ETyfeWmAc3m-L=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/LwBDgVkyo5UWqRWu8",
      "null": null
    },
    {
      "id": 84,
      "center_name": "belagavi",
      "clinic_location": "belagavi",
      "city": "Belagavi",
      "rating": 5,
      "name": "Irfan Khan",
      "reviews": "Looking for the best IVF center near me? This is it! Dr. Shweta G. Sonwalkar and her team made our journey stress-free. The results were amazing. Highly recommend!",
      "profile_picture": null,
      "review_link": "https://maps.app.goo.gl/LwBDgVkyo5UWqRWu8",
      "null": null
    },
    {
      "id": 85,
      "center_name": "belagavi",
      "clinic_location": "belagavi",
      "city": "Belagavi",
      "rating": 4.9,
      "name": "Sharada Shiledar",
      "reviews": "Facing fertility challenges? This IVF center changed our lives. The team was caring, and the treatment was effective. We are now a happy family. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJVFU-oPlfCdh0sIYzesdWv7hoydWH6FNOp9tURs3AUByoC=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/j2QFgGtV4pyakmXa9",
      "null": null
    },
    {
      "id": 86,
      "center_name": "belagavi",
      "clinic_location": "belagavi",
      "city": "Belagavi",
      "rating": 5,
      "name": "Sharada Shiledar",
      "reviews": "Our IVF journey was smooth and stress-free, thanks to the amazing team at this center. The treatment was successful, and we are forever grateful. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJVFU-oPlfCdh0sIYzesdWv7hoydWH6FNOp9tURs3AUByoC=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/JpQ7TYu5xBrm2apC9",
      "null": null
    },
    {
      "id": 87,
      "center_name": "chennai",
      "clinic_location": "chennai",
      "city": "Chennai",
      "rating": 4.9,
      "name": "Karthikaarjun A",
      "reviews": "Dr. Hema at the best IVF centre in Chennai made our journey stress-free. The IVF cost was transparent, and the team’s care was exceptional. Highly recommend!\"",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLvS2E-jTV6hPrw3yGd4ZqvNbbs2M-up7crvEW0kqhswBbE5w=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/NDCLK7VYLcgZVBnA8",
      "null": null
    },
    {
      "id": 88,
      "center_name": "chennai",
      "clinic_location": "chennai",
      "city": "Chennai",
      "rating": 4.9,
      "name": "Sathiya Sathiya",
      "reviews": "After years of disappointment, we found hope at this IVF hospital in Chennai. The staff was supportive, and the treatment was effective. We are now proud parents.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJo2e2MAmX1H1FJQABYQZ1i-b6FRw_EKJaAvoACCmyWWcV4zw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/b1CGoUBEr8zYh8n48",
      "null": null
    },
    {
      "id": 89,
      "center_name": "chennai",
      "clinic_location": "chennai",
      "city": "Chennai",
      "rating": 4.9,
      "name": "Prabakaran Subu",
      "reviews": "Looking for IVF treatment in Chennai? Dr. Maheswari D is the best. Her guidance and the team’s support made all the difference. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXEPSsP0Q0XC6oMGLvN8hCvE0nDycn7zUjtHEkf4pdeaDVhmNCAww=w56-h56-p-rp-mo-ba3-br100",
      "review_link": "https://maps.app.goo.gl/h1ZmAxvok1WrEVkVA",
      "null": null
    },
    {
      "id": 90,
      "center_name": "chennai",
      "clinic_location": "chennai",
      "city": "Chennai",
      "rating": 4.9,
      "name": "Anagha C H",
      "reviews": "The best IVF center near me in Chennai provided excellent care. The IVF cost was reasonable, and the staff was kind. We are forever grateful for this experience.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVqDxvnlhhmAPnmg-9RQxhL81lvpv7Kpc7PLz94ieMK-XHOtVU=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/irFpmGjYgJMW2shk9",
      "null": null
    },
    {
      "id": 91,
      "center_name": "chennai",
      "clinic_location": "chennai",
      "city": "Chennai",
      "rating": 4.9,
      "name": "Ramya Hema",
      "reviews": "Facing fertility challenges? This IVF centre in Chennai changed our lives. Dr. Maheswari D and her team made the process smooth, and the results were amazing. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLc9tciEnzPQYNW8S6PE0cZknC0VOkdU8fni7ObnZUhaFNfPQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/kdbseUNiA6L4CWd19",
      "null": null
    },
    {
      "id": 92,
      "center_name": "Pune",
      "clinic_location": "wakad",
      "city": "Pune",
      "rating": 4.9,
      "name": "Chaya Wakode",
      "reviews": "Dr. Nilesh Unmesh Balkawade at the best IVF center in Pune made our dream come true. The IVF cost was transparent, and the team’s care was exceptional. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKVJtamRUa1agKMUWeb6wdczv9mZb5AbaU39OWhvXcwwHgv-A=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/CmUcWzptkmPnuud18",
      "null": null
    },
    {
      "id": 93,
      "center_name": "Pune",
      "clinic_location": "wakad",
      "city": "Pune",
      "rating": 4.9,
      "name": "Madhushri Marathe",
      "reviews": "After years of struggle, Dr. Sneha Govind Balki gave us hope. The best IVF center in Pune with a supportive team. We are now proud parents. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIhSb6z3B0AGx7aX4bm_mOOxCehqBAZr8kjM69RLu89oo1tcw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/zDwf7DRiyxoeSTJEA",
      "null": null
    },
    {
      "id": 94,
      "center_name": "Pune",
      "clinic_location": "kharadi",
      "city": "Pune",
      "rating": 4.7,
      "name": "Nandini Idohole",
      "reviews": "Looking for IVF treatment in Pune? This is the place! The staff was kind, and the IVF cost was reasonable. We are forever grateful for this experience.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKHPCqfIBD5pMFJ323h5h9zeeQKyHDb554QGVW1v4HD32MJSA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/8eoVDFctXWJFTsif9",
      "null": null
    },
    {
      "id": 95,
      "center_name": "Pune",
      "clinic_location": "kharadi",
      "city": "Pune",
      "rating": 4.7,
      "name": "Pratik Kedari",
      "reviews": "Facing fertility challenges? This IVF center in Pune changed our lives. Dr. Sneha Govind Balki and her team made the process stress-free. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUwHJlwOH2qkb29xIs9c2ZrB2wljts1-rQvu9M0kqktprMgy65sbQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/8W8vgFELigaRDXB36",
      "null": null
    },
    {
      "id": 96,
      "center_name": "Pune",
      "clinic_location": "kharadi",
      "city": "Pune",
      "rating": 4.9,
      "name": "Rajendra Mothe",
      "reviews": "Dr. Nilesh Unmesh Balkawade is amazing! The best IVF fertility center in Pune with a team that feels like family. The process was smooth, and the results were life-changing.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWMEgexjQ1nlN0b41jXtSpkfz-QhplE6yNT7VJpMO4sYBuyNPHddQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/voRZhsvRfhm6wi75A",
      "null": null
    },
    {
      "id": 97,
      "center_name": "wakad",
      "clinic_location": "wakad",
      "city": "Wakad",
      "rating": 4.9,
      "name": "Hakam Joping",
      "reviews": "The best IVF center near me in Pune provided excellent care. The IVF cost was transparent, and the staff was supportive. We are now a happy family. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXRjLT-R6qCFuGyPMOZcCQ7kxQvhxvnGkJGmrFuyhSJ1i_r0j17=w56-h56-p-rp-mo-ba3-br100",
      "review_link": "https://maps.app.goo.gl/aFrJaB6xbMGcAXGP7",
      "null": null
    },
    {
      "id": 98,
      "center_name": "wakad",
      "clinic_location": "wakad",
      "city": "Wakad",
      "rating": 4.9,
      "name": "Chaya Wakode",
      "reviews": "Dr. Nilesh Unmesh Balkawade is a blessing! The best IVF center in Pune with a caring team. The treatment was effective, and we are forever grateful.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKVJtamRUa1agKMUWeb6wdczv9mZb5AbaU39OWhvXcwwHgv-A=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/CmUcWzptkmPnuud18",
      "null": null
    },
    {
      "id": 99,
      "center_name": "wakad",
      "clinic_location": "wakad",
      "city": "Wakad",
      "rating": 4.9,
      "name": "Prashant Ranpise",
      "reviews": "Looking for IVF treatment in Pune? Dr. Nilesh Unmesh Balkawade is the best. His guidance and the team’s support made all the difference. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLN65_iIhU58mC4IiavMhi1yjAP9JawZWNYW7BX5Xw6cqzIbQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/ABvEL4Vx7Mdv8AQz8",
      "null": null
    },
    {
      "id": 100,
      "center_name": "wakad",
      "clinic_location": "wakad",
      "city": "Wakad",
      "rating": 4.9,
      "name": "Bandu Jadhav",
      "reviews": "The best IVF center in Pune with a supportive team. The IVF cost was reasonable, and the treatment was successful. We are now proud parents. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLs8xDDb12GsezxYTTeR_6zMb1R6GhZ_HfwVOhlGRgrsmEWdis=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/28Go4X42nUWZFsHN7",
      "null": null
    },
    {
      "id": 101,
      "center_name": "wakad",
      "clinic_location": "wakad",
      "city": "Wakad",
      "rating": 4.9,
      "name": "Vikas Lande",
      "reviews": "After years of disappointment, this IVF center in Pune gave us hope. The staff was supportive, and the treatment was effective. We are now a happy family.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKS2ViCy5luxjh7hVQkFGgJ_XvhIATTImbRmN3eA6EglkBCIA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/6DNnRhxJ5Xy8uDmd6",
      "null": null
    },
    {
      "id": 102,
      "center_name": "kharadi",
      "clinic_location": "kharadi",
      "city": "Kharadi",
      "rating": 4.7,
      "name": "Nandini Idohole",
      "reviews": "All doctors are incredible! The best IVF fertility center in Pune with a caring team. We are now proud parents. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKHPCqfIBD5pMFJ323h5h9zeeQKyHDb554QGVW1v4HD32MJSA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/8eoVDFctXWJFTsif9",
      "null": null
    },
    {
      "id": 103,
      "center_name": "kharadi",
      "clinic_location": "kharadi",
      "city": "Kharadi",
      "rating": 5,
      "name": "Govind Bhambre",
      "reviews": "Facing fertility issues? This IVF center in Pune is the answer. The staff was supportive, and the treatment was successful. We are forever grateful.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVmC9X6B1_EZOcn3N3TQcYc58_T-ewRGf5wQRyswFkZWXGV4ngW=w56-h56-p-rp-mo-ba3-br100",
      "review_link": "https://maps.app.goo.gl/8SPGYmRzEMwRoQuX6",
      "null": null
    },
    {
      "id": 104,
      "center_name": "kharadi",
      "clinic_location": "kharadi",
      "city": "Kharadi",
      "rating": 4.7,
      "name": "Pitta Kishore",
      "reviews": "Dr. Sneha Govind Balki made our IVF journey stress-free. The best IVF center in Pune with a team that truly cares. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIXC9Px-Oj7wwJavLnULLhvpeT9CWXwjDgS6epPKsO0Z_FS8w=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/X6LhCAJ6je5tMdY59",
      "null": null
    },
    {
      "id": 105,
      "center_name": "kharadi",
      "clinic_location": "kharadi",
      "city": "Kharadi",
      "rating": 4.7,
      "name": "Nadia Shaikh",
      "reviews": "Looking for the best IVF center near me in Pune? This is it! The staff was amazing, and the IVF cost was transparent. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLkUaxmLiYqeDs8gbqRL8Oei2eTGXv5gJ4EgJe7FHnumUH6OYQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/VmJGRjP3hsAggU16A",
      "null": null
    },
    {
      "id": 106,
      "center_name": "kharadi",
      "clinic_location": "kharadi",
      "city": "Kharadi",
      "rating": 4.7,
      "name": "Poornima Bagul",
      "reviews": "After multiple failed attempts, Dr. Sneha Govind Balki at the best IVF fertility center in Pune turned things around. Her care and expertise gave us our little miracle.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVsKQM0UExDdTG1PCW0WgcWBtawSQaeyNZX9jlkcIv0x6yKu3g=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/YHLn7n4omWaFoBMU9",
      "null": null
    },
    {
      "id": 107,
      "center_name": "nashik",
      "clinic_location": "nashik",
      "city": "Nashik",
      "rating": 5,
      "name": "Vaishali Dumbare",
      "reviews": "After years of struggle, Dr. Pallavi Yuvraj Untwal at the best IVF center in Nashik gave us hope. The IVF cost was transparent, and the team’s care was exceptional. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocId70JrDMx2FBCnvRSbVZIR2xkp72hMRQIx9B_MiOa6CiZBfA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/4kpTffhGZdcuvfzGA",
      "null": null
    },
    {
      "id": 108,
      "center_name": "nashik",
      "clinic_location": "nashik",
      "city": "Nashik",
      "rating": 5,
      "name": "Usha Patil",
      "reviews": "Looking for IVF near me in Nashik? This is the place! The staff was supportive, and the treatment was effective. We are now proud parents. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKd6EMo8mfe_nwnc21KCZEyjyUTAEJkj7uzQmqzHdBUJ3kqGw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/BQpA7ZhxLHFivaTw8",
      "null": null
    },
    {
      "id": 109,
      "center_name": "nashik",
      "clinic_location": "nashik",
      "city": "Nashik",
      "rating": 5,
      "name": "Kavitaa Tailor",
      "reviews": "The best IVF center in Nashik with a caring team. The IVF cost was reasonable, and the process was smooth. We are forever grateful for this experience.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLB4g4D5uVY1V0iEdLRtKyM-3LhfjB8MRHCN463oSxT6z8LLQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/8R4BQPLgqgPAP1736",
      "null": null
    },
    {
      "id": 110,
      "center_name": "nashik",
      "clinic_location": "nashik",
      "city": "Nashik",
      "rating": 5,
      "name": "Ganesh Karwal",
      "reviews": "Facing fertility challenges? This IVF center in Nashik changed our lives. The staff was kind, and the treatment was successful. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJ68lcyDouptfG9QliSEPkNQcnaqSgtl22AKCSxqOGTV_fWpQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/qCRMabjGYj8BCPt59",
      "null": null
    },
    {
      "id": 111,
      "center_name": "nashik",
      "clinic_location": "nashik",
      "city": "Nashik",
      "rating": 5,
      "name": "Mahesh Belekar",
      "reviews": "Our IVF journey in Nashik was amazing. The best IVF center near me with a supportive team. The results were beyond our expectations. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJGybbY0m6SV_1ztoFm6JrwRtxrI518iZGVVxqQmeE8X0xz=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/nRSAEvdAn47dfL828",
      "null": null
    },
    {
      "id": 112,
      "center_name": "raipur",
      "clinic_location": "raipur",
      "city": "Raipur",
      "rating": 5,
      "name": "Bharat Pahuja",
      "reviews": "After years of disappointment, Dr. Pratibha Tiwary at the IVF centre in Raipur gave us hope. The staff was supportive, and the treatment was successful. Highly recommend!\"",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJcQsAWo41KeW8Uq7SI18ytKZNgvGF6bua3uiqzVq2d-nrprg=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/Ap4DHNNqNFF3de9p8",
      "null": null
    },
    {
      "id": 113,
      "center_name": "raipur",
      "clinic_location": "raipur",
      "city": "Raipur",
      "rating": 5,
      "name": "Tanushree Barua",
      "reviews": "Looking for IVF doctors near me in Raipur? This is the place! The team was caring, and the process was smooth. We are now proud parents. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUtTTGVmqP73WWZ5MI01q8SV7jYGyGBlnn-ANITA5kFj7olbFbe=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/3APNiiqWCYJCQi579",
      "null": null
    },
    {
      "id": 114,
      "center_name": "raipur",
      "clinic_location": "raipur",
      "city": "Raipur",
      "rating": 5,
      "name": "Komal Dewangan",
      "reviews": "The best IVF centre in Raipur with a kind and professional team. The treatment was effective, and we are forever grateful for this experience.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXh2W7mJ0GXx9C6OcuCCZM5rVVOowYiZbJ5bH4BHkMQm0odSxtrDA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/5g7weWndF8spoivY9",
      "null": null
    },
    {
      "id": 115,
      "center_name": "raipur",
      "clinic_location": "raipur",
      "city": "Raipur",
      "rating": 5,
      "name": "Kumar Gaurav",
      "reviews": "Facing fertility challenges? This IVF centre in Raipur changed our lives. The staff was amazing, and the results were beyond our expectations. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWnkuovrXnz1mjY51aCuYlk9bY9m-ikCtwQVDkQIm5hbwmeRya7=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/d9ZW1eKKzSV9BxaY6",
      "null": null
    },
    {
      "id": 116,
      "center_name": "raipur",
      "clinic_location": "raipur",
      "city": "Raipur",
      "rating": 5,
      "name": "Deepali",
      "reviews": "Our IVF journey in Raipur was stress-free, thanks to the supportive team. The treatment was successful, and we are now a happy family. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJNdu8TzMyiCufxfy050DJ4Ahbj5ZFbwQnKiLELXgCFMg2Xlw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/WjhFNwQUAyF96tFs5",
      "null": null
    },
    {
      "id": 117,
      "center_name": "vadodara",
      "clinic_location": "vadodara",
      "city": "Vadodara",
      "rating": 4.9,
      "name": "Suresh Rathod",
      "reviews": "Dr. Baxi Sushma at the best IVF center in Vadodara made our dream come true. The staff was caring, and the treatment was successful. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIIAsTF_7X4PRqAp7QGO2k--v3InJzvgxvFaSfjJxHya7VImA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/WFzNBZkSXGWHvo4T9",
      "null": null
    },
    {
      "id": 118,
      "center_name": "vadodara",
      "clinic_location": "vadodara",
      "city": "Vadodara",
      "rating": 4.9,
      "name": "Neetu Vardhan",
      "reviews": "Looking for IVF treatment in Vadodara? This is the place! The team was supportive, and the process was smooth. We are now proud parents. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXlrPuozneVBtTmL_K0Ahehxn196w8KCLREkH6mAWiXWqztIKo=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/2t7c8fhss29oT7BNA",
      "null": null
    },
    {
      "id": 119,
      "center_name": "vadodara",
      "clinic_location": "vadodara",
      "city": "Vadodara",
      "rating": 4.9,
      "name": "Aneeta Patel",
      "reviews": "The best IVF hospital in Vadodara with a kind and professional team. The treatment was effective, and we are forever grateful for this experience.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWyTc0wnx3xYEQJf0sO9XHuZeV_aU0DmSnJqnX0lyq1XXW_7GY=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/93js5Buyji79GZ3J6",
      "null": null
    },
    {
      "id": 120,
      "center_name": "vadodara",
      "clinic_location": "vadodara",
      "city": "Vadodara",
      "rating": 4.9,
      "name": "Santosh Luste",
      "reviews": "Facing fertility challenges? This IVF centre in Vadodara changed our lives. The staff was amazing, and the results were beyond our expectations. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJBhEoHMcqaSzUpYCnWjSMsGy3G6HnQIvL3JSdyiRQ6FkNxwQ=w56-h56-p-rp-mo-ba3-br100",
      "review_link": "https://maps.app.goo.gl/jekG5b9XYda1eKJ16",
      "null": null
    },
    {
      "id": 121,
      "center_name": "vadodara",
      "clinic_location": "vadodara",
      "city": "Vadodara",
      "rating": 4.9,
      "name": "Mahesh Sharma",
      "reviews": "Our IVF journey in Vadodara was stress-free, thanks to the supportive team. The treatment was successful, and we are now a happy family. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocIIAsTF_7X4PRqAp7QGO2k--v3InJzvgxvFaSfjJxHya7VImA=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/aycBs9hiZbk76zjp9",
      "null": null
    },
    {
      "id": 122,
      "center_name": "ranchi",
      "clinic_location": "ranchi",
      "city": "Ranchi",
      "rating": 4.9,
      "name": "Rahul Singh",
      "reviews": "Dr. Musunuru Rajani at the IVF center in Ranchi made our dream come true. The staff was caring, and the treatment was successful. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLHQ4AeF9R3sXJ6knv6QVhYF8IXVCm40yodoycGfpWVT_4ZEw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/11PRU8AFdhdqiVMa9",
      "null": null
    },
    {
      "id": 123,
      "center_name": "ranchi",
      "clinic_location": "ranchi",
      "city": "Ranchi",
      "rating": 4.9,
      "name": "Ashish Sharma",
      "reviews": "Looking for IVF in Ranchi? This is the place! The team was supportive, and the process was smooth. We are now proud parents. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjV392MCna1evNE97BAL2Arm19DZyBqWv-YcBrWHwY-ruNGt5hjGww=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/pPdVbPXQHjQikzAc7",
      "null": null
    },
    {
      "id": 124,
      "center_name": "ranchi",
      "clinic_location": "ranchi",
      "city": "Ranchi",
      "rating": 4.9,
      "name": "Shiva Yadav",
      "reviews": "The best IVF centre in Ranchi with a kind and professional team. The treatment was effective, and we are forever grateful for this experience.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLTL_laLgwHEnsxuK2ogZeW3rSRivwey2_GcSc1nA8xipJAHQ=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/YvhAPRFnXAnmZTxG7",
      "null": null
    },
    {
      "id": 125,
      "center_name": "ranchi",
      "clinic_location": "ranchi",
      "city": "Ranchi",
      "rating": 4.9,
      "name": "Rohini",
      "reviews": "Facing fertility challenges? This IVF center in Ranchi changed our lives. The staff was amazing, and the results were beyond our expectations. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVSIR3Vk2EgPPIPtzUdJUT9zuJuPW8YOGc1K2myh9un8p6CR49I=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/25YW4TKyZYhdEv8b9",
      "null": null
    },
    {
      "id": 126,
      "center_name": "ranchi",
      "clinic_location": "ranchi",
      "city": "Ranchi",
      "rating": 4.9,
      "name": "Rahul Kumar",
      "reviews": "Our IVF journey in Ranchi was stress-free, thanks to the supportive team. The treatment was successful, and we are now a happy family. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLHQ4AeF9R3sXJ6knv6QVhYF8IXVCm40yodoycGfpWVT_4ZEw=w56-h56-p-rp-mo-br100",
      "review_link": "https://maps.app.goo.gl/whdkLHy86bK6XrHV9",
      "null": null
    },
    {
      "id": 127,
      "null": null,
      "review_link": "https://maps.app.goo.gl/Z2iVz6dH84txkRag7",
      "center_name": "india",
      "clinic_location": "Hyderabad",
      "rating": 5,
      "reviews": "\"I recently visited Oasis for my prenatal care, and I must say, I was thoroughly impressed. Dr. MeeraJindal and Tejashree was extremely knowledgeable, kind, and took the time to answer all my questions.",
      "name": "Sai Singh",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWjG9wHNIcDGy4OTnfpUpwQWolqPfV3q2B4LCY8NsAJGa91ZUjXcQ=w60-h60-p-rp-mo-br100"
    },
    {
      "id": 128,
      "null": null,
      "review_link": "https://maps.app.goo.gl/5fX9pg83f7pnbLV66",
      "center_name": "india",
      "clinic_location": "Bengaluru",
      "rating": 4.9,
      "reviews": "Thanks to oasis for all the support. We have gone through a lot before coming here. Since when we started taking treatment from oasis hospital really given me a positive vibe.We are really happy to share this review.",
      "name": "Manikeshwari K",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKLdL9IMtSrXEVOoE-h0Vwf9ghAlLbVbkdoF1nn8GV6koWaS5Jv=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 129,
      "null": null,
      "review_link": "https://maps.app.goo.gl/VmJGRjP3hsAggU16A",
      "center_name": "india",
      "clinic_location": "Pune",
      "rating": 4.9,
      "reviews": "Excellent facilities and compassionate care at OASIS Hospital, making a significant difference in our journey to parenthood. THANKS TO COMPLETE OASIS TEAM.",
      "name": "Rajendra Mothe",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWMEgexjQ1nlN0b41jXtSpkfz-QhplE6yNT7VJpMO4sYBuyNPHddQ=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 130,
      "null": null,
      "review_link": "https://maps.app.goo.gl/NDCLK7VYLcgZVBnA8",
      "center_name": "india",
      "clinic_location": "chennai",
      "rating": 4.9,
      "reviews": "Thanks for Nova IVF and thank you so much for dr.ajantha mam .she is very friendly and ans all enquiries.she give good confident for pts .all staff are pt guidance well.",
      "name": "Sathiya Sathiya",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJo2e2MAmX1H1FJQABYQZ1i-b6FRw_EKJaAvoACCmyWWcV4zw=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 131,
      "null": null,
      "review_link": "https://maps.app.goo.gl/WFzNBZkSXGWHvo4T9",
      "center_name": "india",
      "clinic_location": "Vadodara",
      "rating": 5,
      "reviews": "We want to Jalgaon manmad but we didn't find what we came for but in nashik oasis fertility dr pallavi dr Meenakshi centre manager pre full staff support guide a lot are hopes and dreams came true all credit to dr pallavi highly recommend",
      "name": "Usha Patil",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKd6EMo8mfe_nwnc21KCZEyjyUTAEJkj7uzQmqzHdBUJ3kqGw=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 127,
      "center_name": "kakinada",
      "center_location": "kakinada",
      "city": "kakinada",
      "rating": 5,
      "name": "Srikanth Sri",
      "reviews": "Dr. Ramineedi at the best IVF hospital in kakinada changed our lives. Her expertise and the team’s care made our IVF treatment successful. Forever grateful!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJV0CbscHMoi8u1hCrFTgJe-jBE18h7cyY7tZAba3nO6IjjY96z=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 128,
      "center_name": "kakinada",
      "center_location": "kakinada",
      "city": null,
      "rating": 5,
      "name": "Madhusudan Naidu Pathipati",
      "reviews": "After years of disappointment, we found hope at kakinada IVF Centres. The staff was supportive, and the treatment was effective. We are now proud parents. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJJqeZyvFm1fC9s5Wy35_EqRjG5jAHujaRg7SDrqIg-u9dblw=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 129,
      "center_name": "kakinada",
      "center_location": "kakinada",
      "city": "kakinada",
      "rating": 5,
      "name": "Vasanth Appapogu",
      "reviews": "Dr. Ramineedi is amazing! The best IVF hospital in kakinada with a team that feels like family. The process was smooth, and the results were life-changing.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocKqcRkT75CGLsu44io3o73xFfGLta_9biNXnBfuaOYo0LszSw=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 130,
      "center_name": "kakinada",
      "center_location": "kakinada",
      "city": "kakinada",
      "rating": 4.9,
      "name": "Gowthami Gowni",
      "reviews": "Looking for IVF treatment in kakinada ? This is the place! The staff was kind, and the care was exceptional. Our dream of parenthood finally came true. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWIfG_ONIOQqjrx7OExlhmR__iP_5KVoJ6Jw9tZC2dbJzJqMbCu=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 131,
      "center_name": "tolichowki",
      "center_location": "tolichowki",
      "city": "tolichowki",
      "rating": 4.9,
      "name": "Aaliya Sheikh",
      "reviews": "We found the best IVF center in Hyderabad. The process was smooth, and the staff made us feel at ease. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjVaryLP-qAbGfBXYjLtdaQi58njQC1hz2T-zOdhn2tyV9pptEe2Tw=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 132,
      "center_name": "tolichowki",
      "center_location": "tolichowki",
      "city": "tolichowki",
      "rating": 4.9,
      "name": "Lekhan Naga",
      "reviews": "Dr. Keerthana V is amazing! The IVF center in Hyderabad has a warm environment, and the treatment was successful. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocI5mA_d95nPa0fHlv9ncDPrqwECj6JM2LGpP8wrGZ7B46HdXA=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 133,
      "center_name": "tolichowki",
      "center_location": "tolichowki",
      "city": "tolichowki",
      "rating": 4.9,
      "name": "Kaniki Shekar",
      "reviews": "The best IVF doctor in Hyderabad! Dr. Keerthana V explained everything clearly, and the staff was very supportive.",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocLipXYIcAPExyu_HZLcNechNkVeyScHkmBmOeiAm_22ckyP=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 134,
      "center_name": "tolichowki",
      "center_location": "tolichowki",
      "city": "tolichowki",
      "rating": 4.9,
      "name": "Lakshmi Sarada",
      "reviews": "We are so grateful to this IVF center in Hyderabad. The cost was transparent, and the care was exceptional. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJdA5mFa1KosgA1bVPQqhMPUKmCwtPMxHRivQiwfUSABq-FTA=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 135,
      "center_name": "bhubaneswar",
      "center_location": "bhubaneswar",
      "city": "bhubaneswar",
      "rating": 5,
      "name": "Bharat Pahuja",
      "reviews": "After years of disappointment, Dr. Suprava Jena at the IVF centre in Raipur gave us hope. The staff was supportive, and the treatment was successful. Highly recommend!\"",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJcQsAWo41KeW8Uq7SI18ytKZNgvGF6bua3uiqzVq2d-nrprg=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 136,
      "center_name": "bhubaneswar",
      "center_location": "bhubaneswar",
      "city": "bhubaneswar",
      "rating": 5,
      "name": "Tanushree Barua",
      "reviews": "Looking for IVF doctors near me in bhubaneswar? This is the place! The team was caring, and the process was smooth. We are now proud parents. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjUtTTGVmqP73WWZ5MI01q8SV7jYGyGBlnn-ANITA5kFj7olbFbe=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 137,
      "center_name": "bhubaneswar",
      "center_location": "bhubaneswar",
      "city": "bhubaneswar",
      "rating": 5,
      "name": "Komal Dewangan",
      "reviews": "The best IVF centre in bhubaneswar with a kind and professional team. The treatment was effective, and we are forever grateful for this experience.",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjXh2W7mJ0GXx9C6OcuCCZM5rVVOowYiZbJ5bH4BHkMQm0odSxtrDA=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 138,
      "center_name": "bhubaneswar",
      "center_location": "bhubaneswar",
      "city": "bhubaneswar",
      "rating": 5,
      "name": "Kumar Gaurav",
      "reviews": "Facing fertility challenges? This IVF centre in bhubaneswar changed our lives. The staff was amazing, and the results were beyond our expectations. Highly recommend!",
      "profile_picture": "https://lh3.googleusercontent.com/a-/ALV-UjWnkuovrXnz1mjY51aCuYlk9bY9m-ikCtwQVDkQIm5hbwmeRya7=w56-h56-p-rp-mo-br100"
    },
    {
      "id": 139,
      "center_name": "bhubaneswar",
      "center_location": "bhubaneswar",
      "city": "bhubaneswar",
      "rating": 5,
      "name": "Deepali",
      "reviews": "Our IVF journey in bhubaneswar was stress-free, thanks to the supportive team. The treatment was successful, and we are now a happy family. Thank you!",
      "profile_picture": "https://lh3.googleusercontent.com/a/ACg8ocJNdu8TzMyiCufxfy050DJ4Ahbj5ZFbwQnKiLELXgCFMg2Xlw=w56-h56-p-rp-mo-br100"
    }
   
  ]

  export default ivfReview;