const maleFertilityDoctors = [
    {
        "id": 1,
        "fullname": "Dr Raghuveer Karne",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 1,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 2,
        "fullname": "Dr Raghuveer Karne",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 11,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 3,
        "fullname": "Dr Raghuveer Karne",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 10,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 4,
        "fullname": "Dr Sarath Gillelmudi",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 12,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 5,
        "fullname": "Dr Santhi Vardhan",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": null,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 6,
        "fullname": "Dr Pradeep Uppala",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 15,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 7,
        "fullname": "Dr B Suresh",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 16,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 8,
        "fullname": "Dr Pradeep Uppala",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 14,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 9,
        "fullname": "Dr Y Manoj",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 17,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 10,
        "fullname": "Dr Pulla Prasad",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 37,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 11,
        "fullname": "Dr Dhananjay Sathe",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 24,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 12,
        "fullname": "Dr Amey Patil",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 27,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 13,
        "fullname": "Dr Tarun",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 19,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 14,
        "fullname": "Dr Raju R",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 19,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 15,
        "fullname": "Dr Vishruth K Raj",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 19,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 16,
        "fullname": "Dr R Prathik",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 21,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 17,
        "fullname": null,
        "designation": null,
        "experience": null,
        "docterImage": null,
        "master_id": 22,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 18,
        "fullname": "Dr Debabrata Sabat",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 31,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 19,
        "fullname": null,
        "designation": null,
        "experience": null,
        "docterImage": null,
        "master_id": 28,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 20,
        "fullname": "Dr Karthikeyan",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 23,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 21,
        "fullname": "Dr Nisarg Mehta",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 29,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 22,
        "fullname": null,
        "designation": null,
        "experience": null,
        "docterImage": null,
        "master_id": 30,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 23,
        "fullname": "Dr Raghuveer Karne",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 34,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 24,
        "fullname": "Dr Sarath Gillelmudi",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 34,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 25,
        "fullname": "Dr Santhi Vardhan",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 34,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 26,
        "fullname": "Dr Pradeep Uppala",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 34,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 27,
        "fullname": "Dr B Suresh",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 34,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 28,
        "fullname": "Dr Y Manoj",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 34,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 29,
        "fullname": "Dr Pulla Prasad",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 34,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 30,
        "fullname": "Dr Dhananjay Sathe",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 34,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 31,
        "fullname": "Dr Amey Patil",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 34,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 32,
        "fullname": "Dr Tarun",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 34,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 33,
        "fullname": "Dr Raju R",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 34,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 34,
        "fullname": "Dr Vishruth K Raj",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 34,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 35,
        "fullname": "Dr R Prathik",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 34,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 36,
        "fullname": "Dr Debabrata Sabat",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 34,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 37,
        "fullname": "Dr Karthikeyan",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 34,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
      {
        "id": 38,
        "fullname": "Dr Nisarg Mehta",
        "designation": "Senior Consultant",
        "experience": null,
        "docterImage": null,
        "master_id": 34,
        "qualification": null,
        "areaOfSpecialization": null,
        "practoRating": null
      },
];

export default maleFertilityDoctors;