const newdoctorslp3 = [
    {
        "id": 1,
        "fullname": "Dr. Aaishwari Durge",
        "designation": "Consultant",
        "experience": "5 Yrs",
        "docterImage": "Dr. Aaishwari Durge.webp",
        "master_id": "1",
        "qualification": "MS-OBG",
        "areaOfSpecialization": "Fellowship in reproductive medicine"
    },
    {
        "id": 2,
        "fullname": "Dr. Durga Rao Gedela",
        "designation": "Co-founder & Medical Director",
        "experience": "18 Years",
        "docterImage": "Dr. Durga Rao Gedela.webp",
        "master_id": "1",
        "qualification": "MBBS, DGO, MRCOG (UK),",
        "areaOfSpecialization": "Fellowship in Reproductive Endocrinology & Infertility",
        "practoRating": "99%"
    },
    {
        "id": 3,
        "fullname": "Dr. Parinaaz Parhar",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "12 Years",
        "docterImage": "Dr. Parinaaz Parhar.webp",
        "master_id": "1",
        "qualification": "MS - OBG, DNB - OBG \n",
        "areaOfSpecialization": "Fellowship in Minimal Access Surgery , Fellowship of National Board in Reproductive Medicine",
        "practoRating": "100%"
    },
    {
        "id": 4,
        "fullname": "Dr. Raghuveer Karne",
        "designation": "Consultant",
        "experience": "8 Yrs",
        "docterImage": "Dr. Raghuveer Karne.webp",
        "master_id": "1",
        "qualification": "MS (General Surgery), \nDNB (Genitourinary Surgery)",
        "areaOfSpecialization": "Master in Andrology's"
    },
    {
        "id": 5,
        "fullname": "Dr. Srinivasa Varalakshmi Yakasiri",
        "designation": "Clinical Head & Sr. Fertility Specialist",
        "experience": "30 Yrs",
        "docterImage": "Dr. Srinivasa Varalakshmi Yakasiri.webp",
        "master_id": "1",
        "qualification": "MBBS, DGO",
        "areaOfSpecialization": "Fellowship in Infertility (IMA)"
    },
    {
        "id": 6,
        "fullname": "Dr. Vellala Avanthi",
        "designation": "Consultant Fertility Specialist",
        "experience": "3 Yrs",
        "docterImage": "Dr. Vellala Avanthi.webp",
        "master_id": "1",
        "qualification": "MS-OBG",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine"
    },
    {
        "id": 7,
        "fullname": "Dr. Aaishwari Durge",
        "designation": "Consultant",
        "experience": "5 Yrs",
        "docterImage": "Dr. Aaishwari Durge.webp",
        "master_id": "2",
        "qualification": "MS-OBG",
        "second qualification degree": "MBBS , Icog certificate course in gynecological endoscopy\nPost graduate diploma in ART and reproductive endocrinology (UKSH- KIEL GERMANY)",
        "areaOfSpecialization": "#N/A"
    },
    {
        "id": 8,
        "fullname": "Dr. Durga Rao Gedela",
        "designation": "Co-founder & Medical Director",
        "experience": "18 Years",
        "docterImage": "Dr. Durga Rao Gedela.webp",
        "master_id": "2",
        "qualification": "MBBS, DGO, MRCOG (UK),",
        "areaOfSpecialization": "Fellowship in Reproductive Endocrinology & Infertility",
        "practoRating": "99%"
    },
    {
        "id": 9,
        "fullname": "Dr. Ramineedi Deepthi Priyadarshini",
        "designation": "Fertility Specialist",
        "experience": "10 Years",
        "docterImage": "Dr. Ramineedi Deepthi Priyadarshini.webp",
        "master_id": "2",
        "qualification": "MS, FNB",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine",
        "practoRating": ""
    },
    {
        "id": 10,
        "fullname": "Dr. Parinaaz Parhar",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "12 Years",
        "docterImage": "Dr. Parinaaz Parhar.webp",
        "master_id": "3",
        "qualification": "MS - OBG, DNB - OBG \n",
        "areaOfSpecialization": "Fellowship in Minimal Access Surgery , Fellowship of National Board in Reproductive Medicine",
        "practoRating": "100%"
    },
    {
        "id": 11,
        "fullname": "Dr. Srinivasa Varalakshmi Yakasiri",
        "designation": "Clinical Head & Sr. Fertility Specialist",
        "experience": "30 Yrs",
        "docterImage": "Dr. Srinivasa Varalakshmi Yakasiri.webp",
        "master_id": "3",
        "qualification": "MBBS, DGO",
        "second qualification degree": "M.B.B.S ,",
        "areaOfSpecialization": "#N/A"
    },
    {
        "id": 12,
        "fullname": "Dr. Vellala Avanthi",
        "designation": "Consultant",
        "experience": "3 Yrs",
        "docterImage": "Dr. Vellala Avanthi.webp",
        "master_id": "3",
        "qualification": "MS-OBG",
        "second qualification degree": "MBBS FROM GUNTUR MEDICAL COLLEGE",
        "areaOfSpecialization": "#N/A"
    },
    // {
    //     "id": 13,
    //     "fullname": "Dr. A Tejashree",
    //     "designation": "Junior Consultant",
    //     "experience": "12 Yrs",
    //     "docterImage": "Dr. A Tejashree.webp",
    //     "master_id": "4",
    //     "qualification": "MBBS, MS - OBG \n",
    //     "areaOfSpecialization": "Fellowship in reproductive medicine"
    // },
    {
        "id": 14,
        "fullname": "Dr. A Tejashree",
        "designation": "Fertility Specialist",
        "experience": "6 Years",
        "docterImage": "Dr. A Tejashree.webp",
        "master_id": "4",
        "qualification": "MBBS,DGO,MS-OBGY,Advanced Diploma in ART and Reproductive medicine Fertility Specalist",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine at Ferty 9",
        "practoRating": "100%"
    },
    {
        "id": 15,
        "fullname": "Dr. Bogi Reddy Mounika",
        "designation": "Fertility Specialist",
        "experience": "2 Years",
        "docterImage": "Dr. Bogi Reddy Mounika.webp",
        "master_id": "4",
        "qualification": "MBBS, MS OBG",
        "areaOfSpecialization": "FRM, advanced diploma in ART and reproductive medicine - kiel germany",
        "practoRating": ""
    },
    {
        "id": 16,
        "fullname": "Dr. Sai Manasa Darla",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "7 Yrs",
        "docterImage": "Dr. Sai Manasa Darla.webp",
        "master_id": "4",
        "qualification": "MBBS, MS OBG, FRM,FMAS,FELLOWSHIP IN ART",
        "areaOfSpecialization": "Fellowship in Minimal Access Surgery"
    },
    {
        "id": 17,
        "fullname": "Dr. Parinaaz Parhar",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "12 Years",
        "docterImage": "Dr. Parinaaz Parhar.webp",
        "master_id": "5",
        "qualification": "MS - OBG, DNB - OBG \n",
        "areaOfSpecialization": "Fellowship in Minimal Access Surgery , Fellowship of National Board in Reproductive Medicine",
        "practoRating": "100%"
    },
    {
        "id": 18,
        "fullname": "Dr. Raghuveer Karne",
        "designation": "Consultant",
        "experience": "8 Yrs",
        "docterImage": "Dr. Raghuveer Karne.webp",
        "master_id": "5",
        "qualification": "MS (General Surgery), \nDNB (Genitourinary Surgery) ",
      "areaOfSpecialization": "#N/A"
    },
    {
        "id": 19,
        "fullname": "Dr. Sai Manasa Darla",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "8 Years",
        "docterImage": "Dr. Sai Manasa Darla.webp",
        "master_id": "5",
        "qualification": "MBBS, MS OBG, FRM,FMAS,FELLOWSHIP IN ART",
        "areaOfSpecialization": "FRM,FMAS,FELLOWSHIP IN ART",
        "practoRating": "100%"
    },
    {
        "id": 20,
        "fullname": "Dr. Srinivasa Varalakshmi Yakasiri",
        "designation": "Clinical Head",
        "experience": "30 Yrs",
        "docterImage": "Dr. Srinivasa Varalakshmi Yakasiri.webp",
        "master_id": "5",
        "qualification": "MBBS, DGO",
        "second qualification degree": "M.B.B.S ,",
        "areaOfSpecialization": "#N/A"
    },
    {
        "id": 21,
        "fullname": "Dr. Nuthakki Spandana",
        "designation": "Fertility Specialist",
        "experience": "7 Years",
        "docterImage": "Dr. Nuthakki Spandana.webp",
        "master_id": "6",
        "qualification": "MS - OBG",
        "areaOfSpecialization": "Fellowship in fertility, laparoscopic surgeon",
        "practoRating": ""
    },
    {
        "id": 22,
        "fullname": "Dr. Srinivasa Varalakshmi Yakasiri",
        "designation": "Clinical Head",
        "experience": "30 Yrs",
        "docterImage": "Dr. Srinivasa Varalakshmi Yakasiri.webp",
        "master_id": "6",
        "qualification": "MBBS, DGO",
        "areaOfSpecialization": "#N/A"
    },
    {
        "id": 23,
        "fullname": "Dr. Vallabhareddy Devi Syamala",
        "designation": "Fertility Specialist",
        "experience": "2 Years",
        "docterImage": "Dr. Vallabhareddy Devi Syamala.webp",
        "master_id": "6",
        "qualification": "MBBS, MS (OBG)",
        "areaOfSpecialization": "FRM",
        "practoRating": ""
    },
    {
        "id": 24,
        "fullname": "Dr. Meera Jindal",
        "designation": "Consultant Fertility Specialist",
        "experience": "13 Years",
        "docterImage": "Dr. Meera Jindal.webp",
        "master_id": "7",
        "qualification": "MS - OBGYN, DNB, FNB",
        "areaOfSpecialization": "Fellowship in Gynecologic Laparoscopy",
        "practoRating": "100%"
    },
    {
        "id": 25,
        "fullname": "Dr. Parinaaz Parhar",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "12 Years",
        "docterImage": "Dr. Parinaaz Parhar.webp",
        "master_id": "7",
        "qualification": "MS - OBG, DNB - OBG \n",
        "areaOfSpecialization": "Fellowship in Minimal Access Surgery , Fellowship of National Board in Reproductive Medicine",
        "practoRating": "100%"
    },
    {
        "id": 26,
        "fullname": "Dr. Srinivasa Varalakshmi Yakasiri",
        "designation": "Clinical Head",
        "experience": "30 Yrs",
        "docterImage": "Dr. Srinivasa Varalakshmi Yakasiri.webp",
        "master_id": "7",
        "qualification": "MBBS, DGO",
        "areaOfSpecialization": "#N/A"
    },
    {
        "id": 27,
        "fullname": "Dr. M V D Aruna",
        "designation": "Consultant Fertility Specialist",
        "experience": "29 Years",
        "docterImage": "Dr. M V D Aruna.webp",
        "master_id": "8",
        "qualification": "MBBS,MD DGO",
        "areaOfSpecialization": "Dimploma in aMinimal Acess surgery,ICOG Fellowship in Reproductiv medicine,Fellowship in Infertiltiy",
        "practoRating": "100%"
    },
    {
        "id": 28,
        "fullname": "Dr. Sai Manasa Darla",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "7 Yrs",
        "docterImage": "Dr. Sai Manasa Darla.webp",
        "master_id": "8",
        "qualification": "MBBS, MS OBG, FRM,FMAS,FELLOWSHIP IN ART",
        "areaOfSpecialization": "#N/A"
    },
    {
        "id": 29,
        "fullname": "Dr. Keerthana V",
        "designation": "Fertility Specialist",
        "experience": "12 years",
        "docterImage": "Dr. Keerthana V.webp",
        "master_id": "9",
        "qualification": "MBBS,DNB(OBG)",
        "areaOfSpecialization": "FNB(REPRODUCTIVE MEDICINE)",
        "practoRating": ""
    },
    {
        "id": 30,
        "fullname": "Dr. Parinaaz Parhar",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "12 Years",
        "docterImage": "Dr. Parinaaz Parhar.webp",
        "master_id": "9",
        "qualification": "MS - OBG, DNB - OBG \n",
        "areaOfSpecialization": "Fellowship in Minimal Access Surgery , Fellowship of National Board in Reproductive Medicine",
        "practoRating": "100%"
    },
    {
        "id": 31,
        "fullname": "Dr. Srinivasa Varalakshmi Yakasiri",
        "designation": "Clinical Head",
        "experience": "30 Yrs",
        "docterImage": "Dr. Srinivasa Varalakshmi Yakasiri.webp",
        "master_id": "9",
        "qualification": "MBBS, DGO",
        "areaOfSpecialization": "#N/A"
    },
    {
        "id": 32,
        "fullname": "Dr. B S Bhavya",
        "designation": "Fertility Specialist",
        "experience": "5 Years",
        "docterImage": "Dr. B S Bhavya.webp",
        "master_id": "10",
        "qualification": "MBBS, MS OBG",
        "areaOfSpecialization": "FRM",
        "practoRating": ""
    },
    {
        "id": 33,
        "fullname": "Dr. Jalagam Kavya Rao",
        "designation": "Regional Medical Head & Fertility Specialist",
        "experience": "10 Years",
        "docterImage": "Dr. Jalagam Kavya Rao.webp",
        "master_id": "10",
        "qualification": "MBBS, MS OBG, FRM, FIGL",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine fro m OSHREM- 2017-2018, Fellowship in Gynecological Laproscopy- KEIL- Germany-2020-2021",
        "practoRating": "100%"
    },
    {
        "id": 34,
        "fullname": "Dr. M V D Aruna",
        "designation": "Consultant Fertility Specialist",
        "experience": "29 Years",
        "docterImage": "Dr. M V D Aruna.webp",
        "master_id": "10",
        "qualification": "MBBS,MD DGO",
        "areaOfSpecialization": "Dimploma in aMinimal Acess surgery,ICOG Fellowship in Reproductiv medicine,Fellowship in Infertiltiy",
        "practoRating": "100%"
    },
    {
        "id": 35,
        "fullname": "Dr. Meera Jindal",
        "designation": "Consultant Fertility Specialist",
        "experience": "13 Years",
        "docterImage": "Dr. Meera Jindal.webp",
        "master_id": "10",
        "qualification": "MS - OBGYN, DNB, FNB",
        "areaOfSpecialization": "Fellowship in Gynecologic Laparoscopy",
        "practoRating": "100%"
    },
    {
        "id": 36,
        "fullname": "Dr. B S Bhavya",
        "designation": "Fertility Specialist",
        "experience": "5 Years",
        "docterImage": "Dr. B S Bhavya.webp",
        "master_id": "11",
        "qualification": "MBBS, MS OBG",
        "areaOfSpecialization": "FRM",
        "practoRating": ""
    },
    {
        "id": 37,
        "fullname": "Dr. Jigna Tamagond",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "14 Years",
        "docterImage": "Dr. Jigna Tamagond.webp",
        "master_id": "11",
        "qualification": "MS-OBG",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine",
        "practoRating": "100%"
    },
    {
        "id": 38,
        "fullname": "Dr. Meera Jindal",
        "designation": "Consultant Fertility Specialist",
        "experience": "13 Years",
        "docterImage": "Dr. Meera Jindal.webp",
        "master_id": "11",
        "qualification": "MS - OBGYN, DNB, FNB",
        "areaOfSpecialization": "Fellowship in Gynecologic Laparoscopy",
        "practoRating": "100%"
    },
    {
        "id": 39,
        "fullname": "Dr. R Samyuktha",
        "designation": "Fertility Specialist",
        "experience": "6 Years",
        "docterImage": "Dr. R Samyuktha.webp",
        "master_id": "11",
        "qualification": "MBBS, DGO \n",
        "Awards": "karimnagar\n"
    },
    // {
    //     "id": 40,
    //     "fullname": "Dr. Mathi Harika",
    //     "designation": "Consultant Fertility Specialist",
    //     "experience": "11 Years",
    //     "docterImage": "Dr. Mathi Harika.webp",
    //     "master_id": "12",
    //     "qualification": "MS - OBGYN, FRM",
    //     "areaOfSpecialization": "Fellowship in Reproductive Medicine",
    //     "practoRating": ""
    // },
    {
        "id": 41,
        "fullname": "Dr. Radhika Potluri",
        "designation": "Regional Medical Head & Fertility Specialist",
        "experience": "19 Years",
        "docterImage": "Dr. Radhika Potluri.webp",
        "master_id": "12",
        "qualification": "MS - OBG \n",
        "areaOfSpecialization": "Fellowship in Minimal Access Surgery Fellowship in Reproductive Medicine",
        "practoRating": "99%"
    },
    {
        "id": 42,
        "fullname": "Dr. Ramya Vicharapu",
        "designation": "Consultant Fertility Specialist",
        "experience": "18 Years",
        "docterImage": "Dr. Ramya Vicharapu.webp",
        "master_id": "12",
        "qualification": "MBBS, DNB (OBG), FRM (MGR), DMAS",
        "areaOfSpecialization": "DNB (OBG), Post Doctoral fellow in Reproductive Medicine (MGR), Diploma in minimal acess surgery",
        "practoRating": "99%"
    },
    {
        "id": 43,
        "fullname": "Dr. Venkata Sujatha Vellanki",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "21 Years",
        "docterImage": "Dr. Venkata Sujatha Vellanki.webp",
        "master_id": "12",
        "qualification": "MBBS, OBG MS, MICOG, FAIMER",
        "practoRating": "98%"
    },
    {
        "id": 44,
        "fullname": "Dr. Boddu Padma",
        "designation": "Fertility Specialist",
        "experience": "16 Years",
        "docterImage": "Dr. Boddu Padma.webp",
        "master_id": "13",
        "qualification": "MBBS",
        "practoRating": ""
    },
    {
        "id": 45,
        "fullname": "Dr. Radhika Potluri",
        "designation": "Regional Medical Head & Fertility Specialist",
        "experience": "19 Years",
        "docterImage": "Dr. Radhika Potluri.webp",
        "master_id": "13",
        "qualification": "MS - OBG \n",
        "areaOfSpecialization": "Fellowship in Minimal Access Surgery Fellowship in Reproductive Medicine",
        "practoRating": "99%"
    },
    {
        "id": 46,
        "fullname": "Dr. Tenali Vijaya Lakshmi",
        "designation": "Fertility Specialist",
        "experience": "13 Years",
        "docterImage": "Dr. Tenali Vijaya Lakshmi.webp",
        "master_id": "13",
        "qualification": "MBBS,MS - OBG",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine",
        "practoRating": ""
    },
    {
        "id": 47,
        "fullname": "Dr. L Divya Bharathi Reddy",
        "designation": "Fertility Specialist",
        "experience": "6 Years",
        "docterImage": "Dr. L Divya Bharathi Reddy.webp",
        "master_id": "14",
        "qualification": "MBBS,DNB (OBG)",
        "practoRating": ""
    },
    {
        "id": 48,
        "fullname": "Dr. Nadikattu Saranya Lakshmi",
        "designation": "Fertility Specialist",
        "experience": "10 Years",
        "docterImage": "Dr. Nadikattu Saranya Lakshmi.webp",
        "master_id": "14",
        "qualification": "MBBS- DGO",
        "areaOfSpecialization": "fellowship in infertility",
        "practoRating": ""
    },
    {
        "id": 49,
        "fullname": "Dr. Pallavi Tapala",
        "designation": "Fertility Specialist",
        "experience": "11 Years",
        "docterImage": "Dr. Pallavi Tapala.webp",
        "master_id": "14",
        "qualification": "MBBS, MS (OBG), FRM",
        "areaOfSpecialization": "FELLOWSHIP IN REPRODUCTIVE MEDICINE at OSHREM , PUNE.",
        "practoRating": ""
    },
    {
        "id": 50,
        "fullname": "Dr. Ramya Vicharapu",
        "designation": "Consultant Fertility Specialist",
        "experience": "18 Years",
        "docterImage": "Dr. Ramya Vicharapu.webp",
        "master_id": "14",
        "qualification": "MBBS, DNB (OBG), FRM (MGR), DMAS",
        "areaOfSpecialization": "DNB (OBG), Post Doctoral fellow in Reproductive Medicine (MGR), Diploma in minimal acess surgery",
        "practoRating": "99%"
    },
    {
        "id": 51,
        "fullname": "Dr. Deepika Boppana",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "13 Years",
        "docterImage": "Dr. Deepika Boppana.webp",
        "master_id": "15",
        "qualification": "MBBS, MS - Obstetrics & Gynaecology-MBBS,MS-OBG",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine\nFellowship in minimal access&nbsp;surgery",
        "practoRating": "99%"
    },
    {
        "id": 52,
        "fullname": "Dr. Vijayalakshmi D",
        "designation": "Clinical Head, Laparoscopic Surgeon & Fertility Specialist",
        "experience": "12 Years",
        "docterImage": "Dr. Vijayalakshmi D.webp",
        "master_id": "15",
        "qualification": "MS (OBG) FRM (RGUHS)",
        "areaOfSpecialization": "MS (OBG) POST DOCTORAL FELLOW IN REPRODUCTIVE MEDICINE (RGUHS), ADVANCED DIPLOMA IN REPRODUCTIVE MEDICINE (KIEL,GERMANY)",
        "practoRating": ""
    },
    {
        "id": 53,
        "fullname": "Dr. Nadikattu Saranya Lakshmi",
        "designation": "Fertility Specialist",
        "experience": "10 Years",
        "docterImage": "Dr. Nadikattu Saranya Lakshmi.webp",
        "master_id": "16",
        "qualification": "MBBS- DGO",
        "areaOfSpecialization": "fellowship in infertility",
        "practoRating": ""
    },
    {
        "id": 54,
        "fullname": "Dr. Pallavi Tapala",
        "designation": "Fertility Specialist",
        "experience": "11 Years",
        "docterImage": "Dr. Pallavi Tapala.webp",
        "master_id": "16",
        "qualification": "MBBS, MS (OBG), FRM",
        "areaOfSpecialization": "FELLOWSHIP IN REPRODUCTIVE MEDICINE at OSHREM , PUNE.",
        "practoRating": ""
    },
    {
        "id": 55,
        "fullname": "Dr. Ramya Vicharapu",
        "designation": "Consultant Fertility Specialist",
        "experience": "18 Years",
        "docterImage": "Dr. Ramya Vicharapu.webp",
        "master_id": "16",
        "qualification": "MBBS, DNB (OBG), FRM (MGR), DMAS",
        "areaOfSpecialization": "DNB (OBG), Post Doctoral fellow in Reproductive Medicine (MGR), Diploma in minimal acess surgery",
        "practoRating": "99%"
    },
    {
        "id": 56,
        "fullname": "Dr. Vijayalakshmi D",
        "designation": "Clinical Head, Laparoscopic Surgeon & Fertility Specialist ",
        "experience": "12 Years",
        "docterImage": "Dr. Vijayalakshmi D.webp",
        "master_id": "16",
        "qualification": "MS (OBG) FRM (RGUHS)",
        "areaOfSpecialization": "MS (OBG) POST DOCTORAL FELLOW IN REPRODUCTIVE MEDICINE (RGUHS), ADVANCED DIPLOMA IN REPRODUCTIVE MEDICINE (KIEL,GERMANY)",
        "practoRating": ""
    },
    {
        "id": 57,
        "fullname": "Dr. L Divya Bharathi Reddy",
        "designation": "Fertility Specialist",
        "experience": "6 Years",
        "docterImage": "Dr. L Divya Bharathi Reddy.webp",
        "master_id": "17",
        "qualification": "MBBS,DNB (OBG)",
        "practoRating": ""
    },
    // {
    //     "id": 58,
    //     "fullname": "Dr. Mathi Harika",
    //     "designation": "Consultant Fertility Specialist",
    //     "experience": "11 Years",
    //     "docterImage": "Dr. Mathi Harika.webp",
    //     "master_id": "17",
    //     "qualification": "MS - OBGYN, FRM",
    //     "areaOfSpecialization": "Fellowship in Reproductive Medicine",
    //     "practoRating": ""
    // },
    {
        "id": 59,
        "fullname": "Dr. Vijayalakshmi D",
        "designation": "Clinical Head, Laparoscopic Surgeon & Fertility Specialist",
        "experience": "12 Years",
        "docterImage": "Dr. Vijayalakshmi D.webp",
        "master_id": "17",
        "qualification": "MS (OBG) FRM (RGUHS)",
        "areaOfSpecialization": "MS (OBG) POST DOCTORAL FELLOW IN REPRODUCTIVE MEDICINE (RGUHS), ADVANCED DIPLOMA IN REPRODUCTIVE MEDICINE (KIEL,GERMANY)",
        "practoRating": ""
    },
    {
        "id": 60,
        "fullname": "Dr. Prinka Bajaj",
        "designation": "Senior Consultant Fertility Specialist",
        "experience": "11 Years",
        "docterImage": "Dr. Prinka Bajaj.webp",
        "master_id": "18",
        "qualification": "DNB-OBG",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine, \nFellowship in Minimal Access Surgery, \nFellowship in USG",
        "practoRating": "100%"
    },
    {
        "id": 61,
        "fullname": "Dr. Rekha Viswanath",
        "designation": "Consultant Fertility Specialist",
        "experience": "14 Years",
        "docterImage": "Dr. Rekha Viswanath.webp",
        "master_id": "18",
        "qualification": "MBBS , MS- OBG , \nDNB ( OBG)",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine",
        "practoRating": ""
    },
    {
        "id": 62,
        "fullname": "Dr. Shalini M A",
        "designation": "Senior Consultant Fertility Specialist",
        "experience": "13 Years",
        "docterImage": "Dr. Shalini M A.webp",
        "master_id": "18",
        "qualification": "MS - OBG , FRM, FMAS",
        "areaOfSpecialization": "Fellowship in Minimal Access Surgery \nFellowship in Reproductive Medicine",
        "practoRating": "100%"
    },
    {
        "id": 63,
        "fullname": "Dr. Shweta .G. Sonwalkar",
        "designation": "Consultant Fertility Specialist",
        "experience": "3 Years",
        "docterImage": "Dr. Shweta .G. Sonwalkar.webp",
        "master_id": "18",
        "qualification": "DGO, PGDCC",
        "practoRating": ""
    },
    {
        "id": 64,
        "fullname": "Dr. Rekha Viswanath",
        "designation": "Consultant Fertility Specialist",
        "experience": "14 Years",
        "docterImage": "Dr. Rekha Viswanath.webp",
        "master_id": "19",
        "qualification": "MBBS , MS- OBG , \nDNB ( OBG)",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine",
        "practoRating": ""
    },
    {
        "id": 65,
        "fullname": "Dr. Shalini M A",
        "designation": "Senior Consultant Fertility Specialist",
        "experience": "13 Years",
        "docterImage": "Dr. Shalini M A.webp",
        "master_id": "19",
        "qualification": "MS - OBG , FRM, FMAS",
        "areaOfSpecialization": "Fellowship in Minimal Access Surgery \nFellowship in Reproductive Medicine",
        "practoRating": "100%"
    },
    {
        "id": 66,
        "fullname": "Dr. Shweta .G. Sonwalkar",
        "designation": "Consultant Fertility Specialist",
        "experience": "3 Years",
        "docterImage": "Dr. Shweta .G. Sonwalkar.webp",
        "master_id": "19",
        "qualification": "DGO, PGDCC",
        "practoRating": ""
    },
    {
        "id": 67,
        "fullname": "Dr. Prinka Bajaj",
        "designation": "Senior Consultant Fertility Specialist",
        "experience": "11 Years",
        "docterImage": "Dr. Prinka Bajaj.webp",
        "master_id": "20",
        "qualification": "DNB-OBG",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine, \nFellowship in Minimal Access Surgery, \nFellowship in USG",
        "practoRating": "100%"
    },
    {
        "id": 68,
        "fullname": "Dr. Rekha Viswanath",
        "designation": "Consultant Fertility Specialist",
        "experience": "14 Years",
        "docterImage": "Dr. Rekha Viswanath.webp",
        "master_id": "20",
        "qualification": "MBBS , MS- OBG , \nDNB ( OBG)",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine",
        "practoRating": ""
    },
    {
        "id": 69,
        "fullname": "Dr. Shalini M A",
        "designation": "Senior Consultant Fertility Specialist",
        "experience": "13 Years",
        "docterImage": "Dr. Shalini M A.webp",
        "master_id": "20",
        "qualification": "MS - OBG , FRM, FMAS",
        "areaOfSpecialization": "Fellowship in Minimal Access Surgery \nFellowship in Reproductive Medicine",
        "practoRating": "100%"
    },
    {
        "id": 70,
        "fullname": "Dr. Prinka Bajaj",
        "designation": "Senior Consultant Fertility Specialist",
        "experience": "11 Years",
        "docterImage": "Dr. Prinka Bajaj.webp",
        "master_id": "21",
        "qualification": "DNB-OBG",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine, \nFellowship in Minimal Access Surgery, \nFellowship in USG",
        "practoRating": "100%"
    },
    {
        "id": 71,
        "fullname": "Dr. Shalini M A",
        "designation": "Senior Consultant Fertility Specialist",
        "experience": "13 Years",
        "docterImage": "Dr. Shalini M A.webp",
        "master_id": "21",
        "qualification": "MS - OBG , FRM, FMAS",
        "areaOfSpecialization": "Fellowship in Minimal Access Surgery \nFellowship in Reproductive Medicine",
        "practoRating": "100%"
    },
    {
        "id": 72,
        "fullname": "Dr. Shweta .G. Sonwalkar",
        "designation": "Consultant Fertility Specialist",
        "experience": "3 Years",
        "docterImage": "Dr. Shweta .G. Sonwalkar.webp",
        "master_id": "21",
        "qualification": "DGO, PGDCC",
        "practoRating": ""
    },
    {
        "id": 73,
        "fullname": "Dr. Prinka Bajaj",
        "designation": "Senior Consultant Fertility Specialist",
        "experience": "11 Years",
        "docterImage": "Dr. Prinka Bajaj.webp",
        "master_id": "22",
        "qualification": "DNB-OBG",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine, \nFellowship in Minimal Access Surgery, \nFellowship in USG",
        "practoRating": "100%"
    },
    {
        "id": 74,
        "fullname": "Dr. Shweta .G. Sonwalkar",
        "designation": "Consultant Fertility Specialist",
        "experience": "3 Years",
        "docterImage": "Dr. Shweta .G. Sonwalkar.webp",
        "master_id": "22",
        "qualification": "DGO, PGDCC",
        "practoRating": ""
    },
    {
        "id": 75,
        "fullname": "Dr. Hema",
        "designation": "Sr. Consultant & Fertility Specialist",
        "experience": "18 Years",
        "docterImage": "Dr. Hema.webp",
        "master_id": "23",
        "qualification": "MRCOG(UK), MD(OBG)",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine",
        "practoRating": "100%"
    },
    {
        "id": 76,
        "fullname": "Dr. Maheswari D",
        "designation": "Consultant Fertility Specialist",
        "experience": "13 Years",
        "docterImage": "Dr. Maheswari D.webp",
        "master_id": "23",
        "qualification": "DNB-OG",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine",
        "practoRating": "100%"
    },
    // {
    //     "id": 77,
    //     "fullname": "Dr. Ashwini Vikram Wagh",
    //     "designation": "Consultant Fertility Specialist",
    //     "experience": "3 Years",
    //     "docterImage": "Dr. Ashwini Vikram Wagh.webp",
    //     "master_id": "24",
    //     "qualification": "DNB-OBG",
    //     "areaOfSpecialization": "Fellowship in Minimal Access Surgery",
    //     "practoRating": ""
    // },
    {
        "id": 78,
        "fullname": "Dr. Nilesh Unmesh Balkawade",
        "designation": "Regional Medical Head & Fertility Specialist",
        "experience": "16 Years",
        "docterImage": "Dr. Nilesh Unmesh Balkawade.webp",
        "master_id": "24",
        "qualification": "MS, DNB, MNAMS, FIAGE, FRM",
        "areaOfSpecialization": "Fellowship at Harvard Boston",
        "practoRating": "95%"
    },
    {
        "id": 79,
        "fullname": "Dr. Sneha Govind Balki",
        "designation": "Sr. Consultant & Fertility Specialist",
        "experience": "10 Years",
        "docterImage": "Dr. Sneha Govind Balki.webp",
        "master_id": "24",
        "qualification": "MBBS DGO DNB FRM",
        "areaOfSpecialization": "Fellowship in Assisted Reproductive Techniques \n\nICOG & UKSH Germany",
        "practoRating": ""
    },
    // {
    //     "id": 80,
    //     "fullname": "Dr. Ashwini Vikram Wagh",
    //     "designation": "Consultant Fertility Specialist",
    //     "experience": "3 Years",
    //     "docterImage": "Dr. Ashwini Vikram Wagh.webp",
    //     "master_id": "25",
    //     "qualification": "DNB-OBG",
    //     "areaOfSpecialization": "Fellowship in Minimal Access Surgery",
    //     "practoRating": ""
    // },
    {
        "id": 81,
        "fullname": "Dr. Nilesh Unmesh Balkawade",
        "designation": "Regional Medical Head & Fertility Specialist",
        "experience": "16 Years",
        "docterImage": "Dr. Nilesh Unmesh Balkawade.webp",
        "master_id": "25",
        "qualification": "MS, DNB, MNAMS, FIAGE, FRM",
        "areaOfSpecialization": "Fellowship at Harvard Boston",
        "practoRating": "95%"
    },
    {
        "id": 82,
        "fullname": "Dr. Sneha Govind Balki",
        "designation": "Sr. Consultant & Fertility Specialist",
        "experience": "10 Years",
        "docterImage": "Dr. Sneha Govind Balki.webp",
        "master_id": "25",
        "qualification": "MBBS DGO DNB FRM",
        "areaOfSpecialization": "Fellowship in Assisted Reproductive Techniques \n\nICOG & UKSH Germany",
        "practoRating": ""
    },
    // {
    //     "id": 83,
    //     "fullname": "Dr. Ashwini Vikram Wagh",
    //     "designation": "Consultant Fertility Specialist",
    //     "experience": "3 Years",
    //     "docterImage": "Dr. Ashwini Vikram Wagh.webp",
    //     "master_id": "26",
    //     "qualification": "DNB-OBG",
    //     "areaOfSpecialization": "Fellowship in Minimal Access Surgery",
    //     "practoRating": ""
    // },
    {
        "id": 84,
        "fullname": "Dr. Sneha Govind Balki",
        "designation": "Sr. Consultant & Fertility Specialist",
        "experience": "10 Years",
        "docterImage": "Dr. Sneha Govind Balki.webp",
        "master_id": "26",
        "qualification": "MBBS DGO DNB FRM",
        "areaOfSpecialization": "Fellowship in Assisted Reproductive Techniques \n\nICOG & UKSH Germany",
        "practoRating": ""
    },
    {
        "id": 85,
        "fullname": "Dr. Nilesh Unmesh Balkawade",
        "designation": "Regional Medical Head & Fertility Specialist",
        "experience": "16 Years",
        "docterImage": "Dr. Nilesh Unmesh Balkawade.webp",
        "master_id": "27",
        "qualification": "MS, DNB, MNAMS, FIAGE, FRM",
        "areaOfSpecialization": "Fellowship at Harvard Boston",
        "practoRating": "95%"
    },
    {
        "id": 86,
        "fullname": "Dr. Pallavi Yuvraj Untwal",
        "designation": "Fertility Specialist",
        "experience": "6 Years",
        "docterImage": "Dr. Pallavi Yuvraj Untwal.webp",
        "master_id": "27",
        "qualification": "MBBS ,DGO",
        "practoRating": ""
    },
    {
        "id": 87,
        "fullname": "Dr. Sneha Govind Balki",
        "designation": "Sr. Consultant & Fertility Specialist",
        "experience": "10 Years",
        "docterImage": "Dr. Sneha Govind Balki.webp",
        "master_id": "27",
        "qualification": "MBBS DGO DNB FRM",
        "areaOfSpecialization": "Fellowship in Assisted Reproductive Techniques \n\nICOG & UKSH Germany",
        "practoRating": ""
    },
    {
        "id": 88,
        "fullname": "Dr. Pratibha Tiwary",
        "designation": "Consultant Fertility Specialist",
        "experience": "14 Years",
        "docterImage": "Dr. Pratibha Tiwary.webp",
        "master_id": "28",
        "qualification": "MS-OBG , DNB-OBG",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine",
        "practoRating": ""
    },
    {
        "id": 89,
        "fullname": "Dr. Baxi Sushma",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "35 Years",
        "docterImage": "Dr. Baxi Sushma.webp",
        "master_id": "29",
        "qualification": "MD - GYNEC",
        "practoRating": "95%"
    },
    {
        "id": 90,
        "fullname": "Dr. Poornima Mathur",
        "designation": "Consultant - Laparoscopic Surgeon, Fertility Specialist",
        "experience": "9 Years",
        "docterImage": "Dr. Poornima Mathur.webp",
        "master_id": "29",
        "qualification": "MD-OBG",
        "areaOfSpecialization": "Fellowship in Assisted Reproductive Techniques and Gynaecological Endoscopy",
        "practoRating": "100%"
    },
    {
        "id": 91,
        "fullname": "Dr. Pratibha Tiwary",
        "designation": "Consultant Fertility Specialist",
        "experience": "14 Years",
        "docterImage": "Dr. Pratibha Tiwary.webp",
        "master_id": "30",
        "qualification": "MS-OBG , DNB-OBG",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine",
        "practoRating": ""
    },
    {
        "id": 92,
        "fullname": "Dr. Gayatri Satpathy",
        "designation": "Consultant Fertility Specialist",
        "experience": "14 Years",
        "docterImage": "Dr. Gayatri Satpathy.webp",
        "master_id": "31",
        "qualification": "MS-OBG",
        "areaOfSpecialization": "Fellowship in Minimally Invasive Gynecological Surgeries",
        "practoRating": "100%"
    },
    {
        "id": 93,
        "fullname": "Dr. Prasanta Kumar Nayak",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "20 years",
        "docterImage": "Dr. Prasanta Kumar Nayak.webp",
        "master_id": "31",
        "qualification": "MD-OBG",
        "areaOfSpecialization": "Fellowship in reproductive medicine \nFellowship in sexual medicine",
        "practoRating": "86%"
    },
    // {
    //     "id": 94,
    //     "fullname": "Dr. Mathi Harika",
    //     "designation": "Consultant Fertility Specialist",
    //     "experience": "11 Years",
    //     "docterImage": "Dr. Mathi Harika.webp",
    //     "master_id": "32",
    //     "qualification": "MS - OBGYN, FRM",
    //     "areaOfSpecialization": "Fellowship in Reproductive Medicine",
    //     "practoRating": ""
    // },
    {
        "id": 95,
        "fullname": "Dr. Ramya Vicharapu",
        "designation": "Consultant Fertility Specialist",
        "experience": "18 Years",
        "docterImage": "Dr. Ramya Vicharapu.webp",
        "master_id": "32",
        "qualification": "MBBS, DNB (OBG), FRM (MGR), DMAS",
        "areaOfSpecialization": "DNB (OBG), Post Doctoral fellow in Reproductive Medicine (MGR), Diploma in minimal acess surgery",
        "practoRating": "99%"
    },
    {
        "id": 96,
        "fullname": "Dr. Venkata Sujatha Vellanki",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "21 Years",
        "docterImage": "Dr. Venkata Sujatha Vellanki.webp",
        "master_id": "32",
        "qualification": "MBBS, OBG MS, MICOG, FAIMER",
        "practoRating": "98%"
    },
    {
        "id": 97,
        "fullname": "Dr. Keerthana V",
        "designation": "Fertility Specialist",
        "experience": "12 years",
        "docterImage": "Dr. Keerthana V.webp",
        "master_id": "33",
        "qualification": "MBBS,DNB(OBG)",
        "areaOfSpecialization": "FNB(REPRODUCTIVE MEDICINE)",
        "practoRating": ""
    },
    {
        "id": 98,
        "fullname": "Dr. Parinaaz Parhar",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "12 Years",
        "docterImage": "Dr. Parinaaz Parhar.webp",
        "master_id": "33",
        "qualification": "MS - OBG, DNB - OBG \n",
        "areaOfSpecialization": "Fellowship in Minimal Access Surgery , Fellowship of National Board in Reproductive Medicine",
        "practoRating": "100%"
    },
    {
        "id": 99,
        "fullname": "Dr. Srinivasa Varalakshmi Yakasiri",
        "designation": "Clinical Head",
        "experience": "30 Yrs",
        "docterImage": "Dr. Srinivasa Varalakshmi Yakasiri.webp",
        "master_id": "33",
        "qualification": "MBBS, DGO",
        "second qualification degree": "M.B.B.S ,",
        "areaOfSpecialization": "#N/A"
    },
    {
        "id": 100,
        "fullname": "Dr. Aaishwari Durge",
        "designation": "Consultant Fertility Specialist",
        "experience": "5 Yrs",
        "docterImage": "Dr. Aaishwari Durge.webp",
        "master_id": "34",
        "qualification": "MS-OBG",
        "second qualification degree": "Fellowship in reproductive medicine \n",
        "areaOfSpecialization": "#N/A"
    },
    {
        "id": 101,
        "fullname": "Dr. Maheswari D",
        "designation": "Consultant Fertility Specialist",
        "experience": "13 Years",
        "docterImage": "Dr. Maheswari D.webp",
        "master_id": "34",
        "qualification": "DNB-OG",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine",
        "practoRating": "100%"
    },
    {
        "id": 102,
        "fullname": "Dr. Nilesh Unmesh Balkawade",
        "designation": "Regional Medical Head & Fertility Specialist",
        "experience": "16 Years",
        "docterImage": "Dr. Nilesh Unmesh Balkawade.webp",
        "master_id": "34",
        "qualification": "MS, DNB, MNAMS, FIAGE, FRM",
        "areaOfSpecialization": "Fellowship at Harvard Boston",
        "practoRating": "95%"
    },
    {
        "id": 103,
        "fullname": "Dr. Parinaaz Parhar",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "12 Years",
        "docterImage": "Dr. Parinaaz Parhar.webp",
        "master_id": "34",
        "qualification": "MS - OBG, DNB - OBG \n",
        "areaOfSpecialization": "Fellowship in Minimal Access Surgery , Fellowship of National Board in Reproductive Medicine",
        "practoRating": "100%"
    },
    {
        "id": 104,
        "fullname": "Dr. Prasanta Kumar Nayak",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "20 years",
        "docterImage": "Dr. Prasanta Kumar Nayak.webp",
        "master_id": "34",
        "qualification": "MD-OBG",
        "areaOfSpecialization": "Fellowship in reproductive medicine \nFellowship in sexual medicine",
        "practoRating": "86%"
    },
    {
        "id": 105,
        "fullname": "Dr. Pratibha Tiwary",
        "designation": "Consultant Fertility Specialist",
        "experience": "14 Years",
        "docterImage": "Dr. Pratibha Tiwary.webp",
        "master_id": "34",
        "qualification": "MS-OBG , DNB-OBG",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine",
        "practoRating": ""
    },
    {
        "id": 106,
        "fullname": "Dr. Prinka Bajaj",
        "designation": "Senior Consultant Fertility Specialist",
        "experience": "11 Years",
        "docterImage": "Dr. Prinka Bajaj.webp",
        "master_id": "34",
        "qualification": "DNB-OBG",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine, \nFellowship in Minimal Access Surgery, \nFellowship in USG",
        "practoRating": "100%"
    },
    {
        "id": 107,
        "fullname": "Dr. Radhika Potluri",
        "designation": "Regional Medical Head & Fertility Specialist",
        "experience": "19 Years",
        "docterImage": "Dr. Radhika Potluri.webp",
        "master_id": "34",
        "qualification": "MS - OBG \n",
        "areaOfSpecialization": "Fellowship in Minimal Access Surgery Fellowship in Reproductive Medicine",
        "practoRating": "99%"
    },
    {
        "id": 108,
        "fullname": "Dr. Raghuveer Karne",
        "designation": "Consultant",
        "experience": "8 Yrs",
        "docterImage": "Dr. Raghuveer Karne.webp",
        "master_id": "34",
        "qualification": "MS (General Surgery), \nDNB (Genitourinary Surgery)",
        "areaOfSpecialization": "Master in Andrology's"
    },
    {
        "id": 109,
        "fullname": "Dr. Sneha Govind Balki",
        "designation": "Sr. Consultant & Fertility Specialist",
        "experience": "10 Years",
        "docterImage": "Dr. Sneha Govind Balki.webp",
        "master_id": "34",
        "qualification": "MBBS DGO DNB FRM",
        "areaOfSpecialization": "Fellowship in Assisted Reproductive Techniques \n\nICOG & UKSH Germany",
        "practoRating": ""
    },
    {
        "id": 110,
        "fullname": "Dr. Prinka Bajaj",
        "designation": "Senior Consultant Fertility Specialist",
        "experience": "11 Years",
        "docterImage": "Dr. Prinka Bajaj.webp",
        "master_id": "35",
        "qualification": "DNB-OBG",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine, \nFellowship in Minimal Access Surgery, \nFellowship in USG",
        "practoRating": "100%"
    },
    {
        "id": 111,
        "fullname": "Dr. Rekha Viswanath",
        "designation": "Consultant Fertility Specialist",
        "experience": "14 Years",
        "docterImage": "Dr. Rekha Viswanath.webp",
        "master_id": "35",
        "qualification": "MBBS , MS- OBG , \nDNB ( OBG)",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine",
        "practoRating": ""
    },
    {
        "id": 112,
        "fullname": "Dr. Shalini M A",
        "designation": "Senior Consultant Fertility Specialist",
        "experience": "13 Years",
        "docterImage": "Dr. Shalini M A.webp",
        "master_id": "35",
        "qualification": "MS - OBG , FRM, FMAS",
        "areaOfSpecialization": "Fellowship in Minimal Access Surgery \nFellowship in Reproductive Medicine",
        "practoRating": "100%"
    },
    {
        "id": 113,
        "fullname": "Dr. Shweta .G. Sonwalkar",
        "designation": "Consultant Fertility Specialist",
        "experience": "3 Years",
        "docterImage": "Dr. Shweta .G. Sonwalkar.webp",
        "master_id": "35",
        "qualification": "DGO, PGDCC",
        "practoRating": ""
    },
    // {
    //     "id": 114,
    //     "fullname": "Dr. Mathi Harika",
    //     "designation": "Consultant Fertility Specialist",
    //     "experience": "11 Years",
    //     "docterImage": "Dr. Mathi Harika.webp",
    //     "master_id": "36",
    //     "qualification": "MS - OBGYN, FRM",
    //     "areaOfSpecialization": "Fellowship in Reproductive Medicine",
    //     "practoRating": ""
    // },
    {
        "id": 115,
        "fullname": "Dr. Radhika Potluri",
        "designation": "Regional Medical Head & Fertility Specialist",
        "experience": "19 Years",
        "docterImage": "Dr. Radhika Potluri.webp",
        "master_id": "36",
        "qualification": "MS - OBG \n",
        "areaOfSpecialization": "Fellowship in Minimal Access Surgery Fellowship in Reproductive Medicine",
        "practoRating": "99%"
    },
    {
        "id": 116,
        "fullname": "Dr. Venkata Sujatha Vellanki",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "21 Years",
        "docterImage": "Dr. Venkata Sujatha Vellanki.webp",
        "master_id": "36",
        "qualification": "MBBS, OBG MS, MICOG, FAIMER",
        "practoRating": "98%"
    },
    {
        "id": 117,
        "fullname": "Dr. Vijayalakshmi D",
        "designation": "Clinical Head, Laparoscopic Surgeon & Fertility Specialist",
        "experience": "12 Years",
        "docterImage": "Dr. Vijayalakshmi D.webp",
        "master_id": "36",
        "qualification": "MS (OBG) FRM (RGUHS)",
        "areaOfSpecialization": "MS (OBG) POST DOCTORAL FELLOW IN REPRODUCTIVE MEDICINE (RGUHS), ADVANCED DIPLOMA IN REPRODUCTIVE MEDICINE (KIEL,GERMANY)",
        "practoRating": ""
    },
    {
        "id": 118,
        "fullname": "Dr. Ramineedi Deepthi Priyadarshini",
        "designation": "Fertility Specialist",
        "experience": "10 Years",
        "docterImage": "Dr. Ramineedi Deepthi Priyadarshini.webp",
        "master_id": "37",
        "qualification": "MS, FNB",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine",
        "practoRating": ""
    },
    {
        "id": 119,
        "fullname": "Dr. Durga Rao Gedela",
        "designation": "Co-founder & Medical Director",
        "experience": "18 Years",
        "docterImage": "Dr. Durga Rao Gedela.webp",
        "master_id": "38",
        "qualification": "MBBS, DGO, MRCOG (UK),",
        "areaOfSpecialization": "Fellowship in Reproductive Endocrinology & Infertility",
        "practoRating": "99%"
    },
    {
        "id": 120,
        "fullname": "Dr. Aaishwari Durge",
        "designation": "Consultant Fertility Specialist",
        "experience": "5 Yrs",
        "docterImage": "Dr. Aaishwari Durge.webp",
        "master_id": "39",
        "qualification": "MS-OBG",
        "second qualification degree": "MBBS , Icog certificate course in gynecological endoscopy\nPost graduate diploma in ART and reproductive endocrinology (UKSH- KIEL GERMANY)",
        "areaOfSpecialization": "#N/A"
    },
    {
        "id": 121,
        "fullname": "Dr. Maheswari D",
        "designation": "Consultant Fertility Specialist",
        "experience": "13 Years",
        "docterImage": "Dr. Maheswari D.webp",
        "master_id": "39",
        "qualification": "DNB-OG",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine",
        "practoRating": "100%"
    },
    {
        "id": 122,
        "fullname": "Dr. Nilesh Unmesh Balkawade",
        "designation": "Regional Medical Head & Fertility Specialist",
        "experience": "16 Years",
        "docterImage": "Dr. Nilesh Unmesh Balkawade.webp",
        "master_id": "39",
        "qualification": "MS, DNB, MNAMS, FIAGE, FRM",
        "areaOfSpecialization": "Fellowship at Harvard Boston",
        "practoRating": "95%"
    },
    {
        "id": 123,
        "fullname": "Dr. Parinaaz Parhar",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "12 Years",
        "docterImage": "Dr. Parinaaz Parhar.webp",
        "master_id": "39",
        "qualification": "MS - OBG, DNB - OBG \n",
        "areaOfSpecialization": "Fellowship in Minimal Access Surgery , Fellowship of National Board in Reproductive Medicine",
        "practoRating": "100%"
    },
    {
        "id": 124,
        "fullname": "Dr. Prasanta Kumar Nayak",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "20 years",
        "docterImage": "Dr. Prasanta Kumar Nayak.webp",
        "master_id": "39",
        "qualification": "MD-OBG",
        "areaOfSpecialization": "Fellowship in reproductive medicine \nFellowship in sexual medicine",
        "practoRating": "86%"
    },
    {
        "id": 125,
        "fullname": "Dr. Pratibha Tiwary",
        "designation": "Consultant Fertility Specialist",
        "experience": "14 Years",
        "docterImage": "Dr. Pratibha Tiwary.webp",
        "master_id": "39",
        "qualification": "MS-OBG , DNB-OBG",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine",
        "practoRating": ""
    },
    {
        "id": 126,
        "fullname": "Dr. Prinka Bajaj",
        "designation": "Senior Consultant Fertility Specialist",
        "experience": "11 Years",
        "docterImage": "Dr. Prinka Bajaj.webp",
        "master_id": "39",
        "qualification": "DNB-OBG",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine, \nFellowship in Minimal Access Surgery, \nFellowship in USG",
        "practoRating": "100%"
    },
    {
        "id": 127,
        "fullname": "Dr. Radhika Potluri",
        "designation": "Regional Medical Head & Fertility Specialist",
        "experience": "19 Years",
        "docterImage": "Dr. Radhika Potluri.webp",
        "master_id": "39",
        "qualification": "MS - OBG \n",
        "areaOfSpecialization": "Fellowship in Minimal Access Surgery Fellowship in Reproductive Medicine",
        "practoRating": "99%"
    },
    {
        "id": 128,
        "fullname": "Dr. Raghuveer Karne",
        "designation": "Consultant",
        "experience": "8 Yrs",
        "docterImage": "Dr. Raghuveer Karne.webp",
        "master_id": "39",
        "qualification": "MS (General Surgery), \nDNB (Genitourinary Surgery)",
        "areaOfSpecialization": "Master in Andrology's"
    },
    {
        "id": 129,
        "fullname": "Dr. Sneha Govind Balki",
        "designation": "Sr. Consultant & Fertility Specialist",
        "experience": "10 Years",
        "docterImage": "Dr. Sneha Govind Balki.webp",
        "master_id": "39",
        "qualification": "MBBS DGO DNB FRM",
        "areaOfSpecialization": "Fellowship in Assisted Reproductive Techniques \n\nICOG & UKSH Germany",
        "practoRating": ""
    },
    {
        "id": 130,
        "fullname": "Dr. Aaishwari Durge",
        "designation": "Consultant Fertility Specialist",
        "experience": "5 Yrs",
        "docterImage": "Dr. Aaishwari Durge.webp",
        "master_id": "40",
        "qualification": "MS-OBG",
        "second qualification degree": "MBBS , Icog certificate course in gynecological endoscopy\nPost graduate diploma in ART and reproductive endocrinology (UKSH- KIEL GERMANY)",
        "areaOfSpecialization": "#N/A"
    },
    {
        "id": 131,
        "fullname": "Dr. Maheswari D",
        "designation": "Consultant Fertility Specialist",
        "experience": "13 Years",
        "docterImage": "Dr. Maheswari D.webp",
        "master_id": "40",
        "qualification": "DNB-OG",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine",
        "practoRating": "100%"
    },
    {
        "id": 132,
        "fullname": "Dr. Nilesh Unmesh Balkawade",
        "designation": "Regional Medical Head & Fertility Specialist",
        "experience": "16 Years",
        "docterImage": "Dr. Nilesh Unmesh Balkawade.webp",
        "master_id": "40",
        "qualification": "MS, DNB, MNAMS, FIAGE, FRM",
        "areaOfSpecialization": "Fellowship at Harvard Boston",
        "practoRating": "95%"
    },
    {
        "id": 133,
        "fullname": "Dr. Parinaaz Parhar",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "12 Years",
        "docterImage": "Dr. Parinaaz Parhar.webp",
        "master_id": "40",
        "qualification": "MS - OBG, DNB - OBG \n",
        "areaOfSpecialization": "Fellowship in Minimal Access Surgery , Fellowship of National Board in Reproductive Medicine",
        "practoRating": "100%"
    },
    {
        "id": 134,
        "fullname": "Dr. Prasanta Kumar Nayak",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "20 years",
        "docterImage": "Dr. Prasanta Kumar Nayak.webp",
        "master_id": "40",
        "qualification": "MD-OBG",
        "areaOfSpecialization": "Fellowship in reproductive medicine \nFellowship in sexual medicine",
        "practoRating": "86%"
    },
    {
        "id": 135,
        "fullname": "Dr. Pratibha Tiwary",
        "designation": "Consultant Fertility Specialist",
        "experience": "14 Years",
        "docterImage": "Dr. Pratibha Tiwary.webp",
        "master_id": "40",
        "qualification": "MS-OBG , DNB-OBG",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine",
        "practoRating": ""
    },
    {
        "id": 136,
        "fullname": "Dr. Prinka Bajaj",
        "designation": "Senior Consultant Fertility Specialist",
        "experience": "11 Years",
        "docterImage": "Dr. Prinka Bajaj.webp",
        "master_id": "40",
        "qualification": "DNB-OBG",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine, \nFellowship in Minimal Access Surgery, \nFellowship in USG",
        "practoRating": "100%"
    },
    {
        "id": 137,
        "fullname": "Dr. Radhika Potluri",
        "designation": "Regional Medical Head & Fertility Specialist",
        "experience": "19 Years",
        "docterImage": "Dr. Radhika Potluri.webp",
        "master_id": "40",
        "qualification": "MS - OBG \n",
        "areaOfSpecialization": "Fellowship in Minimal Access Surgery Fellowship in Reproductive Medicine",
        "practoRating": "99%"
    },
    {
        "id": 138,
        "fullname": "Dr. Raghuveer Karne",
        "designation": "Consultant",
        "experience": "8 Yrs",
        "docterImage": "Dr. Raghuveer Karne.webp",
        "master_id": "40",
        "qualification": "MS (General Surgery), \nDNB (Genitourinary Surgery)",
        "areaOfSpecialization": "Master in Andrology's"
    },
    {
        "id": 139,
        "fullname": "Dr. Sneha Govind Balki",
        "designation": "Sr. Consultant & Fertility Specialist",
        "experience": "10 Years",
        "docterImage": "Dr. Sneha Govind Balki.webp",
        "master_id": "40",
        "qualification": "MBBS DGO DNB FRM",
        "areaOfSpecialization": "Fellowship in Assisted Reproductive Techniques \n\nICOG & UKSH Germany",
        "practoRating": ""
    },
    {
        "id": 140,
        "fullname": "Dr. Jalagam Kavya Rao",
        "designation": "Regional Medical Head & Fertility Specialist",
        "experience": "10 Years",
        "docterImage": "Dr. Jalagam Kavya Rao.webp",
        "master_id": "34",
        "qualification": "MBBS, MS OBG, FRM, FIGL",
        "areaOfSpecialization": "Fellowship in Reproductive Medicine fro m OSHREM- 2017-2018, Fellowship in Gynecological Laproscopy- KEIL- Germany-2020-2021",
        "practoRating": "100%"
    },
    {
        "id": 141,
        "fullname": "Dr. Venkata Sujatha Vellanki",
        "designation": "Clinical Head & Fertility Specialist",
        "experience": "21 Years",
        "docterImage": "Dr. Venkata Sujatha Vellanki.webp",
        "master_id": "34",
        "qualification": "MBBS, OBG MS, MICOG, FAIMER",
        "practoRating": "98%"
    },
]

export default newdoctorslp3;