export const videos = [
    {
        "id": "1",
        "influencer_name": "Kishor Babu",
        "videoId": "Xxfm_uXZa-Y",
        "VideoTitleText": "Real Fertility Story | PCOD And Infertility | IUI Babies | Fertility Treatment Testimonial",
        "videoImage": "/images/home/testimonials/Kishor Babu.jpg",
        "youTubeVideoUrl": "https://www.youtube.com/shorts/Xxfm_uXZa-Y",
        "isSelected": false,
    },
    {
        "id": "2",
        "influencer_name": "Madhu Kiran",
        "videoId": "2__vfnI8BF0",
        "VideoTitleText": "Fertility Story | Advanced Maternal Age | IVF Success | IVF Success Testimonial",
        "videoImage": "/images/home/testimonials/Madhu Kiran.jpg",
        "youTubeVideoUrl": "https://www.youtube.com/shorts/2__vfnI8BF0",
        "isSelected": false,
    },
    {
        "id": "3",
        "influencer_name": "Deevi Prasad",
        "videoId": "PqtmTf0iBc8",
        "VideoTitleText": "Fertility Story | Fallopian Tube Blockage | IVF Success",
        "videoImage": "/images/home/testimonials/Deevi Prasad.jpg",
        "youTubeVideoUrl": "https://www.youtube.com/shorts/PqtmTf0iBc8",
        "isSelected": false,
    },
    {
        "id": "4",
        "influencer_name": "Shekhar Almury",
        "videoId": "7wwrDjGFaMY",
        "VideoTitleText": "IVF Success Story | Healthy IVF Twin Babies | Pregnancy After Recurrent Miscarriages",
        "videoImage": "/images/home/testimonials/Shekhar Almury.jpg",
        "youTubeVideoUrl": "https://www.youtube.com/shorts/7wwrDjGFaMY",
        "isSelected": false,
    },
    {
        "id": "5",
        "influencer_name": "Vasudev & Swapna",
        "videoId": "qDRWwc0iFgc",
        "VideoTitleText": "Happy IVF Couple | Pregnancy After 12 Years | Advanced Maternal Age",
        "videoImage": "/images/home/testimonials/Vasudev & Swapna.jpg",
        "youTubeVideoUrl": "https://www.youtube.com/shorts/qDRWwc0iFgc",
        "isSelected": false,
    }
];

export const cityToVideos = {
    hyderabad: [1, 2, 3, 4, 5],
    "banjara-hills": [1, 2, 3, 4, 5],
    gachibowli: [1, 2, 3, 4, 5],
    dilshuknagar: [1, 2, 3, 4, 5],
    secunderabad: [1, 2, 3, 4, 5],
    miyapur: [1, 2, 3, 4, 5],
    kompally: [1, 2, 3, 4, 5],
    uppal: [1, 2, 3, 4, 5],
    hanamkonda: [1, 2, 3, 4, 5],
    karimnagar: [1, 2, 3, 4, 5],
    vijayawada: [1, 2, 3, 4, 5],
    visakhapatnam: [1, 2, 3, 4, 5],
    guntur: [1, 2, 3, 4, 5],
    ongole: [1, 2, 3, 4, 5],
    tirupati: [1, 2, 3, 4, 5],
    kurnool: [1, 2, 3, 4, 5],
    bengaluru: [4, 5, 1, 2, 3],
    hsr: [4, 5, 1, 2, 3],
    banashankari: [4, 5, 1, 2, 3],
    hebbal: [4, 5, 1, 2, 3],
    belagavi: [4, 5, 1, 2, 3],
    chennai: [4, 5, 1, 2, 3],
    pune: [4, 5, 1, 2, 3],
    wakad: [4, 5, 1, 2, 3],
    kharadi: [4, 5, 1, 2, 3],
    nashik: [4, 5, 1, 2, 3],
    raipur: [4, 5, 1, 2, 3],
    vadodara: [4, 5, 1, 2, 3],
    ranchi: [4, 5, 1, 2, 3],
    bhubaneswar: [4, 5, 1, 2, 3],
    suryaraopeta: [1, 2, 3, 4, 5],
    tolichowki: [1, 2, 3, 4, 5],
    india: [4, 5, 1, 2, 3],
    karnataka: [4, 5, 1, 2, 3],
    andhrapradesh: [1, 2, 3, 4, 5],
    kakinada: [1, 2, 3, 4, 5],
    "egg-freezing": [],
    madhurawada: [1, 2, 3, 4, 5],
    meta: [4, 5, 1, 2, 3],
    google: [4, 5, 1, 2, 3]
};


