export const videos = [
    {
        "id": "1",
        "influencer_name": "Shiva Jyothi",
        "videoId": "HARgKEK7ihA",
        "VideoTitleText": "పిల్లల కోసం ప్రయత్నం | Kids Planning | Shiva Jyothi",
        "videoImage": "https://images.oasisindia.in/website/home/influencers/Shiva Jyothi.webp",
        "youTubeVideoUrl": "https://youtube.com/shorts/HARgKEK7ihA",
        "isSelected": false,
    },
    {
        "id": "2",
        "influencer_name": "Vithika Sheru",
        "videoId": "TSUFeOgscYM",
        "VideoTitleText": "Everything about pregnancy planning | Vithika Sheru",
        "videoImage": "https://images.oasisindia.in/website/home/influencers/Vrithika.webp",
        "youTubeVideoUrl": "https://youtube.com/shorts/TSUFeOgscYM",
        "isSelected": false,
    },
    {
        "id": "3",
        "influencer_name": "Marina & Rohit",
        "videoId": "9qT8zaJV56U",
        "VideoTitleText": "Everything about pregnancy planning | Vithika Sheru",
        "videoImage": "https://images.oasisindia.in/website/home/influencers/Marina & Rohith.webp",
        "youTubeVideoUrl": "https://youtube.com/shorts/9qT8zaJV56U",
        "isSelected": false,
    },
    {
        "id": "4",
        "influencer_name": "Rapid Rashmi (Kannada)",
        "videoId": "p6W3t5FcIyQ",
        "VideoTitleText": "Infertility, Busting Myths about IVF | Rapid Rashmi",
        "videoImage": "https://images.oasisindia.in/website/home/influencers/Rashmi.webp",
        "youTubeVideoUrl": "https://youtube.com/shorts/p6W3t5FcIyQ",
        "isSelected": false,
    },
    {
        "id": "5",
        "influencer_name": "Tejaswini Gowda (Telugu)",
        "videoId": "KxeaEIQCtNc",
        "VideoTitleText": "పిల్లలు? Pregnancy? Fertility?🤔 | Tejaswini Gowda",
        "videoImage": "https://images.oasisindia.in/website/home/influencers/Tejaswini.webp",
        "youTubeVideoUrl": "https://youtube.com/shorts/KxeaEIQCtNc",
        "isSelected": false,
    },
    {
        "id": "6",
        "influencer_name": "Nandhu & Chintu (Telugu)",
        "videoId": "-zhdAj87Tu0",
        "VideoTitleText": "PLANNING PREGNANCY? | INFORMATIVE VLOG | NACH",
        "videoImage": "https://images.oasisindia.in/website/home/influencers/Nandhu.webp",
        "youTubeVideoUrl": "https://youtube.com/shorts/-zhdAj87Tu0",
        "isSelected": false,
    },
    {
        "id": "7",
        "influencer_name": "Vaishnavi",
        "videoId": "26lJM-Gt6E4",
        "VideoTitleText": "IVF & Pregnancy ( what I learnt from an expert) | Vaishnavi",
        "videoImage": "https://images.oasisindia.in/website/home/influencers/Vaishnavi.webp",
        "youTubeVideoUrl": "https://youtube.com/shorts/26lJM-Gt6E4",
        "isSelected": false,
    },
    {
        "id": "8",
        "influencer_name": "Hrutha",
        "videoId": "KDz_mfG1AEo",
        "VideoTitleText": "What is Egg Freezing | Hrutha",
        "videoImage": "https://images.oasisindia.in/website/home/influencers/Hrutha.webp",
        "youTubeVideoUrl": "https://youtu.be/KDz_mfG1AEo",
        "isSelected": false,
    },
    {
        "id": "9",
        "influencer_name": "Ananya",
        "videoId": "Jrb9E4lN9VM",
        "VideoTitleText": "How Oasis Fertility Transforms Dreams Into Reality | Ananya",
        "videoImage": "https://images.oasisindia.in/website/home/influencers/Ananya.webp",
        "youTubeVideoUrl": "https://youtube.com/shorts/Jrb9E4lN9VM",
        "isSelected": false,
    },
    {
        "id": "10",
        "influencer_name": "Nisha",
        "videoId": "8JGUqEfB0dM",
        "VideoTitleText": "Creating Families: A Day in the Life at Oasis Fertility | Nisha",
        "videoImage": "https://images.oasisindia.in/website/home/influencers/Nisha.webp",
        "youTubeVideoUrl": "https://www.youtube.com/shorts/8JGUqEfB0dM",
        "isSelected": false,
    }
];

export const cityToVideos = {
    hyderabad: [1, 6, 5, 2],
    "banjara-hills": [1, 6, 5, 2],
    gachibowli: [1, 6, 5, 2],
    dilshuknagar: [1, 6, 5, 2],
    secunderabad: [1, 6, 5, 2],
    miyapur: [1, 6, 5, 2],
    kompally: [1, 6, 5, 2],
    uppal: [1, 6, 5, 2],
    hanamkonda: [1, 6, 5, 2],
    karimnagar: [1, 6, 5, 2],
    vijayawada: [1, 6, 5, 2],
    visakhapatnam: [1, 6, 5, 2],
    guntur: [1, 6, 5, 2],
    ongole: [1, 6, 5, 2],
    tirupati: [1, 6, 5, 2],
    kurnool: [1, 6, 5, 2],
    bengaluru: [7, 4, 1, 5],
    hsr: [7, 4, 1, 5],
    banashankari: [7, 4, 1, 5],
    hebbal: [7, 4, 1, 5],
    belagavi: [7, 4, 1, 5],
    chennai: [7, 4, 1, 5],
    pune: [8, 10, 5, 2],
    wakad: [8, 10, 5, 2],
    kharadi: [8, 10, 5, 2],
    nashik: [8, 10, 5, 2],
    raipur: [8, 10, 5, 2],
    vadodara: [8, 10, 5, 2],
    ranchi: [8, 10, 5, 2],
    bhubaneswar: [8, 10, 5, 2],
    suryaraopeta: [1, 6, 5, 2],
    tolichowki: [1, 6, 5, 2],
    india: [8, 10, 1, 2],
    karnataka: [7, 4, 1, 5],
    andhrapradesh: [1, 6, 5, 2],
    kakinada: [1, 6, 5, 2],
    "egg-freezing": [1, 6, 5, 2],
    madhurawada: [1, 6, 5, 2],
    meta: [8, 10, 1, 2],
    google: [8, 10, 1, 2]
};

