const master = [
    {
      id: "1",
      center_name: "hyderabad",
      center_name_heading: "Hyderabad",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Hyderabad",
      phone: "tel:+91 9513736432",
      our_center: "hyderabad, Hyderabad", 
      status: "1",
    },
    {
      id: "2",
      center_name: "banjara-hills",
      center_name_heading: "Banjara Hills",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Hyderabad",
      phone: "tel:+91 9513736432",
      our_center: "Banjara Hills, Hyderabad",
      status: "1",
    },
    {
      id: "3",
      center_name: "gachibowli",
      center_name_heading: "Gachibowli",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Hyderabad",
      phone: "tel:+91 9513736432",
      our_center: "Gachibowli, Hyderabad",
      status: "1",
    }, 
    {
      id: "4",
      center_name: "dilshuknagar", 
      center_name_heading: "Dilshuknagar",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Hyderabad",
      phone: "tel:+91 9513736432",
      our_center: "Dilsuknagar, Hyderabad", 
      status: "1",
    },
    {
      id: "5",
      center_name: "secunderabad",
      center_name_heading: "Secunderabad",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Hyderabad",
      phone: "tel:+91 9513736432",
      our_center: "Secundrabad, Hyderabad",
      status: "1",
    },
    {
      id: "6",
      center_name: "miyapur",
      center_name_heading: "Miyapur",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Hyderabad",
      phone: "tel:+91 9513736432",
      our_center: "Miyapur, Hyderabad",
      status: "1",
    },
    {
      id: "7",
      center_name: "kompally",
      center_name_heading: "Kompally",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Hyderabad",
      phone: "tel:+91 9513736432",
      our_center: "Kompally, Hyderabad",
      status: "1",
    },
    {
      id: "8",
      center_name: "uppal",
      center_name_heading: "Uppal",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Hyderabad",
      phone: "tel:+91 9513736432",
      our_center: "Uppal, Hyderabad",
      status: "1",
    },
    
    {
      id: "10",
      center_name: "hanamkonda",
      center_name_heading: "Hanamkonda",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Hanamkonda",
      phone: "tel:+91 9513736432",
      our_center: "Hanmakonda",
      status: "1",
    },
    {
      id: "11",
      center_name: "karimnagar",
      center_name_heading: "Karimnagar",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Karimnagar",
      phone: "tel:+91 9513736432",
      our_center: "Karimnagar",
      status: "1",
    },
    {
      id: "12",
      center_name: "vijayawada",
      center_name_heading: "Vijayawada",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Vijayawada",
      phone: "tel:+91 9513736432",
      our_center: "Venkateshwara Nagar,Vijayawada",
      status: "1",
    },
    {
      id: "13",
      center_name: "visakhapatnam",
      center_name_heading: "Visakhapatnam",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Vizag",
      phone: "tel:+91 9513736432",
      our_center: "Visakhapatnam,Vizag",
      status: "1",
    },
    {
      id: "14",
      center_name: "guntur",
      center_name_heading: "Guntur",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Guntur",
      phone: "tel:+91 9513736432",
      our_center: "Guntur",
      status: "1",
    },
    {
      id: "15",
      center_name: "ongole",
      center_name_heading: "Ongole",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Ongole",
      phone: "tel:+91 9513736432",
      our_center: "Ongole",
      status: "1",
    },
    {
      id: "16",
      center_name: "tirupati",
      center_name_heading: "Tirupati",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Tirupati",
      phone: "tel:+91 9513736432",
      our_center: "Tirupati",
      status: "1",
    },
    {
      id: "17",
      center_name: "kurnool",
      center_name_heading: "Kurnool",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Kurnool",
      phone: "tel:+91 9513736432",
      our_center: "Kurnool",
      status: "1",
    },
    {
      id: "18",
      center_name: "bengaluru",
      center_name_heading: "Bengaluru",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Bengaluru",
      phone: "tel:+91 9513736432",
      our_center: "Bengaluru",
      status: "1",
    },
    {
      id: "19",
      center_name: "hsr",
      center_name_heading: "HSR Layout",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Bengaluru",
      phone: "tel:+91 9513736432",
      our_center: "HSR Layout,Bengaluru",
      status: "1",
    },
    {
      id: "20",
      center_name: "banashankari",
      center_name_heading: "Banashankari",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Bengaluru",
      phone: "tel:+91 9513736432",
      our_center: "Banashankari,Bengaluru",
      status: "1",
    },
    {
      id: "21",
      center_name: "hebbal",
      center_name_heading: "Hebbal",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Bengaluru",
      phone: "tel:+91 9513736432",
      our_center: "Hebbal,Bengaluru ",
      status: "1",
    },
    {
      id: "22",
      center_name: "belagavi",
      center_name_heading: "Belagavi",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Belagavi",
      phone: "tel:+91 9513736432",
      our_center: "Belagavi",
      status: "1",
    },
    {
      id: "23",
      center_name: "chennai",
      center_name_heading: "Chennai",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Chennai",
      phone: "tel:+91 9513736432",
      our_center: "Chennai",
      status: "1",
    },
    {
      id: "24",
      center_name: "pune",
      center_name_heading: "Pune",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Pune",
      phone: "tel:+91 9513736432",
      our_center: "Pune",
      status: "1",
    },
    {
      id: "25",
      center_name: "wakad",
      center_name_heading: "Wakad",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Pune",
      phone: "tel:+91 9513736432",
      our_center: "Wakad , Pune",
      status: "1",
    },
    {
      id: "26",
      center_name: "kharadi",
      center_name_heading: "Kharadi",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Pune",
      phone: "tel:+91 9513736432",
      our_center: "Kharadi , Pune",
      status: "1",
    },
    {
      id: "27",
      center_name: "nashik",
      center_name_heading: "Nashik",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Nashik",
      phone: "tel:+91 9513736432",
      our_center: "Nashik",
      status: "1",
    },
    {
      id: "28",
      center_name: "raipur",
      center_name_heading: "Raipur",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Raipur",
      phone: "tel:+91 9513736432",
      our_center: "Raipur",
      status: "1",
    },
    {
      id: "29",
      center_name: "vadodara",
      center_name_heading: "Vadodara",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Vadodara",
      phone: "tel:+91 9513736432",
      our_center: "Vadodara",
      status: "1",
    },
    {
      id: "30",
      center_name: "ranchi",
      center_name_heading: "Ranchi",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Ranchi",
      phone: "tel:+91 9513736432",
      our_center: "Ranchi",
      status: "1",
    },
    {
      id: "31",
      center_name: "bhubaneswar",
      center_name_heading: "Bhubaneswar",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Bhubaneswar",
      phone: "tel:+91 9513736432",
      our_center: "Bhubaneswar",
      status: "1",
    },
    {
      id: "32",
      center_name: "suryaraopeta",
      center_name_heading: "Suryaraopeta",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Suryaraopeta",
      phone: "tel:+91 9513736432",
      our_center: "Suryaraopeta,Vijayawada",
      status: "1",
    },
    {
        id: "33",
        center_name: "tolichowki",
        center_name_heading: "Tolichowki",
        additional_content: "Avail Our Special Offer",
        title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
        hero_title: "Your Journey to Parenthood Starts Here",
        location: "Hyderabad",
        phone: "tel:+91 9513736432",
        our_center: "Tolichowki, Hyderabad",
        status: "1",
      },
    {
      id: "34",
      center_name: "india",
      center_name_heading: "India",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "India",
      phone: "tel:+91 9513736432",
      our_center: "India",
      status: "1",
    },
    {
      id: "35",
      center_name: "karnataka",
      center_name_heading: "Karnataka",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Karnataka",
      phone: "tel:+91 9513736432",
      our_center: "Telengana",
      status: "1",
    },
    {
      id: "36",
      center_name: "andhrapradesh",
      center_name_heading: "Andhrapradesh",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "AndhraPradesh",
      phone: "tel:+91 9513736432",
      our_center: "AndhraPradesh",
      status: "1",
    },
    {
      id: "37",
      center_name: "kakinada",
      center_name_heading: "Kakinada",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Kakinada",
      phone: "tel:+91 9513736432",
      our_center: "Kakinada",
      status: "1",
    },
    {
      id: "38",
      center_name: "madhurawada",
      center_name_heading: "Madhurawada",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Madhurawada",
      phone: "tel:+91 9513736432",
      our_center: "Madhurawada",
      status: "1",
    },
    {
      id: "39",
      center_name: "meta",
      center_name_heading: "India",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "India",
      phone: "tel:+91 9513736432",
      our_center: "India",
      status: "1",
    },
    {
      id: "40",
      center_name: "google",
      center_name_heading: "India",
      additional_content: "Avail Our Special Offer",
      title: "Valid From 25th July&nbsp;Till&nbsp;27th&nbsp;July",
      hero_title: "Your Journey to Parenthood Starts Here",
      location: "Kakinada",
      phone: "tel:+91 9513736432",
      our_center: "India",
      status: "1",
    },
  ];
  
  export default master;
  